package com.bytedance.sdk.component.adexpress.ReZ;

import android.content.Context;
import android.graphics.Color;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout.LayoutParams;
import android.widget.FrameLayout;
import android.widget.ImageView.ScaleType;
import android.widget.ImageView;
import android.widget.LinearLayout.LayoutParams;
import android.widget.LinearLayout;
import android.widget.RelativeLayout.LayoutParams;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.bytedance.adsdk.Zh.cz;
import com.bytedance.sdk.component.adexpress.cr.Au;
import com.bytedance.sdk.component.adexpress.cz.xf;
import com.bytedance.sdk.component.utils.Lrd;
import com.bytedance.sdk.component.utils.Qf;

public class PjT {
    public static View Au(Context context0) {
        View view0 = new LinearLayout(context0);
        view0.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        ((LinearLayout)view0).setOrientation(1);
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFE6);
        LinearLayout.LayoutParams linearLayout$LayoutParams0 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams0.gravity = 17;
        linearLayout$LayoutParams0.setMargins(0, Qf.PjT(context0, 12.0f), 0, 0);
        textView0.setLayoutParams(linearLayout$LayoutParams0);
        textView0.setVisibility(4);
        textView0.setTextSize(1, 18.0f);
        ((ViewGroup)view0).addView(textView0);
        TextView textView1 = new TextView(context0);
        textView1.setId(0x7D06FFE8);
        LinearLayout.LayoutParams linearLayout$LayoutParams1 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams1.gravity = 17;
        textView1.setLayoutParams(linearLayout$LayoutParams1);
        textView1.setVisibility(4);
        textView1.setTextSize(1, 14.0f);
        ((ViewGroup)view0).addView(textView1);
        LinearLayout linearLayout0 = new LinearLayout(context0);
        linearLayout0.setId(0x7D06FFE7);
        LinearLayout.LayoutParams linearLayout$LayoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams2.gravity = 17;
        linearLayout0.setLayoutParams(linearLayout$LayoutParams2);
        linearLayout0.setGravity(17);
        linearLayout0.setOrientation(1);
        ((ViewGroup)view0).addView(linearLayout0);
        ImageView imageView0 = new ImageView(context0);
        imageView0.setId(0x7D06FFE5);
        imageView0.setLayoutParams(new LinearLayout.LayoutParams(Qf.PjT(context0, 60.0f), Qf.PjT(context0, 60.0f)));
        imageView0.setImageDrawable(Lrd.ReZ(context0, "tt_splash_rock"));
        linearLayout0.addView(imageView0);
        TextView textView2 = new TextView(context0);
        textView2.setId(0x7D06FFE4);
        LinearLayout.LayoutParams linearLayout$LayoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams3.gravity = 17;
        linearLayout$LayoutParams3.setMargins(0, Qf.PjT(context0, 12.0f), 0, 0);
        textView2.setLayoutParams(linearLayout$LayoutParams3);
        textView2.setSingleLine(true);
        textView2.setText(context0.getString(Lrd.Zh(context0, "tt_splash_rock_top_text")));
        textView2.setTextColor(-1);
        textView2.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView2.setTextSize(1, 18.0f);
        ((ViewGroup)view0).addView(textView2);
        TextView textView3 = new TextView(context0);
        textView3.setId(0x7D06FFE3);
        LinearLayout.LayoutParams linearLayout$LayoutParams4 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams4.gravity = 17;
        linearLayout$LayoutParams4.setMargins(0, Qf.PjT(context0, 12.0f), 0, 0);
        textView3.setLayoutParams(linearLayout$LayoutParams4);
        textView3.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView3.setTextSize(1, 14.0f);
        textView3.setText(context0.getString(Lrd.Zh(context0, "tt_splash_rock_text")));
        textView3.setTextColor(-1);
        ((ViewGroup)view0).addView(textView3);
        return view0;
    }

    public static View JQp(Context context0) {
        View view0 = new RelativeLayout(context0);
        view0.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        ((RelativeLayout)view0).setGravity(16);
        ((ViewGroup)view0).setClipChildren(false);
        ImageView imageView0 = new ImageView(context0);
        imageView0.setId(0x7D06FFEF);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams0 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 36.0f), Qf.PjT(context0, 36.0f));
        relativeLayout$LayoutParams0.addRule(14);
        relativeLayout$LayoutParams0.addRule(8, 0x7D06FFEC);
        relativeLayout$LayoutParams0.setMargins(0, 0, 0, Qf.PjT(context0, -24.0f));
        imageView0.setLayoutParams(relativeLayout$LayoutParams0);
        imageView0.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_circle"));
        imageView0.setAlpha(0.0f);
        ImageView imageView1 = new ImageView(context0);
        imageView1.setId(0x7D06FFEE);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams1 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 67.0f), Qf.PjT(context0, 51.0f));
        relativeLayout$LayoutParams1.addRule(14);
        relativeLayout$LayoutParams1.addRule(1, 0x7D06FFEC);
        relativeLayout$LayoutParams1.addRule(8, 0x7D06FFEC);
        relativeLayout$LayoutParams1.setMargins(Qf.PjT(context0, -7.0f), 0, 0, Qf.PjT(context0, -20.0f));
        imageView1.setLayoutParams(relativeLayout$LayoutParams1);
        imageView1.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_finger"));
        imageView1.setAlpha(0.0f);
        ImageView imageView2 = new ImageView(context0);
        imageView2.setId(0x7D06FFED);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams2 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 10.0f), 0);
        relativeLayout$LayoutParams2.addRule(14);
        relativeLayout$LayoutParams2.addRule(8, 0x7D06FFEC);
        imageView2.setLayoutParams(relativeLayout$LayoutParams2);
        imageView2.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_bg"));
        ImageView imageView3 = new ImageView(context0);
        imageView3.setId(0x7D06FFEC);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams3 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 14.0f), Qf.PjT(context0, 100.0f));
        relativeLayout$LayoutParams3.addRule(14);
        imageView3.setLayoutParams(relativeLayout$LayoutParams3);
        imageView3.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_arrow"));
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFEB);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams4 = new RelativeLayout.LayoutParams(-1, -2);
        relativeLayout$LayoutParams4.addRule(3, 0x7D06FFEC);
        textView0.setLayoutParams(relativeLayout$LayoutParams4);
        textView0.setTextColor(-1);
        textView0.setText("wipe up");
        textView0.setTextSize(2, 18.0f);
        textView0.setShadowLayer(((float)Qf.PjT(context0, 4.0f)), ((float)Qf.PjT(context0, 3.0f)), ((float)Qf.PjT(context0, 3.0f)), Color.parseColor("#99000000"));
        textView0.setGravity(1);
        TextView textView1 = new TextView(context0);
        textView1.setId(0x7D06FFEA);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        relativeLayout$LayoutParams5.addRule(3, 0x7D06FFEB);
        textView1.setLayoutParams(relativeLayout$LayoutParams5);
        textView1.setTextColor(-1);
        textView1.setTextSize(2, 14.0f);
        textView1.setShadowLayer(((float)Qf.PjT(context0, 4.0f)), ((float)Qf.PjT(context0, 3.0f)), ((float)Qf.PjT(context0, 3.0f)), Color.parseColor("#99000000"));
        textView1.setGravity(1);
        ((ViewGroup)view0).addView(imageView0);
        ((ViewGroup)view0).addView(imageView1);
        ((ViewGroup)view0).addView(imageView2);
        ((ViewGroup)view0).addView(imageView3);
        ((ViewGroup)view0).addView(textView0);
        ((ViewGroup)view0).addView(textView1);
        return view0;
    }

    public static View PjT(Context context0) {
        View view0 = new LinearLayout(context0);
        view0.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
        ((LinearLayout)view0).setGravity(81);
        LinearLayout linearLayout0 = new LinearLayout(context0);
        linearLayout0.setLayoutParams(new LinearLayout.LayoutParams(Qf.PjT(context0, 46.0f), Qf.PjT(context0, 32.0f)));
        linearLayout0.setBackground(Au.PjT(0, Color.parseColor("#99000000"), new int[]{Qf.PjT(context0, 40.0f)}, null, Qf.PjT(context0, 1.0f), Color.parseColor("#88FFFFFF")));
        linearLayout0.setGravity(17);
        linearLayout0.setOrientation(1);
        ImageView imageView0 = new ImageView(context0);
        imageView0.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        imageView0.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_10"));
        linearLayout0.addView(imageView0);
        ((ViewGroup)view0).addView(linearLayout0);
        return view0;
    }

    public static View ReZ(Context context0) {
        View view0 = new LinearLayout(context0);
        view0.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        view0.setBackground(Lrd.ReZ(context0, "tt_splash_unlock_btn_bg"));
        view0.setPadding(Qf.PjT(context0, 38.0f), Qf.PjT(context0, 20.0f), Qf.PjT(context0, 38.0f), Qf.PjT(context0, 20.0f));
        ((LinearLayout)view0).setGravity(17);
        ((LinearLayout)view0).setOrientation(0);
        ImageView imageView0 = new ImageView(context0);
        imageView0.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        imageView0.setBackground(Lrd.ReZ(context0, "tt_splash_shake_hand"));
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFFB);
        LinearLayout.LayoutParams linearLayout$LayoutParams0 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams0.setMargins(Qf.PjT(context0, 8.0f), 0, 0, 0);
        textView0.setLayoutParams(linearLayout$LayoutParams0);
        textView0.setTextSize(2, 17.0f);
        textView0.setTextColor(-1);
        ((ViewGroup)view0).addView(imageView0);
        ((ViewGroup)view0).addView(textView0);
        return view0;
    }

    public static View SM(Context context0) {
        View view0 = new LinearLayout(context0);
        view0.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        ((LinearLayout)view0).setOrientation(1);
        LinearLayout linearLayout0 = new LinearLayout(context0);
        linearLayout0.setId(0x7D06FFE2);
        LinearLayout.LayoutParams linearLayout$LayoutParams0 = new LinearLayout.LayoutParams(Qf.PjT(context0, 110.0f), Qf.PjT(context0, 110.0f));
        linearLayout$LayoutParams0.gravity = 17;
        linearLayout$LayoutParams0.setMargins(0, 0, 0, Qf.PjT(context0, 4.0f));
        linearLayout0.setLayoutParams(linearLayout$LayoutParams0);
        linearLayout0.setGravity(17);
        linearLayout0.setOrientation(1);
        linearLayout0.setVisibility(0);
        ((ViewGroup)view0).addView(linearLayout0);
        cz cz0 = new cz(context0);
        cz0.setId(0x7D06FFD2);
        cz0.setLayoutParams(new LinearLayout.LayoutParams(Qf.PjT(context0, 100.0f), Qf.PjT(context0, 100.0f)));
        linearLayout0.addView(cz0);
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFDF);
        LinearLayout.LayoutParams linearLayout$LayoutParams1 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams1.gravity = 17;
        textView0.setLayoutParams(linearLayout$LayoutParams1);
        textView0.setSingleLine(true);
        textView0.setText(context0.getString(Lrd.Zh(context0, "tt_splash_wriggle_top_text")));
        textView0.setTextColor(-1);
        textView0.setTextSize(1, 18.0f);
        textView0.setTypeface(null, 1);
        textView0.setShadowLayer(2.0f, 0.0f, 0.5f, Color.parseColor("#4D000000"));
        ((ViewGroup)view0).addView(textView0);
        TextView textView1 = new TextView(context0);
        textView1.setId(0x7D06FFDE);
        LinearLayout.LayoutParams linearLayout$LayoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams2.gravity = 17;
        textView1.setLayoutParams(linearLayout$LayoutParams2);
        textView1.setSingleLine(true);
        textView1.setText(context0.getString(Lrd.Zh(context0, "tt_splash_wriggle_text")));
        textView1.setTextColor(-1);
        textView1.setTextSize(1, 14.0f);
        textView1.setTypeface(null, 1);
        textView1.setShadowLayer(2.0f, 0.0f, 0.5f, Color.parseColor("#4D000000"));
        ((ViewGroup)view0).addView(textView1);
        return view0;
    }

    public static View XX(Context context0) {
        View view0 = new LinearLayout(context0);
        view0.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        ((LinearLayout)view0).setOrientation(1);
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFE8);
        LinearLayout.LayoutParams linearLayout$LayoutParams0 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams0.gravity = 17;
        linearLayout$LayoutParams0.setMargins(0, Qf.PjT(context0, 12.0f), 0, 0);
        textView0.setLayoutParams(linearLayout$LayoutParams0);
        textView0.setVisibility(4);
        ((ViewGroup)view0).addView(textView0);
        LinearLayout linearLayout0 = new LinearLayout(context0);
        linearLayout0.setId(0x7D06FFE7);
        LinearLayout.LayoutParams linearLayout$LayoutParams1 = new LinearLayout.LayoutParams(Qf.PjT(context0, 110.0f), Qf.PjT(context0, 110.0f));
        linearLayout$LayoutParams1.gravity = 17;
        linearLayout0.setLayoutParams(linearLayout$LayoutParams1);
        linearLayout0.setGravity(17);
        linearLayout0.setOrientation(1);
        ((ViewGroup)view0).addView(linearLayout0);
        TextView textView1 = new TextView(context0);
        textView1.setId(0x7D06FFE6);
        textView1.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        textView1.setVisibility(4);
        textView1.setTextSize(2, 14.0f);
        linearLayout0.addView(textView1);
        ImageView imageView0 = new ImageView(context0);
        imageView0.setId(0x7D06FFE5);
        imageView0.setLayoutParams(new LinearLayout.LayoutParams(Qf.PjT(context0, 60.0f), Qf.PjT(context0, 60.0f)));
        imageView0.setImageDrawable(Lrd.ReZ(context0, "tt_splash_rock"));
        linearLayout0.addView(imageView0);
        TextView textView2 = new TextView(context0);
        textView2.setId(0x7D06FFE4);
        textView2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        textView2.setSingleLine(true);
        textView2.setText("Shake it");
        textView2.setTextColor(-1);
        textView2.setTextSize(2, 14.0f);
        linearLayout0.addView(textView2);
        TextView textView3 = new TextView(context0);
        textView3.setId(0x7D06FFE3);
        LinearLayout.LayoutParams linearLayout$LayoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams2.gravity = 17;
        linearLayout$LayoutParams2.setMargins(0, Qf.PjT(context0, 12.0f), 0, 0);
        textView3.setLayoutParams(linearLayout$LayoutParams2);
        textView3.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView3.setText("Go to details page or third-party application");
        textView3.setTextColor(-1);
        ((ViewGroup)view0).addView(textView3);
        return view0;
    }

    public static View Zh(Context context0) {
        View view0 = new LinearLayout(context0);
        view0.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
        ((LinearLayout)view0).setGravity(81);
        LinearLayout linearLayout0 = new LinearLayout(context0);
        linearLayout0.setLayoutParams(new LinearLayout.LayoutParams(-1, Qf.PjT(context0, 100.0f)));
        linearLayout0.setGravity(17);
        linearLayout0.setOrientation(1);
        FrameLayout frameLayout0 = new FrameLayout(context0);
        frameLayout0.setLayoutParams(new LinearLayout.LayoutParams(-1, -2));
        ImageView imageView0 = new ImageView(context0);
        imageView0.setId(0x7D06FFFF);
        FrameLayout.LayoutParams frameLayout$LayoutParams0 = new FrameLayout.LayoutParams(Qf.PjT(context0, 19.0f), Qf.PjT(context0, 15.0f));
        frameLayout$LayoutParams0.gravity = 1;
        imageView0.setLayoutParams(frameLayout$LayoutParams0);
        ImageView.ScaleType imageView$ScaleType0 = ImageView.ScaleType.FIT_XY;
        imageView0.setScaleType(imageView$ScaleType0);
        imageView0.setImageDrawable(Lrd.ReZ(context0, "tt_white_slide_up"));
        ImageView imageView1 = new ImageView(context0);
        imageView1.setId(0x7D06FFFE);
        FrameLayout.LayoutParams frameLayout$LayoutParams1 = new FrameLayout.LayoutParams(Qf.PjT(context0, 19.0f), Qf.PjT(context0, 15.0f));
        frameLayout$LayoutParams1.gravity = 1;
        frameLayout$LayoutParams1.topMargin = Qf.PjT(context0, 7.0f);
        imageView1.setLayoutParams(frameLayout$LayoutParams1);
        imageView1.setScaleType(imageView$ScaleType0);
        imageView1.setImageDrawable(Lrd.ReZ(context0, "tt_white_slide_up"));
        ImageView imageView2 = new ImageView(context0);
        imageView2.setId(0x7D06FFFD);
        FrameLayout.LayoutParams frameLayout$LayoutParams2 = new FrameLayout.LayoutParams(Qf.PjT(context0, 19.0f), Qf.PjT(context0, 15.0f));
        frameLayout$LayoutParams2.gravity = 1;
        frameLayout$LayoutParams2.topMargin = Qf.PjT(context0, 14.0f);
        imageView2.setLayoutParams(frameLayout$LayoutParams2);
        imageView2.setScaleType(imageView$ScaleType0);
        imageView2.setImageDrawable(Lrd.ReZ(context0, "tt_white_slide_up"));
        frameLayout0.addView(imageView0);
        frameLayout0.addView(imageView1);
        frameLayout0.addView(imageView2);
        linearLayout0.addView(frameLayout0);
        View view1 = new View(context0);
        view1.setLayoutParams(new LinearLayout.LayoutParams(-1, 0, 1.0f));
        linearLayout0.addView(view1);
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFFC);
        LinearLayout.LayoutParams linearLayout$LayoutParams0 = new LinearLayout.LayoutParams(-1, -2);
        linearLayout$LayoutParams0.setMargins(0, 0, 0, Qf.PjT(context0, 5.0f));
        textView0.setLayoutParams(linearLayout$LayoutParams0);
        textView0.setGravity(1);
        textView0.setTextColor(-1);
        textView0.setTextSize(1, 14.0f);
        linearLayout0.addView(textView0);
        ((ViewGroup)view0).addView(linearLayout0);
        return view0;
    }

    public static View cr(Context context0) {
        View view0 = new RelativeLayout(context0);
        view0.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        RelativeLayout relativeLayout0 = new RelativeLayout(context0);
        relativeLayout0.setId(0x7D06FFFA);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams0 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 247.0f), Qf.PjT(context0, 56.0f));
        relativeLayout$LayoutParams0.addRule(14);
        relativeLayout0.setLayoutParams(relativeLayout$LayoutParams0);
        relativeLayout0.setBackground(Lrd.ReZ(context0, "tt_splash_unlock_btn_bg"));
        ImageView imageView0 = new ImageView(context0);
        imageView0.setId(0x7D06FFF9);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams1 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 48.0f), Qf.PjT(context0, 48.0f));
        relativeLayout$LayoutParams1.addRule(20);
        relativeLayout$LayoutParams1.addRule(15);
        relativeLayout$LayoutParams1.setMargins(Qf.PjT(context0, 4.0f), 0, 0, 0);
        imageView0.setLayoutParams(relativeLayout$LayoutParams1);
        imageView0.setImageDrawable(Lrd.ReZ(context0, "tt_splash_unlock_image_go"));
        xf xf0 = new xf(context0);
        xf0.setId(0x7D06FFF8);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams2 = new RelativeLayout.LayoutParams(-1, Qf.PjT(context0, 24.0f));
        relativeLayout$LayoutParams2.addRule(15);
        relativeLayout$LayoutParams2.setMargins(Qf.PjT(context0, 12.0f), 0, Qf.PjT(context0, 12.0f), 0);
        relativeLayout$LayoutParams2.addRule(16, 0x7D06FFF7);
        relativeLayout$LayoutParams2.addRule(17, 0x7D06FFF9);
        xf0.setLayoutParams(relativeLayout$LayoutParams2);
        ImageView imageView1 = new ImageView(context0);
        imageView1.setId(0x7D06FFF7);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams3 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 48.0f), Qf.PjT(context0, 48.0f));
        relativeLayout$LayoutParams3.addRule(21);
        relativeLayout$LayoutParams3.addRule(15);
        relativeLayout$LayoutParams3.setMarginStart(Qf.PjT(context0, 2.0f));
        relativeLayout$LayoutParams3.setMarginEnd(Qf.PjT(context0, 4.0f));
        imageView1.setLayoutParams(relativeLayout$LayoutParams3);
        imageView1.setImageDrawable(Lrd.ReZ(context0, "tt_splash_unlock_icon_empty"));
        relativeLayout0.addView(imageView0);
        relativeLayout0.addView(xf0);
        relativeLayout0.addView(imageView1);
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFF6);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams4 = new RelativeLayout.LayoutParams(-2, -2);
        relativeLayout$LayoutParams4.addRule(3, 0x7D06FFFA);
        relativeLayout$LayoutParams4.addRule(14);
        relativeLayout$LayoutParams4.setMargins(0, Qf.PjT(context0, 12.0f), 0, 0);
        textView0.setLayoutParams(relativeLayout$LayoutParams4);
        textView0.setTextColor(-1);
        textView0.setShadowLayer(((float)Qf.PjT(context0, 3.0f)), ((float)Qf.PjT(context0, 3.0f)), ((float)Qf.PjT(context0, 3.0f)), Color.parseColor("#99000000"));
        ((ViewGroup)view0).addView(relativeLayout0);
        ((ViewGroup)view0).addView(textView0);
        return view0;
    }

    public static View cz(Context context0) {
        View view0 = new RelativeLayout(context0);
        view0.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        ((ViewGroup)view0).setClipChildren(false);
        ((ViewGroup)view0).setClipToPadding(false);
        ((RelativeLayout)view0).setGravity(16);
        RelativeLayout relativeLayout0 = new RelativeLayout(context0);
        relativeLayout0.setId(0x7D06FFE9);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams0 = new RelativeLayout.LayoutParams(-2, -1);
        relativeLayout$LayoutParams0.addRule(13);
        relativeLayout$LayoutParams0.setMargins(0, 0, 0, 0);
        relativeLayout0.setLayoutParams(relativeLayout$LayoutParams0);
        relativeLayout0.setClipChildren(false);
        relativeLayout0.setClipToPadding(false);
        relativeLayout0.setPadding(Qf.PjT(context0, 60.0f), 0, 0, 0);
        ((ViewGroup)view0).addView(relativeLayout0);
        ImageView imageView0 = new ImageView(context0);
        imageView0.setId(0x7D06FFEF);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams1 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 80.0f), Qf.PjT(context0, 80.0f));
        relativeLayout$LayoutParams1.addRule(9);
        relativeLayout$LayoutParams1.addRule(12);
        relativeLayout$LayoutParams1.setMargins(0, 0, 0, -Qf.PjT(context0, 40.0f));
        imageView0.setLayoutParams(relativeLayout$LayoutParams1);
        imageView0.setAlpha(0);
        imageView0.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_circle"));
        relativeLayout0.addView(imageView0);
        ImageView imageView1 = new ImageView(context0);
        imageView1.setId(0x7D06FFED);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams2 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 16.0f), 0);
        relativeLayout$LayoutParams2.addRule(9);
        relativeLayout$LayoutParams2.addRule(12);
        relativeLayout$LayoutParams2.setMargins(Qf.PjT(context0, 36.0f), 0, 0, 0);
        imageView1.setLayoutParams(relativeLayout$LayoutParams2);
        imageView1.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_bg"));
        relativeLayout0.addView(imageView1);
        ImageView imageView2 = new ImageView(context0);
        imageView2.setId(0x7D06FFEE);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams3 = new RelativeLayout.LayoutParams(Qf.PjT(context0, 160.0f), Qf.PjT(context0, 120.0f));
        relativeLayout$LayoutParams3.addRule(12);
        relativeLayout$LayoutParams3.setMargins(Qf.PjT(context0, 35.0f), 0, 0, -Qf.PjT(context0, 40.0f));
        imageView2.setLayoutParams(relativeLayout$LayoutParams3);
        imageView2.setAlpha(0);
        imageView2.setBackground(Lrd.ReZ(context0, "tt_splash_slide_up_finger"));
        relativeLayout0.addView(imageView2);
        TextView textView0 = new TextView(context0);
        textView0.setId(0x7D06FFEA);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams4 = new RelativeLayout.LayoutParams(-1, Qf.PjT(context0, 20.0f));
        relativeLayout$LayoutParams4.addRule(12);
        relativeLayout$LayoutParams4.setMargins(0, 0, 0, -Qf.PjT(context0, 95.0f));
        textView0.setLayoutParams(relativeLayout$LayoutParams4);
        textView0.setGravity(1);
        textView0.setShadowLayer(4.0f, 3.0f, 3.0f, Color.parseColor("#99000000"));
        textView0.setTextColor(-1);
        textView0.setTextSize(1, 14.0f);
        ((ViewGroup)view0).addView(textView0);
        return view0;
    }
}

