package K3;

import android.os.Parcel;
import kotlin.K;
import y4.l;

public interface b {
    public static final class a {
        @l
        public static Object[] a(@l b b0, int v) {
            throw new K("Generated by Android Extensions automatically");
        }
    }

    Object a(@l Parcel arg1);

    void b(Object arg1, @l Parcel arg2, int arg3);

    @l
    Object[] newArray(int arg1);
}

