package com.bytedance.sdk.openadsdk.component.reward.view;

import android.content.Context;
import android.graphics.Color;
import android.widget.FrameLayout.LayoutParams;
import android.widget.FrameLayout;
import android.widget.LinearLayout.LayoutParams;
import android.widget.RelativeLayout.LayoutParams;
import com.bytedance.sdk.component.SM.cz;
import com.bytedance.sdk.component.utils.Lrd;
import com.bytedance.sdk.openadsdk.common.xf;
import com.bytedance.sdk.openadsdk.core.JQp.Au;
import com.bytedance.sdk.openadsdk.core.JQp.JQp;
import com.bytedance.sdk.openadsdk.core.JQp.XX;
import com.bytedance.sdk.openadsdk.core.model.Owx;
import com.bytedance.sdk.openadsdk.core.widget.PAGLogoView;
import com.bytedance.sdk.openadsdk.core.widget.xE;
import com.bytedance.sdk.openadsdk.utils.DWo;
import com.bytedance.sdk.openadsdk.utils.qZS;
import com.bytedance.sdk.openadsdk.utils.qla;

public class cr {
    public static void PjT(FrameLayout frameLayout0) {
        Context context0 = frameLayout0.getContext();
        ReZ reZ0 = new ReZ(context0);
        reZ0.setId(qla.xf);
        reZ0.setVisibility(8);
        FrameLayout.LayoutParams frameLayout$LayoutParams0 = new FrameLayout.LayoutParams(-1, -2);
        frameLayout$LayoutParams0.gravity = 80;
        frameLayout0.addView(reZ0, frameLayout$LayoutParams0);
        JQp jQp0 = new JQp(context0);
        jQp0.setId(qla.xs);
        jQp0.setVisibility(8);
        frameLayout0.addView(jQp0, new FrameLayout.LayoutParams(-1, -1));
        cz cz0 = new cz(context0, true);
        cz0.setLayerType(2, null);
        cz0.setVisibility(4);
        cz0.setId(qla.fDm);
        frameLayout0.addView(cz0, new FrameLayout.LayoutParams(-1, -1));
        FrameLayout frameLayout1 = new FrameLayout(context0);
        frameLayout1.setId(qla.qla);
        frameLayout1.setVisibility(4);
        frameLayout0.addView(frameLayout1, new FrameLayout.LayoutParams(-1, -1));
        cz cz1 = new cz(context0, true);
        cz1.setVisibility(8);
        cz1.setId(qla.xE);
        frameLayout0.addView(cz1, new FrameLayout.LayoutParams(-1, -1));
        frameLayout0.addView(new RFEndCardBackUpLayout(context0), new FrameLayout.LayoutParams(-1, -1));
    }

    public static void PjT(FrameLayout frameLayout0, Owx owx0) {
        Context context0 = frameLayout0.getContext();
        XX xX0 = new XX(context0);
        xX0.setId(qla.Lrd);
        xX0.setBackgroundColor(Color.parseColor("#F8F8F8"));
        frameLayout0.addView(xX0, new FrameLayout.LayoutParams(-1, -1));
        xf xf0 = new xf(context0);
        xf0.setId(qla.cRA);
        xX0.addView(xf0, new RelativeLayout.LayoutParams(-1, -1));
        JQp jQp0 = new JQp(context0);
        jQp0.setId(qla.yIW);
        jQp0.setOrientation(1);
        jQp0.setVisibility(8);
        jQp0.setGravity(1);
        jQp0.setId(qla.qZS);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams0 = new RelativeLayout.LayoutParams(-1, -2);
        relativeLayout$LayoutParams0.addRule(13);
        xX0.addView(jQp0, relativeLayout$LayoutParams0);
        xE xE0 = new xE(context0);
        xE0.setId(qla.Yo);
        jQp0.addView(xE0, new LinearLayout.LayoutParams(qZS.Zh(context0, 80.0f), qZS.Zh(context0, 80.0f)));
        Au au0 = new Au(context0);
        au0.setId(qla.KM);
        au0.setTextColor(Color.parseColor("#161823"));
        au0.setTextSize(2, 24.0f);
        LinearLayout.LayoutParams linearLayout$LayoutParams0 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams0.topMargin = qZS.Zh(context0, 12.0f);
        jQp0.addView(au0, linearLayout$LayoutParams0);
        Au au1 = new Au(context0);
        au1.setId(qla.Qf);
        au1.setGravity(17);
        au1.setTextColor(Color.parseColor("#80161823"));
        au1.setTextSize(2, 16.0f);
        au1.setTextAlignment(4);
        LinearLayout.LayoutParams linearLayout$LayoutParams1 = new LinearLayout.LayoutParams(-2, -2);
        int v = qZS.Zh(context0, 60.0f);
        linearLayout$LayoutParams1.leftMargin = v;
        linearLayout$LayoutParams1.rightMargin = v;
        linearLayout$LayoutParams1.setMarginStart(v);
        linearLayout$LayoutParams1.setMarginEnd(linearLayout$LayoutParams1.rightMargin);
        linearLayout$LayoutParams1.topMargin = qZS.Zh(context0, 8.0f);
        jQp0.addView(au1, linearLayout$LayoutParams1);
        Au au2 = new Au(context0);
        au2.setId(qla.ZX);
        au2.setGravity(17);
        au2.setTextColor(-1);
        au2.setText(Lrd.PjT(context0, "tt_video_mobile_go_detail"));
        au2.setBackground(DWo.PjT(context0, "tt_reward_video_download_btn_bg"));
        LinearLayout.LayoutParams linearLayout$LayoutParams2 = new LinearLayout.LayoutParams(qZS.Zh(context0, 255.0f), qZS.Zh(context0, 44.0f));
        linearLayout$LayoutParams2.topMargin = qZS.Zh(context0, 32.0f);
        jQp0.addView(au2, linearLayout$LayoutParams2);
        Au au3 = new Au(context0);
        au3.setId(qla.iZZ);
        au3.setGravity(17);
        au3.setTextColor(0xFF000000);
        au3.setText("Sorry,this AD fails to load...");
        au3.setVisibility(8);
        au3.setGravity(1);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams1 = new RelativeLayout.LayoutParams(-1, -2);
        relativeLayout$LayoutParams1.addRule(13);
        xX0.addView(au3, relativeLayout$LayoutParams1);
        PAGLogoView pAGLogoView0 = PAGLogoView.createPAGLogoViewByMaterial(context0, owx0);
        pAGLogoView0.setId(qla.Jo);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams2 = new RelativeLayout.LayoutParams(-2, qZS.Zh(context0, 14.0f));
        relativeLayout$LayoutParams2.addRule(12);
        int v1 = qZS.Zh(context0, 16.0f);
        relativeLayout$LayoutParams2.leftMargin = v1;
        relativeLayout$LayoutParams2.setMarginStart(v1);
        relativeLayout$LayoutParams2.bottomMargin = qZS.Zh(context0, 20.0f);
        xX0.addView(pAGLogoView0, relativeLayout$LayoutParams2);
    }
}

