package net.fellbaum.jemoji;

import java.util.Collections;
import java.util.List;

interface g {
    public static final f A;
    public static final f B;
    public static final f C;
    public static final f D;
    public static final f E;
    public static final f F;
    public static final f G;
    public static final f H;
    public static final f I;
    public static final f J;
    public static final f K;
    public static final f L;
    public static final f M;
    public static final f N;
    public static final f O;
    public static final f P;
    public static final f Q;
    public static final f R;
    public static final f S;
    public static final f T;
    public static final f U;
    public static final f V;
    public static final f W;
    public static final f a;
    public static final f b;
    public static final f c;
    public static final f d;
    public static final f e;
    public static final f f;
    public static final f g;
    public static final f h;
    public static final f i;
    public static final f j;
    public static final f k;
    public static final f l;
    public static final f m;
    public static final f n;
    public static final f o;
    public static final f p;
    public static final f q;
    public static final f r;
    public static final f s;
    public static final f t;
    public static final f u;
    public static final f v;
    public static final f w;
    public static final f x;
    public static final f y;
    public static final f z;

    static {
        g.a = new f("\uD83D\uDD20", "\uD83D\uDD20", Collections.singletonList(":capital_abcd:"), Collections.singletonList(":capital_abcd:"), Collections.singletonList(":capital_abcd:"), false, false, 0.6, M1.a("fully-qualified"), "input latin uppercase", d0.j, q1.c);
        List list0 = Collections.singletonList(":abcd:");
        List list1 = Collections.singletonList(":abcd:");
        List list2 = Collections.singletonList(":abcd:");
        M1 m10 = M1.a("fully-qualified");
        d0 d00 = d0.j;
        q1 q10 = q1.c;
        g.b = new f("\uD83D\uDD21", "\uD83D\uDD21", list0, list1, list2, false, false, 0.6, m10, "input latin lowercase", d00, q10);
        g.c = new f("\uD83D\uDD22", "\uD83D\uDD22", Collections.singletonList(":1234:"), Collections.singletonList(":1234:"), Collections.singletonList(":1234:"), false, false, 0.6, M1.a("fully-qualified"), "input numbers", d00, q10);
        g.d = new f("\uD83D\uDD23", "\uD83D\uDD23", Collections.singletonList(":symbols:"), Collections.singletonList(":symbols:"), Collections.singletonList(":symbols:"), false, false, 0.6, M1.a("fully-qualified"), "input symbols", d00, q10);
        g.e = new f("\uD83D\uDD24", "\uD83D\uDD24", Collections.singletonList(":abc:"), Collections.singletonList(":abc:"), Collections.singletonList(":abc:"), false, false, 0.6, M1.a("fully-qualified"), "input latin letters", d00, q10);
        g.f = new f("\uD83C\uDD70️", "\uD83C\uDD70️", Collections.singletonList(":a:"), Collections.singletonList(":a:"), Collections.singletonList(":a:"), false, false, 0.6, M1.a("fully-qualified"), "A button (blood type)", d00, q10);
        g.g = new f("\uD83C\uDD70", "\uD83C\uDD70", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":a:"), false, false, 0.6, M1.a("unqualified"), "A button (blood type)", d00, q10);
        g.h = new f("\uD83C\uDD8E", "\uD83C\uDD8E", Collections.singletonList(":ab:"), Collections.singletonList(":ab:"), Collections.singletonList(":ab:"), false, false, 0.6, M1.a("fully-qualified"), "AB button (blood type)", d00, q10);
        g.i = new f("\uD83C\uDD71️", "\uD83C\uDD71️", Collections.singletonList(":b:"), Collections.singletonList(":b:"), Collections.singletonList(":b:"), false, false, 0.6, M1.a("fully-qualified"), "B button (blood type)", d00, q10);
        g.j = new f("\uD83C\uDD71", "\uD83C\uDD71", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":b:"), false, false, 0.6, M1.a("unqualified"), "B button (blood type)", d00, q10);
        g.k = new f("\uD83C\uDD91", "\uD83C\uDD91", Collections.singletonList(":cl:"), Collections.singletonList(":cl:"), Collections.singletonList(":cl:"), false, false, 0.6, M1.a("fully-qualified"), "CL button", d00, q10);
        g.l = new f("\uD83C\uDD92", "\uD83C\uDD92", Collections.singletonList(":cool:"), Collections.singletonList(":cool:"), Collections.singletonList(":cool:"), false, false, 0.6, M1.a("fully-qualified"), "COOL button", d00, q10);
        g.m = new f("\uD83C\uDD93", "\uD83C\uDD93", Collections.singletonList(":free:"), Collections.singletonList(":free:"), Collections.singletonList(":free:"), false, false, 0.6, M1.a("fully-qualified"), "FREE button", d00, q10);
        g.n = new f("ℹ️", "ℹ️", Collections.singletonList(":information_source:"), Collections.singletonList(":information_source:"), Collections.singletonList(":information_source:"), false, false, 0.6, M1.a("fully-qualified"), "information", d00, q10);
        g.o = new f("ℹ", "ℹ", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":information_source:"), false, false, 0.6, M1.a("unqualified"), "information", d00, q10);
        g.p = new f("\uD83C\uDD94", "\uD83C\uDD94", Collections.singletonList(":id:"), Collections.singletonList(":id:"), Collections.singletonList(":id:"), false, false, 0.6, M1.a("fully-qualified"), "ID button", d00, q10);
        g.q = new f("Ⓜ️", "Ⓜ️", Collections.singletonList(":m:"), Collections.singletonList(":m:"), Collections.singletonList(":m:"), false, false, 0.6, M1.a("fully-qualified"), "circled M", d00, q10);
        g.r = new f("Ⓜ", "Ⓜ", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":m:"), false, false, 0.6, M1.a("unqualified"), "circled M", d00, q10);
        g.s = new f("\uD83C\uDD95", "\uD83C\uDD95", Collections.singletonList(":new:"), Collections.singletonList(":new:"), Collections.singletonList(":new:"), false, false, 0.6, M1.a("fully-qualified"), "NEW button", d00, q10);
        g.t = new f("\uD83C\uDD96", "\uD83C\uDD96", Collections.singletonList(":ng:"), Collections.singletonList(":ng:"), Collections.singletonList(":ng:"), false, false, 0.6, M1.a("fully-qualified"), "NG button", d00, q10);
        g.u = new f("\uD83C\uDD7E️", "\uD83C\uDD7E️", Collections.singletonList(":o2:"), Collections.singletonList(":o2:"), Collections.singletonList(":o2:"), false, false, 0.6, M1.a("fully-qualified"), "O button (blood type)", d00, q10);
        g.v = new f("\uD83C\uDD7E", "\uD83C\uDD7E", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":o2:"), false, false, 0.6, M1.a("unqualified"), "O button (blood type)", d00, q10);
        g.w = new f("\uD83C\uDD97", "\uD83C\uDD97", Collections.singletonList(":ok:"), Collections.singletonList(":ok:"), Collections.singletonList(":ok:"), false, false, 0.6, M1.a("fully-qualified"), "OK button", d00, q10);
        g.x = new f("\uD83C\uDD7F️", "\uD83C\uDD7F️", Collections.singletonList(":parking:"), Collections.singletonList(":parking:"), Collections.singletonList(":parking:"), false, false, 0.6, M1.a("fully-qualified"), "P button", d00, q10);
        g.y = new f("\uD83C\uDD7F", "\uD83C\uDD7F", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":parking:"), false, false, 0.6, M1.a("unqualified"), "P button", d00, q10);
        g.z = new f("\uD83C\uDD98", "\uD83C\uDD98", Collections.singletonList(":sos:"), Collections.singletonList(":sos:"), Collections.singletonList(":sos:"), false, false, 0.6, M1.a("fully-qualified"), "SOS button", d00, q10);
        g.A = new f("\uD83C\uDD99", "\uD83C\uDD99", Collections.singletonList(":up:"), Collections.singletonList(":up:"), Collections.singletonList(":up:"), false, false, 0.6, M1.a("fully-qualified"), "UP! button", d00, q10);
        g.B = new f("\uD83C\uDD9A", "\uD83C\uDD9A", Collections.singletonList(":vs:"), Collections.singletonList(":vs:"), Collections.singletonList(":vs:"), false, false, 0.6, M1.a("fully-qualified"), "VS button", d00, q10);
        g.C = new f("\uD83C\uDE01", "\uD83C\uDE01", Collections.singletonList(":koko:"), Collections.singletonList(":koko:"), Collections.singletonList(":koko:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “here” button", d00, q10);
        g.D = new f("\uD83C\uDE02️", "\uD83C\uDE02️", Collections.singletonList(":sa:"), Collections.singletonList(":sa:"), Collections.singletonList(":sa:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “service charge” button", d00, q10);
        g.E = new f("\uD83C\uDE02", "\uD83C\uDE02", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":sa:"), false, false, 0.6, M1.a("unqualified"), "Japanese “service charge” button", d00, q10);
        g.F = new f("\uD83C\uDE37️", "\uD83C\uDE37️", Collections.singletonList(":u6708:"), Collections.singletonList(":u6708:"), Collections.singletonList(":u6708:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “monthly amount” button", d00, q10);
        g.G = new f("\uD83C\uDE37", "\uD83C\uDE37", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":u6708:"), false, false, 0.6, M1.a("unqualified"), "Japanese “monthly amount” button", d00, q10);
        g.H = new f("\uD83C\uDE36", "\uD83C\uDE36", Collections.singletonList(":u6709:"), Collections.singletonList(":u6709:"), Collections.singletonList(":u6709:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “not free of charge” button", d00, q10);
        g.I = new f("\uD83C\uDE2F", "\uD83C\uDE2F", Collections.singletonList(":u6307:"), Collections.singletonList(":u6307:"), Collections.singletonList(":u6307:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “reserved” button", d00, q10);
        g.J = new f("\uD83C\uDE50", "\uD83C\uDE50", Collections.singletonList(":ideograph_advantage:"), Collections.singletonList(":ideograph_advantage:"), Collections.singletonList(":ideograph_advantage:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “bargain” button", d00, q10);
        g.K = new f("\uD83C\uDE39", "\uD83C\uDE39", Collections.singletonList(":u5272:"), Collections.singletonList(":u5272:"), Collections.singletonList(":u5272:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “discount” button", d00, q10);
        g.L = new f("\uD83C\uDE1A", "\uD83C\uDE1A", Collections.singletonList(":u7121:"), Collections.singletonList(":u7121:"), Collections.singletonList(":u7121:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “free of charge” button", d00, q10);
        g.M = new f("\uD83C\uDE32", "\uD83C\uDE32", Collections.singletonList(":u7981:"), Collections.singletonList(":u7981:"), Collections.singletonList(":u7981:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “prohibited” button", d00, q10);
        g.N = new f("\uD83C\uDE51", "\uD83C\uDE51", Collections.singletonList(":accept:"), Collections.singletonList(":accept:"), Collections.singletonList(":accept:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “acceptable” button", d00, q10);
        g.O = new f("\uD83C\uDE38", "\uD83C\uDE38", Collections.singletonList(":u7533:"), Collections.singletonList(":u7533:"), Collections.singletonList(":u7533:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “application” button", d00, q10);
        g.P = new f("\uD83C\uDE34", "\uD83C\uDE34", Collections.singletonList(":u5408:"), Collections.singletonList(":u5408:"), Collections.singletonList(":u5408:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “passing grade” button", d00, q10);
        g.Q = new f("\uD83C\uDE33", "\uD83C\uDE33", Collections.singletonList(":u7a7a:"), Collections.singletonList(":u7a7a:"), Collections.singletonList(":u7a7a:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “vacancy” button", d00, q10);
        g.R = new f("㊗️", "㊗️", Collections.singletonList(":congratulations:"), Collections.singletonList(":congratulations:"), Collections.singletonList(":congratulations:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “congratulations” button", d00, q10);
        g.S = new f("㊗", "㊗", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":congratulations:"), false, false, 0.6, M1.a("unqualified"), "Japanese “congratulations” button", d00, q10);
        g.T = new f("㊙️", "㊙️", Collections.singletonList(":secret:"), Collections.singletonList(":secret:"), Collections.singletonList(":secret:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “secret” button", d00, q10);
        g.U = new f("㊙", "㊙", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":secret:"), false, false, 0.6, M1.a("unqualified"), "Japanese “secret” button", d00, q10);
        g.V = new f("\uD83C\uDE3A", "\uD83C\uDE3A", Collections.singletonList(":u55b6:"), Collections.singletonList(":u55b6:"), Collections.singletonList(":u55b6:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “open for business” button", d00, q10);
        g.W = new f("\uD83C\uDE35", "\uD83C\uDE35", Collections.singletonList(":u6e80:"), Collections.singletonList(":u6e80:"), Collections.singletonList(":u6e80:"), false, false, 0.6, M1.a("fully-qualified"), "Japanese “no vacancy” button", d00, q10);
    }
}

