package net.fellbaum.jemoji;

import j..util.DesugarCollections;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

interface k {
    public static final f A1;
    public static final f B1;
    public static final f C1;
    public static final f D1;
    public static final f E1;
    public static final f F1;
    public static final f G1;
    public static final f H1;
    public static final f I1;
    public static final f J1;
    public static final f K1;
    public static final f L1;
    public static final f M1;
    public static final f N0;
    public static final f N1;
    public static final f O0;
    public static final f O1;
    public static final f P0;
    public static final f P1;
    public static final f Q0;
    public static final f Q1;
    public static final f R0;
    public static final f R1;
    public static final f S0;
    public static final f S1;
    public static final f T0;
    public static final f T1;
    public static final f U0;
    public static final f U1;
    public static final f V0;
    public static final f V1;
    public static final f W0;
    public static final f W1;
    public static final f X0;
    public static final f X1;
    public static final f Y0;
    public static final f Y1;
    public static final f Z0;
    public static final f Z1;
    public static final f a1;
    public static final f a2;
    public static final f b1;
    public static final f b2;
    public static final f c1;
    public static final f c2;
    public static final f d1;
    public static final f e1;
    public static final f f1;
    public static final f g1;
    public static final f h1;
    public static final f i1;
    public static final f j1;
    public static final f k1;
    public static final f l1;
    public static final f m1;
    public static final f n1;
    public static final f o1;
    public static final f p1;
    public static final f q1;
    public static final f r1;
    public static final f s1;
    public static final f t1;
    public static final f u1;
    public static final f v1;
    public static final f w1;
    public static final f x1;
    public static final f y1;
    public static final f z1;

    static {
        k.N0 = new f("\uD83D\uDC35", "\uD83D\uDC35", Collections.singletonList(":monkey_face:"), Collections.singletonList(":monkey_face:"), Collections.singletonList(":monkey_face:"), false, false, 0.6, M1.a("fully-qualified"), "monkey face", d0.c, q1.g);
        List list0 = Collections.singletonList(":monkey:");
        List list1 = Collections.singletonList(":monkey:");
        List list2 = Collections.singletonList(":monkey:");
        M1 m10 = M1.a("fully-qualified");
        d0 d00 = d0.c;
        q1 q10 = q1.g;
        k.O0 = new f("\uD83D\uDC12", "\uD83D\uDC12", list0, list1, list2, false, false, 0.6, m10, "monkey", d00, q10);
        k.P0 = new f("\uD83E\uDD8D", "\uD83E\uDD8D", Collections.singletonList(":gorilla:"), Collections.singletonList(":gorilla:"), Collections.singletonList(":gorilla:"), false, false, 3.0, M1.a("fully-qualified"), "gorilla", d00, q10);
        k.Q0 = new f("\uD83E\uDDA7", "\uD83E\uDDA7", Collections.singletonList(":orangutan:"), Collections.singletonList(":orangutan:"), Collections.singletonList(":orangutan:"), false, false, 12.0, M1.a("fully-qualified"), "orangutan", d00, q10);
        k.R0 = new f("\uD83D\uDC36", "\uD83D\uDC36", Collections.singletonList(":dog:"), Collections.singletonList(":dog:"), Collections.singletonList(":dog:"), false, false, 0.6, M1.a("fully-qualified"), "dog face", d00, q10);
        k.S0 = new f("\uD83D\uDC15", "\uD83D\uDC15", Collections.singletonList(":dog2:"), Collections.singletonList(":dog2:"), Collections.singletonList(":dog2:"), false, false, 0.7, M1.a("fully-qualified"), "dog", d00, q10);
        k.T0 = new f("\uD83E\uDDAE", "\uD83E\uDDAE", Collections.singletonList(":guide_dog:"), Collections.singletonList(":guide_dog:"), Collections.singletonList(":guide_dog:"), false, false, 12.0, M1.a("fully-qualified"), "guide dog", d00, q10);
        k.U0 = new f("\uD83D\uDC15‍\uD83E\uDDBA", "\uD83D\uDC15‍\uD83E\uDDBA", Collections.singletonList(":service_dog:"), Collections.singletonList(":service_dog:"), Collections.singletonList(":service_dog:"), false, false, 12.0, M1.a("fully-qualified"), "service dog", d00, q10);
        k.V0 = new f("\uD83D\uDC29", "\uD83D\uDC29", Collections.singletonList(":poodle:"), Collections.singletonList(":poodle:"), Collections.singletonList(":poodle:"), false, false, 0.6, M1.a("fully-qualified"), "poodle", d00, q10);
        k.W0 = new f("\uD83D\uDC3A", "\uD83D\uDC3A", Collections.singletonList(":wolf:"), Collections.singletonList(":wolf:"), Collections.singletonList(":wolf:"), false, false, 0.6, M1.a("fully-qualified"), "wolf", d00, q10);
        k.X0 = new f("\uD83E\uDD8A", "\uD83E\uDD8A", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":fox:", ":fox_face:"})), Collections.singletonList(":fox_face:"), Collections.singletonList(":fox_face:"), false, false, 3.0, M1.a("fully-qualified"), "fox", d00, q10);
        k.Y0 = new f("\uD83E\uDD9D", "\uD83E\uDD9D", Collections.singletonList(":raccoon:"), Collections.singletonList(":raccoon:"), Collections.singletonList(":raccoon:"), false, false, 11.0, M1.a("fully-qualified"), "raccoon", d00, q10);
        k.Z0 = new f("\uD83D\uDC31", "\uD83D\uDC31", Collections.singletonList(":cat:"), Collections.singletonList(":cat:"), Collections.singletonList(":cat:"), false, false, 0.6, M1.a("fully-qualified"), "cat face", d00, q10);
        k.a1 = new f("\uD83D\uDC08", "\uD83D\uDC08", Collections.singletonList(":cat2:"), Collections.singletonList(":cat2:"), Collections.singletonList(":cat2:"), false, false, 0.7, M1.a("fully-qualified"), "cat", d00, q10);
        k.b1 = new f("\uD83D\uDC08‍⬛", "\uD83D\uDC08‍⬛", Collections.singletonList(":black_cat:"), Collections.singletonList(":black_cat:"), Collections.singletonList(":black_cat:"), false, false, 13.0, M1.a("fully-qualified"), "black cat", d00, q10);
        k.c1 = new f("\uD83E\uDD81", "\uD83E\uDD81", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":lion_face:", ":lion:"})), Collections.singletonList(":lion_face:"), Collections.singletonList(":lion:"), false, false, 1.0, M1.a("fully-qualified"), "lion", d00, q10);
        k.d1 = new f("\uD83D\uDC2F", "\uD83D\uDC2F", Collections.singletonList(":tiger:"), Collections.singletonList(":tiger:"), Collections.singletonList(":tiger:"), false, false, 0.6, M1.a("fully-qualified"), "tiger face", d00, q10);
        k.e1 = new f("\uD83D\uDC05", "\uD83D\uDC05", Collections.singletonList(":tiger2:"), Collections.singletonList(":tiger2:"), Collections.singletonList(":tiger2:"), false, false, 1.0, M1.a("fully-qualified"), "tiger", d00, q10);
        k.f1 = new f("\uD83D\uDC06", "\uD83D\uDC06", Collections.singletonList(":leopard:"), Collections.singletonList(":leopard:"), Collections.singletonList(":leopard:"), false, false, 1.0, M1.a("fully-qualified"), "leopard", d00, q10);
        k.g1 = new f("\uD83D\uDC34", "\uD83D\uDC34", Collections.singletonList(":horse:"), Collections.singletonList(":horse:"), Collections.singletonList(":horse:"), false, false, 0.6, M1.a("fully-qualified"), "horse face", d00, q10);
        k.h1 = new f("\uD83E\uDECE", "\uD83E\uDECE", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), false, false, 15.0, M1.a("fully-qualified"), "moose", d00, q10);
        k.i1 = new f("\uD83E\uDECF", "\uD83E\uDECF", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), false, false, 15.0, M1.a("fully-qualified"), "donkey", d00, q10);
        k.j1 = new f("\uD83D\uDC0E", "\uD83D\uDC0E", Collections.singletonList(":racehorse:"), Collections.singletonList(":racehorse:"), Collections.singletonList(":racehorse:"), false, false, 0.6, M1.a("fully-qualified"), "horse", d00, q10);
        k.k1 = new f("\uD83E\uDD84", "\uD83E\uDD84", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":unicorn:", ":unicorn_face:"})), Collections.singletonList(":unicorn_face:"), Collections.singletonList(":unicorn:"), false, false, 1.0, M1.a("fully-qualified"), "unicorn", d00, q10);
        k.l1 = new f("\uD83E\uDD93", "\uD83E\uDD93", Collections.singletonList(":zebra:"), Collections.singletonList(":zebra_face:"), Collections.singletonList(":zebra:"), false, false, 5.0, M1.a("fully-qualified"), "zebra", d00, q10);
        k.m1 = new f("\uD83E\uDD8C", "\uD83E\uDD8C", Collections.singletonList(":deer:"), Collections.singletonList(":deer:"), Collections.singletonList(":deer:"), false, false, 3.0, M1.a("fully-qualified"), "deer", d00, q10);
        k.n1 = new f("\uD83E\uDDAC", "\uD83E\uDDAC", Collections.singletonList(":bison:"), Collections.singletonList(":bison:"), Collections.singletonList(":bison:"), false, false, 13.0, M1.a("fully-qualified"), "bison", d00, q10);
        k.o1 = new f("\uD83D\uDC2E", "\uD83D\uDC2E", Collections.singletonList(":cow:"), Collections.singletonList(":cow:"), Collections.singletonList(":cow:"), false, false, 0.6, M1.a("fully-qualified"), "cow face", d00, q10);
        k.p1 = new f("\uD83D\uDC02", "\uD83D\uDC02", Collections.singletonList(":ox:"), Collections.singletonList(":ox:"), Collections.singletonList(":ox:"), false, false, 1.0, M1.a("fully-qualified"), "ox", d00, q10);
        k.q1 = new f("\uD83D\uDC03", "\uD83D\uDC03", Collections.singletonList(":water_buffalo:"), Collections.singletonList(":water_buffalo:"), Collections.singletonList(":water_buffalo:"), false, false, 1.0, M1.a("fully-qualified"), "water buffalo", d00, q10);
        k.r1 = new f("\uD83D\uDC04", "\uD83D\uDC04", Collections.singletonList(":cow2:"), Collections.singletonList(":cow2:"), Collections.singletonList(":cow2:"), false, false, 1.0, M1.a("fully-qualified"), "cow", d00, q10);
        k.s1 = new f("\uD83D\uDC37", "\uD83D\uDC37", Collections.singletonList(":pig:"), Collections.singletonList(":pig:"), Collections.singletonList(":pig:"), false, false, 0.6, M1.a("fully-qualified"), "pig face", d00, q10);
        k.t1 = new f("\uD83D\uDC16", "\uD83D\uDC16", Collections.singletonList(":pig2:"), Collections.singletonList(":pig2:"), Collections.singletonList(":pig2:"), false, false, 1.0, M1.a("fully-qualified"), "pig", d00, q10);
        k.u1 = new f("\uD83D\uDC17", "\uD83D\uDC17", Collections.singletonList(":boar:"), Collections.singletonList(":boar:"), Collections.singletonList(":boar:"), false, false, 0.6, M1.a("fully-qualified"), "boar", d00, q10);
        k.v1 = new f("\uD83D\uDC3D", "\uD83D\uDC3D", Collections.singletonList(":pig_nose:"), Collections.singletonList(":pig_nose:"), Collections.singletonList(":pig_nose:"), false, false, 0.6, M1.a("fully-qualified"), "pig nose", d00, q10);
        k.w1 = new f("\uD83D\uDC0F", "\uD83D\uDC0F", Collections.singletonList(":ram:"), Collections.singletonList(":ram:"), Collections.singletonList(":ram:"), false, false, 1.0, M1.a("fully-qualified"), "ram", d00, q10);
        k.x1 = new f("\uD83D\uDC11", "\uD83D\uDC11", Collections.singletonList(":sheep:"), Collections.singletonList(":sheep:"), Collections.singletonList(":sheep:"), false, false, 0.6, M1.a("fully-qualified"), "ewe", d00, q10);
        k.y1 = new f("\uD83D\uDC10", "\uD83D\uDC10", Collections.singletonList(":goat:"), Collections.singletonList(":goat:"), Collections.singletonList(":goat:"), false, false, 1.0, M1.a("fully-qualified"), "goat", d00, q10);
        k.z1 = new f("\uD83D\uDC2A", "\uD83D\uDC2A", Collections.singletonList(":dromedary_camel:"), Collections.singletonList(":dromedary_camel:"), Collections.singletonList(":dromedary_camel:"), false, false, 1.0, M1.a("fully-qualified"), "camel", d00, q10);
        k.A1 = new f("\uD83D\uDC2B", "\uD83D\uDC2B", Collections.singletonList(":camel:"), Collections.singletonList(":camel:"), Collections.singletonList(":camel:"), false, false, 0.6, M1.a("fully-qualified"), "two-hump camel", d00, q10);
        k.B1 = new f("\uD83E\uDD99", "\uD83E\uDD99", Collections.singletonList(":llama:"), Collections.singletonList(":llama:"), Collections.singletonList(":llama:"), false, false, 11.0, M1.a("fully-qualified"), "llama", d00, q10);
        k.C1 = new f("\uD83E\uDD92", "\uD83E\uDD92", Collections.singletonList(":giraffe:"), Collections.singletonList(":giraffe_face:"), Collections.singletonList(":giraffe:"), false, false, 5.0, M1.a("fully-qualified"), "giraffe", d00, q10);
        k.D1 = new f("\uD83D\uDC18", "\uD83D\uDC18", Collections.singletonList(":elephant:"), Collections.singletonList(":elephant:"), Collections.singletonList(":elephant:"), false, false, 0.6, M1.a("fully-qualified"), "elephant", d00, q10);
        k.E1 = new f("\uD83E\uDDA3", "\uD83E\uDDA3", Collections.singletonList(":mammoth:"), Collections.singletonList(":mammoth:"), Collections.singletonList(":mammoth:"), false, false, 13.0, M1.a("fully-qualified"), "mammoth", d00, q10);
        k.F1 = new f("\uD83E\uDD8F", "\uD83E\uDD8F", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":rhino:", ":rhinoceros:"})), Collections.singletonList(":rhinoceros:"), Collections.singletonList(":rhinoceros:"), false, false, 3.0, M1.a("fully-qualified"), "rhinoceros", d00, q10);
        k.G1 = new f("\uD83E\uDD9B", "\uD83E\uDD9B", Collections.singletonList(":hippopotamus:"), Collections.singletonList(":hippopotamus:"), Collections.singletonList(":hippopotamus:"), false, false, 11.0, M1.a("fully-qualified"), "hippopotamus", d00, q10);
        k.H1 = new f("\uD83D\uDC2D", "\uD83D\uDC2D", Collections.singletonList(":mouse:"), Collections.singletonList(":mouse:"), Collections.singletonList(":mouse:"), false, false, 0.6, M1.a("fully-qualified"), "mouse face", d00, q10);
        k.I1 = new f("\uD83D\uDC01", "\uD83D\uDC01", Collections.singletonList(":mouse2:"), Collections.singletonList(":mouse2:"), Collections.singletonList(":mouse2:"), false, false, 1.0, M1.a("fully-qualified"), "mouse", d00, q10);
        k.J1 = new f("\uD83D\uDC00", "\uD83D\uDC00", Collections.singletonList(":rat:"), Collections.singletonList(":rat:"), Collections.singletonList(":rat:"), false, false, 1.0, M1.a("fully-qualified"), "rat", d00, q10);
        k.K1 = new f("\uD83D\uDC39", "\uD83D\uDC39", Collections.singletonList(":hamster:"), Collections.singletonList(":hamster:"), Collections.singletonList(":hamster:"), false, false, 0.6, M1.a("fully-qualified"), "hamster", d00, q10);
        k.L1 = new f("\uD83D\uDC30", "\uD83D\uDC30", Collections.singletonList(":rabbit:"), Collections.singletonList(":rabbit:"), Collections.singletonList(":rabbit:"), false, false, 0.6, M1.a("fully-qualified"), "rabbit face", d00, q10);
        k.M1 = new f("\uD83D\uDC07", "\uD83D\uDC07", Collections.singletonList(":rabbit2:"), Collections.singletonList(":rabbit2:"), Collections.singletonList(":rabbit2:"), false, false, 1.0, M1.a("fully-qualified"), "rabbit", d00, q10);
        k.N1 = new f("\uD83D\uDC3F️", "\uD83D\uDC3F️", Collections.singletonList(":chipmunk:"), Collections.singletonList(":chipmunk:"), Collections.singletonList(":chipmunk:"), false, false, 0.7, M1.a("fully-qualified"), "chipmunk", d00, q10);
        k.O1 = new f("\uD83D\uDC3F", "\uD83D\uDC3F", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":chipmunk:"), false, false, 0.7, M1.a("unqualified"), "chipmunk", d00, q10);
        k.P1 = new f("\uD83E\uDDAB", "\uD83E\uDDAB", Collections.singletonList(":beaver:"), Collections.singletonList(":beaver:"), Collections.singletonList(":beaver:"), false, false, 13.0, M1.a("fully-qualified"), "beaver", d00, q10);
        k.Q1 = new f("\uD83E\uDD94", "\uD83E\uDD94", Collections.singletonList(":hedgehog:"), Collections.singletonList(":hedgehog:"), Collections.singletonList(":hedgehog:"), false, false, 5.0, M1.a("fully-qualified"), "hedgehog", d00, q10);
        k.R1 = new f("\uD83E\uDD87", "\uD83E\uDD87", Collections.singletonList(":bat:"), Collections.singletonList(":bat:"), Collections.singletonList(":bat:"), false, false, 3.0, M1.a("fully-qualified"), "bat", d00, q10);
        k.S1 = new f("\uD83D\uDC3B", "\uD83D\uDC3B", Collections.singletonList(":bear:"), Collections.singletonList(":bear:"), Collections.singletonList(":bear:"), false, false, 0.6, M1.a("fully-qualified"), "bear", d00, q10);
        k.T1 = new f("\uD83D\uDC3B‍❄️", "\uD83D\uDC3B‍❄️", Collections.singletonList(":polar_bear:"), Collections.singletonList(":polar_bear:"), Collections.singletonList(":polar_bear:"), false, false, 13.0, M1.a("fully-qualified"), "polar bear", d00, q10);
        k.U1 = new f("\uD83D\uDC3B‍❄", "\uD83D\uDC3B‍❄", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), false, false, 13.0, M1.a("minimally-qualified"), "polar bear", d00, q10);
        k.V1 = new f("\uD83D\uDC28", "\uD83D\uDC28", Collections.singletonList(":koala:"), Collections.singletonList(":koala:"), Collections.singletonList(":koala:"), false, false, 0.6, M1.a("fully-qualified"), "koala", d00, q10);
        k.W1 = new f("\uD83D\uDC3C", "\uD83D\uDC3C", Collections.singletonList(":panda_face:"), Collections.singletonList(":panda_face:"), Collections.singletonList(":panda_face:"), false, false, 0.6, M1.a("fully-qualified"), "panda", d00, q10);
        k.X1 = new f("\uD83E\uDDA5", "\uD83E\uDDA5", Collections.singletonList(":sloth:"), Collections.singletonList(":sloth:"), Collections.singletonList(":sloth:"), false, false, 12.0, M1.a("fully-qualified"), "sloth", d00, q10);
        k.Y1 = new f("\uD83E\uDDA6", "\uD83E\uDDA6", Collections.singletonList(":otter:"), Collections.singletonList(":otter:"), Collections.singletonList(":otter:"), false, false, 12.0, M1.a("fully-qualified"), "otter", d00, q10);
        k.Z1 = new f("\uD83E\uDDA8", "\uD83E\uDDA8", Collections.singletonList(":skunk:"), Collections.singletonList(":skunk:"), Collections.singletonList(":skunk:"), false, false, 12.0, M1.a("fully-qualified"), "skunk", d00, q10);
        k.a2 = new f("\uD83E\uDD98", "\uD83E\uDD98", Collections.singletonList(":kangaroo:"), Collections.singletonList(":kangaroo:"), Collections.singletonList(":kangaroo:"), false, false, 11.0, M1.a("fully-qualified"), "kangaroo", d00, q10);
        k.b2 = new f("\uD83E\uDDA1", "\uD83E\uDDA1", Collections.singletonList(":badger:"), Collections.singletonList(":badger:"), Collections.singletonList(":badger:"), false, false, 11.0, M1.a("fully-qualified"), "badger", d00, q10);
        k.c2 = new f("\uD83D\uDC3E", "\uD83D\uDC3E", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":feet:", ":paw_prints:"})), Collections.singletonList(":feet:"), DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":feet:", ":paw_prints:"})), false, false, 0.6, M1.a("fully-qualified"), "paw prints", d00, q10);
    }
}

