package net.fellbaum.jemoji;

import j..util.DesugarCollections;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

interface r {
    public static final f A4;
    public static final f B4;
    public static final f C4;
    public static final f D4;
    public static final f E4;
    public static final f F4;
    public static final f G4;
    public static final f H4;
    public static final f I4;
    public static final f J4;
    public static final f K4;
    public static final f L4;
    public static final f M4;
    public static final f N4;
    public static final f O4;
    public static final f P4;
    public static final f Q4;
    public static final f R4;
    public static final f S4;
    public static final f T4;
    public static final f U4;
    public static final f V4;
    public static final f W4;
    public static final f X4;
    public static final f Y4;
    public static final f Z4;
    public static final f d4;
    public static final f e4;
    public static final f f4;
    public static final f g4;
    public static final f h4;
    public static final f i4;
    public static final f j4;
    public static final f k4;
    public static final f l4;
    public static final f m4;
    public static final f n4;
    public static final f o4;
    public static final f p4;
    public static final f q4;
    public static final f r4;
    public static final f s4;
    public static final f t4;
    public static final f u4;
    public static final f v4;
    public static final f w4;
    public static final f x4;
    public static final f y4;
    public static final f z4;

    static {
        r.d4 = new f("\uD83D\uDCAA", "\uD83D\uDCAA", Collections.singletonList(":muscle:"), Collections.singletonList(":muscle:"), Collections.singletonList(":muscle:"), false, false, 0.6, M1.a("fully-qualified"), "flexed biceps", d0.h, q1.n);
        List list0 = DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":muscle_tone1:", ":muscle::skin-tone-1:"}));
        List list1 = Collections.singletonList(":muscle::skin-tone-2:");
        List list2 = Collections.emptyList();
        M1 m10 = M1.a("fully-qualified");
        d0 d00 = d0.h;
        q1 q10 = q1.n;
        r.e4 = new f("\uD83D\uDCAA\uD83C\uDFFB", "\uD83D\uDCAA\uD83C\uDFFB", list0, list1, list2, true, false, 1.0, m10, "flexed biceps: light skin tone", d00, q10);
        r.f4 = new f("\uD83D\uDCAA\uD83C\uDFFC", "\uD83D\uDCAA\uD83C\uDFFC", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":muscle_tone2:", ":muscle::skin-tone-2:"})), Collections.singletonList(":muscle::skin-tone-3:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "flexed biceps: medium-light skin tone", d00, q10);
        r.g4 = new f("\uD83D\uDCAA\uD83C\uDFFD", "\uD83D\uDCAA\uD83C\uDFFD", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":muscle_tone3:", ":muscle::skin-tone-3:"})), Collections.singletonList(":muscle::skin-tone-4:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "flexed biceps: medium skin tone", d00, q10);
        r.h4 = new f("\uD83D\uDCAA\uD83C\uDFFE", "\uD83D\uDCAA\uD83C\uDFFE", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":muscle_tone4:", ":muscle::skin-tone-4:"})), Collections.singletonList(":muscle::skin-tone-5:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "flexed biceps: medium-dark skin tone", d00, q10);
        r.i4 = new f("\uD83D\uDCAA\uD83C\uDFFF", "\uD83D\uDCAA\uD83C\uDFFF", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":muscle_tone5:", ":muscle::skin-tone-5:"})), Collections.singletonList(":muscle::skin-tone-6:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "flexed biceps: dark skin tone", d00, q10);
        r.j4 = new f("\uD83E\uDDBE", "\uD83E\uDDBE", Collections.singletonList(":mechanical_arm:"), Collections.singletonList(":mechanical_arm:"), Collections.singletonList(":mechanical_arm:"), false, false, 12.0, M1.a("fully-qualified"), "mechanical arm", d00, q10);
        r.k4 = new f("\uD83E\uDDBF", "\uD83E\uDDBF", Collections.singletonList(":mechanical_leg:"), Collections.singletonList(":mechanical_leg:"), Collections.singletonList(":mechanical_leg:"), false, false, 12.0, M1.a("fully-qualified"), "mechanical leg", d00, q10);
        r.l4 = new f("\uD83E\uDDB5", "\uD83E\uDDB5", Collections.singletonList(":leg:"), Collections.singletonList(":leg:"), Collections.singletonList(":leg:"), false, false, 11.0, M1.a("fully-qualified"), "leg", d00, q10);
        r.m4 = new f("\uD83E\uDDB5\uD83C\uDFFB", "\uD83E\uDDB5\uD83C\uDFFB", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":leg_tone1:", ":leg_light_skin_tone:", ":leg::skin-tone-1:"})), Collections.singletonList(":leg::skin-tone-2:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "leg: light skin tone", d00, q10);
        r.n4 = new f("\uD83E\uDDB5\uD83C\uDFFC", "\uD83E\uDDB5\uD83C\uDFFC", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":leg_tone2:", ":leg_medium_light_skin_tone:", ":leg::skin-tone-2:"})), Collections.singletonList(":leg::skin-tone-3:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "leg: medium-light skin tone", d00, q10);
        r.o4 = new f("\uD83E\uDDB5\uD83C\uDFFD", "\uD83E\uDDB5\uD83C\uDFFD", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":leg_tone3:", ":leg_medium_skin_tone:", ":leg::skin-tone-3:"})), Collections.singletonList(":leg::skin-tone-4:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "leg: medium skin tone", d00, q10);
        r.p4 = new f("\uD83E\uDDB5\uD83C\uDFFE", "\uD83E\uDDB5\uD83C\uDFFE", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":leg_tone4:", ":leg_medium_dark_skin_tone:", ":leg::skin-tone-4:"})), Collections.singletonList(":leg::skin-tone-5:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "leg: medium-dark skin tone", d00, q10);
        r.q4 = new f("\uD83E\uDDB5\uD83C\uDFFF", "\uD83E\uDDB5\uD83C\uDFFF", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":leg_tone5:", ":leg_dark_skin_tone:", ":leg::skin-tone-5:"})), Collections.singletonList(":leg::skin-tone-6:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "leg: dark skin tone", d00, q10);
        r.r4 = new f("\uD83E\uDDB6", "\uD83E\uDDB6", Collections.singletonList(":foot:"), Collections.singletonList(":foot:"), Collections.singletonList(":foot:"), false, false, 11.0, M1.a("fully-qualified"), "foot", d00, q10);
        r.s4 = new f("\uD83E\uDDB6\uD83C\uDFFB", "\uD83E\uDDB6\uD83C\uDFFB", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":foot_tone1:", ":foot_light_skin_tone:", ":foot::skin-tone-1:"})), Collections.singletonList(":foot::skin-tone-2:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "foot: light skin tone", d00, q10);
        r.t4 = new f("\uD83E\uDDB6\uD83C\uDFFC", "\uD83E\uDDB6\uD83C\uDFFC", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":foot_tone2:", ":foot_medium_light_skin_tone:", ":foot::skin-tone-2:"})), Collections.singletonList(":foot::skin-tone-3:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "foot: medium-light skin tone", d00, q10);
        r.u4 = new f("\uD83E\uDDB6\uD83C\uDFFD", "\uD83E\uDDB6\uD83C\uDFFD", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":foot_tone3:", ":foot_medium_skin_tone:", ":foot::skin-tone-3:"})), Collections.singletonList(":foot::skin-tone-4:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "foot: medium skin tone", d00, q10);
        r.v4 = new f("\uD83E\uDDB6\uD83C\uDFFE", "\uD83E\uDDB6\uD83C\uDFFE", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":foot_tone4:", ":foot_medium_dark_skin_tone:", ":foot::skin-tone-4:"})), Collections.singletonList(":foot::skin-tone-5:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "foot: medium-dark skin tone", d00, q10);
        r.w4 = new f("\uD83E\uDDB6\uD83C\uDFFF", "\uD83E\uDDB6\uD83C\uDFFF", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":foot_tone5:", ":foot_dark_skin_tone:", ":foot::skin-tone-5:"})), Collections.singletonList(":foot::skin-tone-6:"), Collections.emptyList(), true, false, 11.0, M1.a("fully-qualified"), "foot: dark skin tone", d00, q10);
        r.x4 = new f("\uD83D\uDC42", "\uD83D\uDC42", Collections.singletonList(":ear:"), Collections.singletonList(":ear:"), Collections.singletonList(":ear:"), false, false, 0.6, M1.a("fully-qualified"), "ear", d00, q10);
        r.y4 = new f("\uD83D\uDC42\uD83C\uDFFB", "\uD83D\uDC42\uD83C\uDFFB", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_tone1:", ":ear::skin-tone-1:"})), Collections.singletonList(":ear::skin-tone-2:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "ear: light skin tone", d00, q10);
        r.z4 = new f("\uD83D\uDC42\uD83C\uDFFC", "\uD83D\uDC42\uD83C\uDFFC", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_tone2:", ":ear::skin-tone-2:"})), Collections.singletonList(":ear::skin-tone-3:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "ear: medium-light skin tone", d00, q10);
        r.A4 = new f("\uD83D\uDC42\uD83C\uDFFD", "\uD83D\uDC42\uD83C\uDFFD", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_tone3:", ":ear::skin-tone-3:"})), Collections.singletonList(":ear::skin-tone-4:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "ear: medium skin tone", d00, q10);
        r.B4 = new f("\uD83D\uDC42\uD83C\uDFFE", "\uD83D\uDC42\uD83C\uDFFE", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_tone4:", ":ear::skin-tone-4:"})), Collections.singletonList(":ear::skin-tone-5:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "ear: medium-dark skin tone", d00, q10);
        r.C4 = new f("\uD83D\uDC42\uD83C\uDFFF", "\uD83D\uDC42\uD83C\uDFFF", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_tone5:", ":ear::skin-tone-5:"})), Collections.singletonList(":ear::skin-tone-6:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "ear: dark skin tone", d00, q10);
        r.D4 = new f("\uD83E\uDDBB", "\uD83E\uDDBB", Collections.singletonList(":ear_with_hearing_aid:"), Collections.singletonList(":ear_with_hearing_aid:"), Collections.singletonList(":ear_with_hearing_aid:"), false, false, 12.0, M1.a("fully-qualified"), "ear with hearing aid", d00, q10);
        r.E4 = new f("\uD83E\uDDBB\uD83C\uDFFB", "\uD83E\uDDBB\uD83C\uDFFB", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_with_hearing_aid_tone1:", ":ear_with_hearing_aid_light_skin_tone:", ":ear_with_hearing_aid::skin-tone-1:"})), Collections.singletonList(":ear_with_hearing_aid::skin-tone-2:"), Collections.emptyList(), true, false, 12.0, M1.a("fully-qualified"), "ear with hearing aid: light skin tone", d00, q10);
        r.F4 = new f("\uD83E\uDDBB\uD83C\uDFFC", "\uD83E\uDDBB\uD83C\uDFFC", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_with_hearing_aid_tone2:", ":ear_with_hearing_aid_medium_light_skin_tone:", ":ear_with_hearing_aid::skin-tone-2:"})), Collections.singletonList(":ear_with_hearing_aid::skin-tone-3:"), Collections.emptyList(), true, false, 12.0, M1.a("fully-qualified"), "ear with hearing aid: medium-light skin tone", d00, q10);
        r.G4 = new f("\uD83E\uDDBB\uD83C\uDFFD", "\uD83E\uDDBB\uD83C\uDFFD", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_with_hearing_aid_tone3:", ":ear_with_hearing_aid_medium_skin_tone:", ":ear_with_hearing_aid::skin-tone-3:"})), Collections.singletonList(":ear_with_hearing_aid::skin-tone-4:"), Collections.emptyList(), true, false, 12.0, M1.a("fully-qualified"), "ear with hearing aid: medium skin tone", d00, q10);
        r.H4 = new f("\uD83E\uDDBB\uD83C\uDFFE", "\uD83E\uDDBB\uD83C\uDFFE", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_with_hearing_aid_tone4:", ":ear_with_hearing_aid_medium_dark_skin_tone:", ":ear_with_hearing_aid::skin-tone-4:"})), Collections.singletonList(":ear_with_hearing_aid::skin-tone-5:"), Collections.emptyList(), true, false, 12.0, M1.a("fully-qualified"), "ear with hearing aid: medium-dark skin tone", d00, q10);
        r.I4 = new f("\uD83E\uDDBB\uD83C\uDFFF", "\uD83E\uDDBB\uD83C\uDFFF", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":ear_with_hearing_aid_tone5:", ":ear_with_hearing_aid_dark_skin_tone:", ":ear_with_hearing_aid::skin-tone-5:"})), Collections.singletonList(":ear_with_hearing_aid::skin-tone-6:"), Collections.emptyList(), true, false, 12.0, M1.a("fully-qualified"), "ear with hearing aid: dark skin tone", d00, q10);
        r.J4 = new f("\uD83D\uDC43", "\uD83D\uDC43", Collections.singletonList(":nose:"), Collections.singletonList(":nose:"), Collections.singletonList(":nose:"), false, false, 0.6, M1.a("fully-qualified"), "nose", d00, q10);
        r.K4 = new f("\uD83D\uDC43\uD83C\uDFFB", "\uD83D\uDC43\uD83C\uDFFB", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":nose_tone1:", ":nose::skin-tone-1:"})), Collections.singletonList(":nose::skin-tone-2:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "nose: light skin tone", d00, q10);
        r.L4 = new f("\uD83D\uDC43\uD83C\uDFFC", "\uD83D\uDC43\uD83C\uDFFC", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":nose_tone2:", ":nose::skin-tone-2:"})), Collections.singletonList(":nose::skin-tone-3:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "nose: medium-light skin tone", d00, q10);
        r.M4 = new f("\uD83D\uDC43\uD83C\uDFFD", "\uD83D\uDC43\uD83C\uDFFD", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":nose_tone3:", ":nose::skin-tone-3:"})), Collections.singletonList(":nose::skin-tone-4:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "nose: medium skin tone", d00, q10);
        r.N4 = new f("\uD83D\uDC43\uD83C\uDFFE", "\uD83D\uDC43\uD83C\uDFFE", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":nose_tone4:", ":nose::skin-tone-4:"})), Collections.singletonList(":nose::skin-tone-5:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "nose: medium-dark skin tone", d00, q10);
        r.O4 = new f("\uD83D\uDC43\uD83C\uDFFF", "\uD83D\uDC43\uD83C\uDFFF", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":nose_tone5:", ":nose::skin-tone-5:"})), Collections.singletonList(":nose::skin-tone-6:"), Collections.emptyList(), true, false, 1.0, M1.a("fully-qualified"), "nose: dark skin tone", d00, q10);
        r.P4 = new f("\uD83E\uDDE0", "\uD83E\uDDE0", Collections.singletonList(":brain:"), Collections.singletonList(":brain:"), Collections.singletonList(":brain:"), false, false, 5.0, M1.a("fully-qualified"), "brain", d00, q10);
        r.Q4 = new f("\uD83E\uDEC0", "\uD83E\uDEC0", Collections.singletonList(":anatomical_heart:"), Collections.singletonList(":anatomical_heart:"), Collections.singletonList(":anatomical_heart:"), false, false, 13.0, M1.a("fully-qualified"), "anatomical heart", d00, q10);
        r.R4 = new f("\uD83E\uDEC1", "\uD83E\uDEC1", Collections.singletonList(":lungs:"), Collections.singletonList(":lungs:"), Collections.singletonList(":lungs:"), false, false, 13.0, M1.a("fully-qualified"), "lungs", d00, q10);
        r.S4 = new f("\uD83E\uDDB7", "\uD83E\uDDB7", Collections.singletonList(":tooth:"), Collections.singletonList(":tooth:"), Collections.singletonList(":tooth:"), false, false, 11.0, M1.a("fully-qualified"), "tooth", d00, q10);
        r.T4 = new f("\uD83E\uDDB4", "\uD83E\uDDB4", Collections.singletonList(":bone:"), Collections.singletonList(":bone:"), Collections.singletonList(":bone:"), false, false, 11.0, M1.a("fully-qualified"), "bone", d00, q10);
        r.U4 = new f("\uD83D\uDC40", "\uD83D\uDC40", Collections.singletonList(":eyes:"), Collections.singletonList(":eyes:"), Collections.singletonList(":eyes:"), false, false, 0.6, M1.a("fully-qualified"), "eyes", d00, q10);
        r.V4 = new f("\uD83D\uDC41️", "\uD83D\uDC41️", Collections.singletonList(":eye:"), Collections.singletonList(":eye:"), Collections.singletonList(":eye:"), false, false, 0.7, M1.a("fully-qualified"), "eye", d00, q10);
        r.W4 = new f("\uD83D\uDC41", "\uD83D\uDC41", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":eye:"), false, false, 0.7, M1.a("unqualified"), "eye", d00, q10);
        r.X4 = new f("\uD83D\uDC45", "\uD83D\uDC45", Collections.singletonList(":tongue:"), Collections.singletonList(":tongue:"), Collections.singletonList(":tongue:"), false, false, 0.6, M1.a("fully-qualified"), "tongue", d00, q10);
        r.Y4 = new f("\uD83D\uDC44", "\uD83D\uDC44", Collections.singletonList(":lips:"), Collections.singletonList(":lips:"), Collections.singletonList(":lips:"), false, false, 0.6, M1.a("fully-qualified"), "mouth", d00, q10);
        r.Z4 = new f("\uD83E\uDEE6", "\uD83E\uDEE6", Collections.singletonList(":biting_lip:"), Collections.emptyList(), Collections.emptyList(), false, false, 14.0, M1.a("fully-qualified"), "biting lip", d00, q10);
    }
}

