package net.fellbaum.jemoji;

import j..util.DesugarCollections;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

interface u {
    public static final f C5;
    public static final f D5;
    public static final f E5;
    public static final f F5;
    public static final f G5;
    public static final f H5;
    public static final f I5;
    public static final f J5;
    public static final f K5;
    public static final f L5;
    public static final f M5;
    public static final f N5;
    public static final f O5;
    public static final f P5;
    public static final f Q5;
    public static final f R5;
    public static final f S5;
    public static final f T5;
    public static final f U5;
    public static final f V5;
    public static final f W5;
    public static final f X5;
    public static final f Y5;
    public static final f Z5;
    public static final f a6;
    public static final f b6;
    public static final f c6;
    public static final f d6;
    public static final f e6;
    public static final f f6;
    public static final f g6;
    public static final f h6;
    public static final f i6;
    public static final f j6;
    public static final f k6;
    public static final f l6;
    public static final f m6;
    public static final f n6;
    public static final f o6;
    public static final f p6;
    public static final f q6;
    public static final f r6;
    public static final f s6;
    public static final f t6;
    public static final f u6;
    public static final f v6;
    public static final f w6;
    public static final f x6;
    public static final f y6;
    public static final f z6;

    static {
        u.C5 = new f("\uD83D\uDC53", "\uD83D\uDC53", Collections.singletonList(":eyeglasses:"), Collections.singletonList(":eyeglasses:"), Collections.singletonList(":eyeglasses:"), false, false, 0.6, M1.a("fully-qualified"), "glasses", d0.g, q1.q);
        List list0 = Collections.singletonList(":dark_sunglasses:");
        List list1 = Collections.singletonList(":dark_sunglasses:");
        List list2 = Collections.singletonList(":dark_sunglasses:");
        M1 m10 = M1.a("fully-qualified");
        d0 d00 = d0.g;
        q1 q10 = q1.q;
        u.D5 = new f("\uD83D\uDD76️", "\uD83D\uDD76️", list0, list1, list2, false, false, 0.7, m10, "sunglasses", d00, q10);
        u.E5 = new f("\uD83D\uDD76", "\uD83D\uDD76", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":dark_sunglasses:"), false, false, 0.7, M1.a("unqualified"), "sunglasses", d00, q10);
        u.F5 = new f("\uD83E\uDD7D", "\uD83E\uDD7D", Collections.singletonList(":goggles:"), Collections.singletonList(":goggles:"), Collections.singletonList(":goggles:"), false, false, 11.0, M1.a("fully-qualified"), "goggles", d00, q10);
        u.G5 = new f("\uD83E\uDD7C", "\uD83E\uDD7C", Collections.singletonList(":lab_coat:"), Collections.singletonList(":lab_coat:"), Collections.singletonList(":lab_coat:"), false, false, 11.0, M1.a("fully-qualified"), "lab coat", d00, q10);
        u.H5 = new f("\uD83E\uDDBA", "\uD83E\uDDBA", Collections.singletonList(":safety_vest:"), Collections.singletonList(":safety_vest:"), Collections.singletonList(":safety_vest:"), false, false, 12.0, M1.a("fully-qualified"), "safety vest", d00, q10);
        u.I5 = new f("\uD83D\uDC54", "\uD83D\uDC54", Collections.singletonList(":necktie:"), Collections.singletonList(":necktie:"), Collections.singletonList(":necktie:"), false, false, 0.6, M1.a("fully-qualified"), "necktie", d00, q10);
        u.J5 = new f("\uD83D\uDC55", "\uD83D\uDC55", Collections.singletonList(":shirt:"), Collections.singletonList(":shirt:"), DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":shirt:", ":tshirt:"})), false, false, 0.6, M1.a("fully-qualified"), "t-shirt", d00, q10);
        u.K5 = new f("\uD83D\uDC56", "\uD83D\uDC56", Collections.singletonList(":jeans:"), Collections.singletonList(":jeans:"), Collections.singletonList(":jeans:"), false, false, 0.6, M1.a("fully-qualified"), "jeans", d00, q10);
        u.L5 = new f("\uD83E\uDDE3", "\uD83E\uDDE3", Collections.singletonList(":scarf:"), Collections.singletonList(":scarf:"), Collections.singletonList(":scarf:"), false, false, 5.0, M1.a("fully-qualified"), "scarf", d00, q10);
        u.M5 = new f("\uD83E\uDDE4", "\uD83E\uDDE4", Collections.singletonList(":gloves:"), Collections.singletonList(":gloves:"), Collections.singletonList(":gloves:"), false, false, 5.0, M1.a("fully-qualified"), "gloves", d00, q10);
        u.N5 = new f("\uD83E\uDDE5", "\uD83E\uDDE5", Collections.singletonList(":coat:"), Collections.singletonList(":coat:"), Collections.singletonList(":coat:"), false, false, 5.0, M1.a("fully-qualified"), "coat", d00, q10);
        u.O5 = new f("\uD83E\uDDE6", "\uD83E\uDDE6", Collections.singletonList(":socks:"), Collections.singletonList(":socks:"), Collections.singletonList(":socks:"), false, false, 5.0, M1.a("fully-qualified"), "socks", d00, q10);
        u.P5 = new f("\uD83D\uDC57", "\uD83D\uDC57", Collections.singletonList(":dress:"), Collections.singletonList(":dress:"), Collections.singletonList(":dress:"), false, false, 0.6, M1.a("fully-qualified"), "dress", d00, q10);
        u.Q5 = new f("\uD83D\uDC58", "\uD83D\uDC58", Collections.singletonList(":kimono:"), Collections.singletonList(":kimono:"), Collections.singletonList(":kimono:"), false, false, 0.6, M1.a("fully-qualified"), "kimono", d00, q10);
        u.R5 = new f("\uD83E\uDD7B", "\uD83E\uDD7B", Collections.singletonList(":sari:"), Collections.singletonList(":sari:"), Collections.singletonList(":sari:"), false, false, 12.0, M1.a("fully-qualified"), "sari", d00, q10);
        u.S5 = new f("\uD83E\uDE71", "\uD83E\uDE71", Collections.singletonList(":one_piece_swimsuit:"), Collections.singletonList(":one-piece_swimsuit:"), Collections.singletonList(":one_piece_swimsuit:"), false, false, 12.0, M1.a("fully-qualified"), "one-piece swimsuit", d00, q10);
        u.T5 = new f("\uD83E\uDE72", "\uD83E\uDE72", Collections.singletonList(":briefs:"), Collections.singletonList(":briefs:"), Collections.singletonList(":swim_brief:"), false, false, 12.0, M1.a("fully-qualified"), "briefs", d00, q10);
        u.U5 = new f("\uD83E\uDE73", "\uD83E\uDE73", Collections.singletonList(":shorts:"), Collections.singletonList(":shorts:"), Collections.singletonList(":shorts:"), false, false, 12.0, M1.a("fully-qualified"), "shorts", d00, q10);
        u.V5 = new f("\uD83D\uDC59", "\uD83D\uDC59", Collections.singletonList(":bikini:"), Collections.singletonList(":bikini:"), Collections.singletonList(":bikini:"), false, false, 0.6, M1.a("fully-qualified"), "bikini", d00, q10);
        u.W5 = new f("\uD83D\uDC5A", "\uD83D\uDC5A", Collections.singletonList(":womans_clothes:"), Collections.singletonList(":womans_clothes:"), Collections.singletonList(":womans_clothes:"), false, false, 0.6, M1.a("fully-qualified"), "woman’s clothes", d00, q10);
        u.X5 = new f("\uD83E\uDEAD", "\uD83E\uDEAD", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), false, false, 15.0, M1.a("fully-qualified"), "folding hand fan", d00, q10);
        u.Y5 = new f("\uD83D\uDC5B", "\uD83D\uDC5B", Collections.singletonList(":purse:"), Collections.singletonList(":purse:"), Collections.singletonList(":purse:"), false, false, 0.6, M1.a("fully-qualified"), "purse", d00, q10);
        u.Z5 = new f("\uD83D\uDC5C", "\uD83D\uDC5C", Collections.singletonList(":handbag:"), Collections.singletonList(":handbag:"), Collections.singletonList(":handbag:"), false, false, 0.6, M1.a("fully-qualified"), "handbag", d00, q10);
        u.a6 = new f("\uD83D\uDC5D", "\uD83D\uDC5D", Collections.singletonList(":pouch:"), Collections.singletonList(":pouch:"), Collections.singletonList(":pouch:"), false, false, 0.6, M1.a("fully-qualified"), "clutch bag", d00, q10);
        u.b6 = new f("\uD83D\uDECD️", "\uD83D\uDECD️", Collections.singletonList(":shopping_bags:"), Collections.singletonList(":shopping_bags:"), Collections.singletonList(":shopping:"), false, false, 0.7, M1.a("fully-qualified"), "shopping bags", d00, q10);
        u.c6 = new f("\uD83D\uDECD", "\uD83D\uDECD", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":shopping:"), false, false, 0.7, M1.a("unqualified"), "shopping bags", d00, q10);
        u.d6 = new f("\uD83C\uDF92", "\uD83C\uDF92", Collections.singletonList(":school_satchel:"), Collections.singletonList(":school_satchel:"), Collections.singletonList(":school_satchel:"), false, false, 0.6, M1.a("fully-qualified"), "backpack", d00, q10);
        u.e6 = new f("\uD83E\uDE74", "\uD83E\uDE74", Collections.singletonList(":thong_sandal:"), Collections.singletonList(":thong_sandal:"), Collections.singletonList(":thong_sandal:"), false, false, 13.0, M1.a("fully-qualified"), "thong sandal", d00, q10);
        u.f6 = new f("\uD83D\uDC5E", "\uD83D\uDC5E", Collections.singletonList(":mans_shoe:"), Collections.singletonList(":mans_shoe:"), DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":mans_shoe:", ":shoe:"})), false, false, 0.6, M1.a("fully-qualified"), "man’s shoe", d00, q10);
        u.g6 = new f("\uD83D\uDC5F", "\uD83D\uDC5F", Collections.singletonList(":athletic_shoe:"), Collections.singletonList(":athletic_shoe:"), Collections.singletonList(":athletic_shoe:"), false, false, 0.6, M1.a("fully-qualified"), "running shoe", d00, q10);
        u.h6 = new f("\uD83E\uDD7E", "\uD83E\uDD7E", Collections.singletonList(":hiking_boot:"), Collections.singletonList(":hiking_boot:"), Collections.singletonList(":hiking_boot:"), false, false, 11.0, M1.a("fully-qualified"), "hiking boot", d00, q10);
        u.i6 = new f("\uD83E\uDD7F", "\uD83E\uDD7F", Collections.singletonList(":womans_flat_shoe:"), Collections.singletonList(":womans_flat_shoe:"), Collections.singletonList(":flat_shoe:"), false, false, 11.0, M1.a("fully-qualified"), "flat shoe", d00, q10);
        u.j6 = new f("\uD83D\uDC60", "\uD83D\uDC60", Collections.singletonList(":high_heel:"), Collections.singletonList(":high_heel:"), Collections.singletonList(":high_heel:"), false, false, 0.6, M1.a("fully-qualified"), "high-heeled shoe", d00, q10);
        u.k6 = new f("\uD83D\uDC61", "\uD83D\uDC61", Collections.singletonList(":sandal:"), Collections.singletonList(":sandal:"), Collections.singletonList(":sandal:"), false, false, 0.6, M1.a("fully-qualified"), "woman’s sandal", d00, q10);
        u.l6 = new f("\uD83E\uDE70", "\uD83E\uDE70", Collections.singletonList(":ballet_shoes:"), Collections.singletonList(":ballet_shoes:"), Collections.singletonList(":ballet_shoes:"), false, false, 12.0, M1.a("fully-qualified"), "ballet shoes", d00, q10);
        u.m6 = new f("\uD83D\uDC62", "\uD83D\uDC62", Collections.singletonList(":boot:"), Collections.singletonList(":boot:"), Collections.singletonList(":boot:"), false, false, 0.6, M1.a("fully-qualified"), "woman’s boot", d00, q10);
        u.n6 = new f("\uD83E\uDEAE", "\uD83E\uDEAE", Collections.emptyList(), Collections.emptyList(), Collections.emptyList(), false, false, 15.0, M1.a("fully-qualified"), "hair pick", d00, q10);
        u.o6 = new f("\uD83D\uDC51", "\uD83D\uDC51", Collections.singletonList(":crown:"), Collections.singletonList(":crown:"), Collections.singletonList(":crown:"), false, false, 0.6, M1.a("fully-qualified"), "crown", d00, q10);
        u.p6 = new f("\uD83D\uDC52", "\uD83D\uDC52", Collections.singletonList(":womans_hat:"), Collections.singletonList(":womans_hat:"), Collections.singletonList(":womans_hat:"), false, false, 0.6, M1.a("fully-qualified"), "woman’s hat", d00, q10);
        u.q6 = new f("\uD83C\uDFA9", "\uD83C\uDFA9", Collections.singletonList(":tophat:"), Collections.singletonList(":tophat:"), Collections.singletonList(":tophat:"), false, false, 0.6, M1.a("fully-qualified"), "top hat", d00, q10);
        u.r6 = new f("\uD83C\uDF93", "\uD83C\uDF93", Collections.singletonList(":mortar_board:"), Collections.singletonList(":mortar_board:"), Collections.singletonList(":mortar_board:"), false, false, 0.6, M1.a("fully-qualified"), "graduation cap", d00, q10);
        u.s6 = new f("\uD83E\uDDE2", "\uD83E\uDDE2", Collections.singletonList(":billed_cap:"), Collections.singletonList(":billed_cap:"), Collections.singletonList(":billed_cap:"), false, false, 5.0, M1.a("fully-qualified"), "billed cap", d00, q10);
        u.t6 = new f("\uD83E\uDE96", "\uD83E\uDE96", Collections.singletonList(":military_helmet:"), Collections.singletonList(":military_helmet:"), Collections.singletonList(":military_helmet:"), false, false, 13.0, M1.a("fully-qualified"), "military helmet", d00, q10);
        u.u6 = new f("⛑️", "⛑️", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":helmet_with_cross:", ":helmet_with_white_cross:"})), Collections.singletonList(":helmet_with_white_cross:"), Collections.singletonList(":rescue_worker_helmet:"), false, false, 0.7, M1.a("fully-qualified"), "rescue worker’s helmet", d00, q10);
        u.v6 = new f("⛑", "⛑", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":rescue_worker_helmet:"), false, false, 0.7, M1.a("unqualified"), "rescue worker’s helmet", d00, q10);
        u.w6 = new f("\uD83D\uDCFF", "\uD83D\uDCFF", Collections.singletonList(":prayer_beads:"), Collections.singletonList(":prayer_beads:"), Collections.singletonList(":prayer_beads:"), false, false, 1.0, M1.a("fully-qualified"), "prayer beads", d00, q10);
        u.x6 = new f("\uD83D\uDC84", "\uD83D\uDC84", Collections.singletonList(":lipstick:"), Collections.singletonList(":lipstick:"), Collections.singletonList(":lipstick:"), false, false, 0.6, M1.a("fully-qualified"), "lipstick", d00, q10);
        u.y6 = new f("\uD83D\uDC8D", "\uD83D\uDC8D", Collections.singletonList(":ring:"), Collections.singletonList(":ring:"), Collections.singletonList(":ring:"), false, false, 0.6, M1.a("fully-qualified"), "ring", d00, q10);
        u.z6 = new f("\uD83D\uDC8E", "\uD83D\uDC8E", Collections.singletonList(":gem:"), Collections.singletonList(":gem:"), Collections.singletonList(":gem:"), false, false, 0.6, M1.a("fully-qualified"), "gem stone", d00, q10);
    }
}

