package net.fellbaum.jemoji;

import j..util.DesugarCollections;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

interface v1 {
    public static final f Aw0;
    public static final f Bv0;
    public static final f Bw0;
    public static final f Cv0;
    public static final f Cw0;
    public static final f Dv0;
    public static final f Dw0;
    public static final f Ev0;
    public static final f Fv0;
    public static final f Gv0;
    public static final f Hv0;
    public static final f Iv0;
    public static final f Jv0;
    public static final f Kv0;
    public static final f Lv0;
    public static final f Mv0;
    public static final f Nv0;
    public static final f Ov0;
    public static final f Pv0;
    public static final f Qv0;
    public static final f Rv0;
    public static final f Sv0;
    public static final f Tv0;
    public static final f Uv0;
    public static final f Vv0;
    public static final f Wv0;
    public static final f Xv0;
    public static final f Yv0;
    public static final f Zv0;
    public static final f aw0;
    public static final f bw0;
    public static final f cw0;
    public static final f dw0;
    public static final f ew0;
    public static final f fw0;
    public static final f gw0;
    public static final f hw0;
    public static final f iw0;
    public static final f jw0;
    public static final f kw0;
    public static final f lw0;
    public static final f mw0;
    public static final f nw0;
    public static final f ow0;
    public static final f pw0;
    public static final f qw0;
    public static final f rw0;
    public static final f sw0;
    public static final f tw0;
    public static final f uw0;
    public static final f vw0;
    public static final f ww0;
    public static final f xw0;
    public static final f yw0;
    public static final f zw0;

    static {
        v1.Bv0 = new f("\uD83D\uDE82", "\uD83D\uDE82", Collections.singletonList(":steam_locomotive:"), Collections.singletonList(":steam_locomotive:"), Collections.singletonList(":steam_locomotive:"), false, false, 1.0, M1.a("fully-qualified"), "locomotive", d0.k, q1.L9);
        List list0 = Collections.singletonList(":railway_car:");
        List list1 = Collections.singletonList(":railway_car:");
        List list2 = Collections.singletonList(":railway_car:");
        M1 m10 = M1.a("fully-qualified");
        d0 d00 = d0.k;
        q1 q10 = q1.L9;
        v1.Cv0 = new f("\uD83D\uDE83", "\uD83D\uDE83", list0, list1, list2, false, false, 0.6, m10, "railway car", d00, q10);
        v1.Dv0 = new f("\uD83D\uDE84", "\uD83D\uDE84", Collections.singletonList(":bullettrain_side:"), Collections.singletonList(":bullettrain_side:"), Collections.singletonList(":bullettrain_side:"), false, false, 0.6, M1.a("fully-qualified"), "high-speed train", d00, q10);
        v1.Ev0 = new f("\uD83D\uDE85", "\uD83D\uDE85", Collections.singletonList(":bullettrain_front:"), Collections.singletonList(":bullettrain_front:"), Collections.singletonList(":bullettrain_front:"), false, false, 0.6, M1.a("fully-qualified"), "bullet train", d00, q10);
        v1.Fv0 = new f("\uD83D\uDE86", "\uD83D\uDE86", Collections.singletonList(":train2:"), Collections.singletonList(":train2:"), Collections.singletonList(":train2:"), false, false, 1.0, M1.a("fully-qualified"), "train", d00, q10);
        v1.Gv0 = new f("\uD83D\uDE87", "\uD83D\uDE87", Collections.singletonList(":metro:"), Collections.singletonList(":metro:"), Collections.singletonList(":metro:"), false, false, 0.6, M1.a("fully-qualified"), "metro", d00, q10);
        v1.Hv0 = new f("\uD83D\uDE88", "\uD83D\uDE88", Collections.singletonList(":light_rail:"), Collections.singletonList(":light_rail:"), Collections.singletonList(":light_rail:"), false, false, 1.0, M1.a("fully-qualified"), "light rail", d00, q10);
        v1.Iv0 = new f("\uD83D\uDE89", "\uD83D\uDE89", Collections.singletonList(":station:"), Collections.singletonList(":station:"), Collections.singletonList(":station:"), false, false, 0.6, M1.a("fully-qualified"), "station", d00, q10);
        v1.Jv0 = new f("\uD83D\uDE8A", "\uD83D\uDE8A", Collections.singletonList(":tram:"), Collections.singletonList(":tram:"), Collections.singletonList(":tram:"), false, false, 1.0, M1.a("fully-qualified"), "tram", d00, q10);
        v1.Kv0 = new f("\uD83D\uDE9D", "\uD83D\uDE9D", Collections.singletonList(":monorail:"), Collections.singletonList(":monorail:"), Collections.singletonList(":monorail:"), false, false, 1.0, M1.a("fully-qualified"), "monorail", d00, q10);
        v1.Lv0 = new f("\uD83D\uDE9E", "\uD83D\uDE9E", Collections.singletonList(":mountain_railway:"), Collections.singletonList(":mountain_railway:"), Collections.singletonList(":mountain_railway:"), false, false, 1.0, M1.a("fully-qualified"), "mountain railway", d00, q10);
        v1.Mv0 = new f("\uD83D\uDE8B", "\uD83D\uDE8B", Collections.singletonList(":train:"), Collections.singletonList(":train:"), Collections.singletonList(":train:"), false, false, 1.0, M1.a("fully-qualified"), "tram car", d00, q10);
        v1.Nv0 = new f("\uD83D\uDE8C", "\uD83D\uDE8C", Collections.singletonList(":bus:"), Collections.singletonList(":bus:"), Collections.singletonList(":bus:"), false, false, 0.6, M1.a("fully-qualified"), "bus", d00, q10);
        v1.Ov0 = new f("\uD83D\uDE8D", "\uD83D\uDE8D", Collections.singletonList(":oncoming_bus:"), Collections.singletonList(":oncoming_bus:"), Collections.singletonList(":oncoming_bus:"), false, false, 0.7, M1.a("fully-qualified"), "oncoming bus", d00, q10);
        v1.Pv0 = new f("\uD83D\uDE8E", "\uD83D\uDE8E", Collections.singletonList(":trolleybus:"), Collections.singletonList(":trolleybus:"), Collections.singletonList(":trolleybus:"), false, false, 1.0, M1.a("fully-qualified"), "trolleybus", d00, q10);
        v1.Qv0 = new f("\uD83D\uDE90", "\uD83D\uDE90", Collections.singletonList(":minibus:"), Collections.singletonList(":minibus:"), Collections.singletonList(":minibus:"), false, false, 1.0, M1.a("fully-qualified"), "minibus", d00, q10);
        v1.Rv0 = new f("\uD83D\uDE91", "\uD83D\uDE91", Collections.singletonList(":ambulance:"), Collections.singletonList(":ambulance:"), Collections.singletonList(":ambulance:"), false, false, 0.6, M1.a("fully-qualified"), "ambulance", d00, q10);
        v1.Sv0 = new f("\uD83D\uDE92", "\uD83D\uDE92", Collections.singletonList(":fire_engine:"), Collections.singletonList(":fire_engine:"), Collections.singletonList(":fire_engine:"), false, false, 0.6, M1.a("fully-qualified"), "fire engine", d00, q10);
        v1.Tv0 = new f("\uD83D\uDE93", "\uD83D\uDE93", Collections.singletonList(":police_car:"), Collections.singletonList(":police_car:"), Collections.singletonList(":police_car:"), false, false, 0.6, M1.a("fully-qualified"), "police car", d00, q10);
        v1.Uv0 = new f("\uD83D\uDE94", "\uD83D\uDE94", Collections.singletonList(":oncoming_police_car:"), Collections.singletonList(":oncoming_police_car:"), Collections.singletonList(":oncoming_police_car:"), false, false, 0.7, M1.a("fully-qualified"), "oncoming police car", d00, q10);
        v1.Vv0 = new f("\uD83D\uDE95", "\uD83D\uDE95", Collections.singletonList(":taxi:"), Collections.singletonList(":taxi:"), Collections.singletonList(":taxi:"), false, false, 0.6, M1.a("fully-qualified"), "taxi", d00, q10);
        v1.Wv0 = new f("\uD83D\uDE96", "\uD83D\uDE96", Collections.singletonList(":oncoming_taxi:"), Collections.singletonList(":oncoming_taxi:"), Collections.singletonList(":oncoming_taxi:"), false, false, 1.0, M1.a("fully-qualified"), "oncoming taxi", d00, q10);
        v1.Xv0 = new f("\uD83D\uDE97", "\uD83D\uDE97", Collections.singletonList(":red_car:"), Collections.singletonList(":car:"), DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":car:", ":red_car:"})), false, false, 0.6, M1.a("fully-qualified"), "automobile", d00, q10);
        v1.Yv0 = new f("\uD83D\uDE98", "\uD83D\uDE98", Collections.singletonList(":oncoming_automobile:"), Collections.singletonList(":oncoming_automobile:"), Collections.singletonList(":oncoming_automobile:"), false, false, 0.7, M1.a("fully-qualified"), "oncoming automobile", d00, q10);
        v1.Zv0 = new f("\uD83D\uDE99", "\uD83D\uDE99", Collections.singletonList(":blue_car:"), Collections.singletonList(":blue_car:"), Collections.singletonList(":blue_car:"), false, false, 0.6, M1.a("fully-qualified"), "sport utility vehicle", d00, q10);
        v1.aw0 = new f("\uD83D\uDEFB", "\uD83D\uDEFB", Collections.singletonList(":pickup_truck:"), Collections.singletonList(":pickup_truck:"), Collections.singletonList(":pickup_truck:"), false, false, 13.0, M1.a("fully-qualified"), "pickup truck", d00, q10);
        v1.bw0 = new f("\uD83D\uDE9A", "\uD83D\uDE9A", Collections.singletonList(":truck:"), Collections.singletonList(":truck:"), Collections.singletonList(":truck:"), false, false, 0.6, M1.a("fully-qualified"), "delivery truck", d00, q10);
        v1.cw0 = new f("\uD83D\uDE9B", "\uD83D\uDE9B", Collections.singletonList(":articulated_lorry:"), Collections.singletonList(":articulated_lorry:"), Collections.singletonList(":articulated_lorry:"), false, false, 1.0, M1.a("fully-qualified"), "articulated lorry", d00, q10);
        v1.dw0 = new f("\uD83D\uDE9C", "\uD83D\uDE9C", Collections.singletonList(":tractor:"), Collections.singletonList(":tractor:"), Collections.singletonList(":tractor:"), false, false, 1.0, M1.a("fully-qualified"), "tractor", d00, q10);
        v1.ew0 = new f("\uD83C\uDFCE️", "\uD83C\uDFCE️", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":race_car:", ":racing_car:"})), Collections.singletonList(":racing_car:"), Collections.singletonList(":racing_car:"), false, false, 0.7, M1.a("fully-qualified"), "racing car", d00, q10);
        v1.fw0 = new f("\uD83C\uDFCE", "\uD83C\uDFCE", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":racing_car:"), false, false, 0.7, M1.a("unqualified"), "racing car", d00, q10);
        v1.gw0 = new f("\uD83C\uDFCD️", "\uD83C\uDFCD️", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":motorcycle:", ":racing_motorcycle:"})), Collections.singletonList(":racing_motorcycle:"), Collections.singletonList(":motorcycle:"), false, false, 0.7, M1.a("fully-qualified"), "motorcycle", d00, q10);
        v1.hw0 = new f("\uD83C\uDFCD", "\uD83C\uDFCD", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":motorcycle:"), false, false, 0.7, M1.a("unqualified"), "motorcycle", d00, q10);
        v1.iw0 = new f("\uD83D\uDEF5", "\uD83D\uDEF5", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":motor_scooter:", ":motorbike:"})), Collections.singletonList(":motor_scooter:"), Collections.singletonList(":motor_scooter:"), false, false, 3.0, M1.a("fully-qualified"), "motor scooter", d00, q10);
        v1.jw0 = new f("\uD83E\uDDBD", "\uD83E\uDDBD", Collections.singletonList(":manual_wheelchair:"), Collections.singletonList(":manual_wheelchair:"), Collections.singletonList(":manual_wheelchair:"), false, false, 12.0, M1.a("fully-qualified"), "manual wheelchair", d00, q10);
        v1.kw0 = new f("\uD83E\uDDBC", "\uD83E\uDDBC", Collections.singletonList(":motorized_wheelchair:"), Collections.singletonList(":motorized_wheelchair:"), Collections.singletonList(":motorized_wheelchair:"), false, false, 12.0, M1.a("fully-qualified"), "motorized wheelchair", d00, q10);
        v1.lw0 = new f("\uD83D\uDEFA", "\uD83D\uDEFA", Collections.singletonList(":auto_rickshaw:"), Collections.singletonList(":auto_rickshaw:"), Collections.singletonList(":auto_rickshaw:"), false, false, 12.0, M1.a("fully-qualified"), "auto rickshaw", d00, q10);
        v1.mw0 = new f("\uD83D\uDEB2", "\uD83D\uDEB2", Collections.singletonList(":bike:"), Collections.singletonList(":bike:"), Collections.singletonList(":bike:"), false, false, 0.6, M1.a("fully-qualified"), "bicycle", d00, q10);
        v1.nw0 = new f("\uD83D\uDEF4", "\uD83D\uDEF4", Collections.singletonList(":scooter:"), Collections.singletonList(":scooter:"), Collections.singletonList(":kick_scooter:"), false, false, 3.0, M1.a("fully-qualified"), "kick scooter", d00, q10);
        v1.ow0 = new f("\uD83D\uDEF9", "\uD83D\uDEF9", Collections.singletonList(":skateboard:"), Collections.singletonList(":skateboard:"), Collections.singletonList(":skateboard:"), false, false, 11.0, M1.a("fully-qualified"), "skateboard", d00, q10);
        v1.pw0 = new f("\uD83D\uDEFC", "\uD83D\uDEFC", Collections.singletonList(":roller_skate:"), Collections.singletonList(":roller_skate:"), Collections.singletonList(":roller_skate:"), false, false, 13.0, M1.a("fully-qualified"), "roller skate", d00, q10);
        v1.qw0 = new f("\uD83D\uDE8F", "\uD83D\uDE8F", Collections.singletonList(":busstop:"), Collections.singletonList(":busstop:"), Collections.singletonList(":busstop:"), false, false, 0.6, M1.a("fully-qualified"), "bus stop", d00, q10);
        v1.rw0 = new f("\uD83D\uDEE3️", "\uD83D\uDEE3️", Collections.singletonList(":motorway:"), Collections.singletonList(":motorway:"), Collections.singletonList(":motorway:"), false, false, 0.7, M1.a("fully-qualified"), "motorway", d00, q10);
        v1.sw0 = new f("\uD83D\uDEE3", "\uD83D\uDEE3", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":motorway:"), false, false, 0.7, M1.a("unqualified"), "motorway", d00, q10);
        v1.tw0 = new f("\uD83D\uDEE4️", "\uD83D\uDEE4️", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":railway_track:", ":railroad_track:"})), Collections.singletonList(":railway_track:"), Collections.singletonList(":railway_track:"), false, false, 0.7, M1.a("fully-qualified"), "railway track", d00, q10);
        v1.uw0 = new f("\uD83D\uDEE4", "\uD83D\uDEE4", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":railway_track:"), false, false, 0.7, M1.a("unqualified"), "railway track", d00, q10);
        v1.vw0 = new f("\uD83D\uDEE2️", "\uD83D\uDEE2️", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":oil:", ":oil_drum:"})), Collections.singletonList(":oil_drum:"), Collections.singletonList(":oil_drum:"), false, false, 0.7, M1.a("fully-qualified"), "oil drum", d00, q10);
        v1.ww0 = new f("\uD83D\uDEE2", "\uD83D\uDEE2", Collections.emptyList(), Collections.emptyList(), Collections.singletonList(":oil_drum:"), false, false, 0.7, M1.a("unqualified"), "oil drum", d00, q10);
        v1.xw0 = new f("⛽", "⛽", Collections.singletonList(":fuelpump:"), Collections.singletonList(":fuelpump:"), Collections.singletonList(":fuelpump:"), false, false, 0.6, M1.a("fully-qualified"), "fuel pump", d00, q10);
        v1.yw0 = new f("\uD83D\uDEDE", "\uD83D\uDEDE", Collections.singletonList(":wheel:"), Collections.emptyList(), Collections.emptyList(), false, false, 14.0, M1.a("fully-qualified"), "wheel", d00, q10);
        v1.zw0 = new f("\uD83D\uDEA8", "\uD83D\uDEA8", Collections.singletonList(":rotating_light:"), Collections.singletonList(":rotating_light:"), Collections.singletonList(":rotating_light:"), false, false, 0.6, M1.a("fully-qualified"), "police car light", d00, q10);
        v1.Aw0 = new f("\uD83D\uDEA5", "\uD83D\uDEA5", Collections.singletonList(":traffic_light:"), Collections.singletonList(":traffic_light:"), Collections.singletonList(":traffic_light:"), false, false, 0.6, M1.a("fully-qualified"), "horizontal traffic light", d00, q10);
        v1.Bw0 = new f("\uD83D\uDEA6", "\uD83D\uDEA6", Collections.singletonList(":vertical_traffic_light:"), Collections.singletonList(":vertical_traffic_light:"), Collections.singletonList(":vertical_traffic_light:"), false, false, 1.0, M1.a("fully-qualified"), "vertical traffic light", d00, q10);
        v1.Cw0 = new f("\uD83D\uDED1", "\uD83D\uDED1", DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":octagonal_sign:", ":stop_sign:"})), Collections.singletonList(":octagonal_sign:"), Collections.singletonList(":stop_sign:"), false, false, 3.0, M1.a("fully-qualified"), "stop sign", d00, q10);
        v1.Dw0 = new f("\uD83D\uDEA7", "\uD83D\uDEA7", Collections.singletonList(":construction:"), Collections.singletonList(":construction:"), Collections.singletonList(":construction:"), false, false, 0.6, M1.a("fully-qualified"), "construction", d00, q10);
    }
}

