package net.fellbaum.jemoji;

import j..util.DesugarCollections;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

interface w {
    public static final f A7;
    public static final f A8;
    public static final f A9;
    public static final f Aa;
    public static final f Ab;
    public static final f B7;
    public static final f B8;
    public static final f B9;
    public static final f Ba;
    public static final f Bb;
    public static final f C7;
    public static final f C8;
    public static final f C9;
    public static final f Ca;
    public static final f Cb;
    public static final f D7;
    public static final f D8;
    public static final f D9;
    public static final f Da;
    public static final f Db;
    public static final f E7;
    public static final f E8;
    public static final f E9;
    public static final f Ea;
    public static final f Eb;
    public static final f F7;
    public static final f F8;
    public static final f F9;
    public static final f Fa;
    public static final f Fb;
    public static final f G7;
    public static final f G8;
    public static final f G9;
    public static final f Ga;
    public static final f Gb;
    public static final f H7;
    public static final f H8;
    public static final f H9;
    public static final f Ha;
    public static final f Hb;
    public static final f I7;
    public static final f I8;
    public static final f I9;
    public static final f Ia;
    public static final f Ib;
    public static final f J7;
    public static final f J8;
    public static final f J9;
    public static final f Ja;
    public static final f Jb;
    public static final f K7;
    public static final f K8;
    public static final f K9;
    public static final f Ka;
    public static final f Kb;
    public static final f L7;
    public static final f L8;
    public static final f L9;
    public static final f La;
    public static final f Lb;
    public static final f M7;
    public static final f M8;
    public static final f M9;
    public static final f Ma;
    public static final f Mb;
    public static final f N7;
    public static final f N8;
    public static final f N9;
    public static final f Na;
    public static final f Nb;
    public static final f O7;
    public static final f O8;
    public static final f O9;
    public static final f Oa;
    public static final f Ob;
    public static final f P7;
    public static final f P8;
    public static final f P9;
    public static final f Pa;
    public static final f Pb;
    public static final f Q7;
    public static final f Q8;
    public static final f Q9;
    public static final f Qa;
    public static final f Qb;
    public static final f R7;
    public static final f R8;
    public static final f R9;
    public static final f Ra;
    public static final f S7;
    public static final f S8;
    public static final f S9;
    public static final f Sa;
    public static final f T6;
    public static final f T7;
    public static final f T8;
    public static final f T9;
    public static final f Ta;
    public static final f U6;
    public static final f U7;
    public static final f U8;
    public static final f U9;
    public static final f Ua;
    public static final f V6;
    public static final f V7;
    public static final f V8;
    public static final f V9;
    public static final f Va;
    public static final f W6;
    public static final f W7;
    public static final f W8;
    public static final f W9;
    public static final f Wa;
    public static final f X6;
    public static final f X7;
    public static final f X8;
    public static final f X9;
    public static final f Xa;
    public static final f Y6;
    public static final f Y7;
    public static final f Y8;
    public static final f Y9;
    public static final f Ya;
    public static final f Z6;
    public static final f Z7;
    public static final f Z8;
    public static final f Z9;
    public static final f Za;
    public static final f a7;
    public static final f a8;
    public static final f a9;
    public static final f aa;
    public static final f ab;
    public static final f b7;
    public static final f b8;
    public static final f b9;
    public static final f ba;
    public static final f bb;
    public static final f c7;
    public static final f c8;
    public static final f c9;
    public static final f ca;
    public static final f cb;
    public static final f d7;
    public static final f d8;
    public static final f d9;
    public static final f da;
    public static final f db;
    public static final f e7;
    public static final f e8;
    public static final f e9;
    public static final f ea;
    public static final f eb;
    public static final f f7;
    public static final f f8;
    public static final f f9;
    public static final f fa;
    public static final f fb;
    public static final f g7;
    public static final f g8;
    public static final f g9;
    public static final f ga;
    public static final f gb;
    public static final f h7;
    public static final f h8;
    public static final f h9;
    public static final f ha;
    public static final f hb;
    public static final f i7;
    public static final f i8;
    public static final f i9;
    public static final f ia;
    public static final f ib;
    public static final f j7;
    public static final f j8;
    public static final f j9;
    public static final f ja;
    public static final f jb;
    public static final f k7;
    public static final f k8;
    public static final f k9;
    public static final f ka;
    public static final f kb;
    public static final f l7;
    public static final f l8;
    public static final f l9;
    public static final f la;
    public static final f lb;
    public static final f m7;
    public static final f m8;
    public static final f m9;
    public static final f ma;
    public static final f mb;
    public static final f n7;
    public static final f n8;
    public static final f n9;
    public static final f na;
    public static final f nb;
    public static final f o7;
    public static final f o8;
    public static final f o9;
    public static final f oa;
    public static final f ob;
    public static final f p7;
    public static final f p8;
    public static final f p9;
    public static final f pa;
    public static final f pb;
    public static final f q7;
    public static final f q8;
    public static final f q9;
    public static final f qa;
    public static final f qb;
    public static final f r7;
    public static final f r8;
    public static final f r9;
    public static final f ra;
    public static final f rb;
    public static final f s7;
    public static final f s8;
    public static final f s9;
    public static final f sa;
    public static final f sb;
    public static final f t7;
    public static final f t8;
    public static final f t9;
    public static final f ta;
    public static final f tb;
    public static final f u7;
    public static final f u8;
    public static final f u9;
    public static final f ua;
    public static final f ub;
    public static final f v7;
    public static final f v8;
    public static final f v9;
    public static final f va;
    public static final f vb;
    public static final f w7;
    public static final f w8;
    public static final f w9;
    public static final f wa;
    public static final f wb;
    public static final f x7;
    public static final f x8;
    public static final f x9;
    public static final f xa;
    public static final f xb;
    public static final f y7;
    public static final f y8;
    public static final f y9;
    public static final f ya;
    public static final f yb;
    public static final f z7;
    public static final f z8;
    public static final f z9;
    public static final f za;
    public static final f zb;

    static {
        w.T6 = new f("\uD83C\uDDE6\uD83C\uDDE8", "\uD83C\uDDE6\uD83C\uDDE8", Collections.singletonList(":flag_ac:"), Collections.singletonList(":flag-ac:"), Collections.singletonList(":ascension_island:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Ascension Island", d0.e, q1.s);
        List list0 = Collections.singletonList(":flag_ad:");
        List list1 = Collections.singletonList(":flag-ad:");
        List list2 = Collections.singletonList(":andorra:");
        M1 m10 = M1.a("fully-qualified");
        d0 d00 = d0.e;
        q1 q10 = q1.s;
        w.U6 = new f("\uD83C\uDDE6\uD83C\uDDE9", "\uD83C\uDDE6\uD83C\uDDE9", list0, list1, list2, false, false, 2.0, m10, "flag: Andorra", d00, q10);
        w.V6 = new f("\uD83C\uDDE6\uD83C\uDDEA", "\uD83C\uDDE6\uD83C\uDDEA", Collections.singletonList(":flag_ae:"), Collections.singletonList(":flag-ae:"), Collections.singletonList(":united_arab_emirates:"), false, false, 2.0, M1.a("fully-qualified"), "flag: United Arab Emirates", d00, q10);
        w.W6 = new f("\uD83C\uDDE6\uD83C\uDDEB", "\uD83C\uDDE6\uD83C\uDDEB", Collections.singletonList(":flag_af:"), Collections.singletonList(":flag-af:"), Collections.singletonList(":afghanistan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Afghanistan", d00, q10);
        w.X6 = new f("\uD83C\uDDE6\uD83C\uDDEC", "\uD83C\uDDE6\uD83C\uDDEC", Collections.singletonList(":flag_ag:"), Collections.singletonList(":flag-ag:"), Collections.singletonList(":antigua_barbuda:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Antigua & Barbuda", d00, q10);
        w.Y6 = new f("\uD83C\uDDE6\uD83C\uDDEE", "\uD83C\uDDE6\uD83C\uDDEE", Collections.singletonList(":flag_ai:"), Collections.singletonList(":flag-ai:"), Collections.singletonList(":anguilla:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Anguilla", d00, q10);
        w.Z6 = new f("\uD83C\uDDE6\uD83C\uDDF1", "\uD83C\uDDE6\uD83C\uDDF1", Collections.singletonList(":flag_al:"), Collections.singletonList(":flag-al:"), Collections.singletonList(":albania:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Albania", d00, q10);
        w.a7 = new f("\uD83C\uDDE6\uD83C\uDDF2", "\uD83C\uDDE6\uD83C\uDDF2", Collections.singletonList(":flag_am:"), Collections.singletonList(":flag-am:"), Collections.singletonList(":armenia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Armenia", d00, q10);
        w.b7 = new f("\uD83C\uDDE6\uD83C\uDDF4", "\uD83C\uDDE6\uD83C\uDDF4", Collections.singletonList(":flag_ao:"), Collections.singletonList(":flag-ao:"), Collections.singletonList(":angola:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Angola", d00, q10);
        w.c7 = new f("\uD83C\uDDE6\uD83C\uDDF6", "\uD83C\uDDE6\uD83C\uDDF6", Collections.singletonList(":flag_aq:"), Collections.singletonList(":flag-aq:"), Collections.singletonList(":antarctica:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Antarctica", d00, q10);
        w.d7 = new f("\uD83C\uDDE6\uD83C\uDDF7", "\uD83C\uDDE6\uD83C\uDDF7", Collections.singletonList(":flag_ar:"), Collections.singletonList(":flag-ar:"), Collections.singletonList(":argentina:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Argentina", d00, q10);
        w.e7 = new f("\uD83C\uDDE6\uD83C\uDDF8", "\uD83C\uDDE6\uD83C\uDDF8", Collections.singletonList(":flag_as:"), Collections.singletonList(":flag-as:"), Collections.singletonList(":american_samoa:"), false, false, 2.0, M1.a("fully-qualified"), "flag: American Samoa", d00, q10);
        w.f7 = new f("\uD83C\uDDE6\uD83C\uDDF9", "\uD83C\uDDE6\uD83C\uDDF9", Collections.singletonList(":flag_at:"), Collections.singletonList(":flag-at:"), Collections.singletonList(":austria:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Austria", d00, q10);
        w.g7 = new f("\uD83C\uDDE6\uD83C\uDDFA", "\uD83C\uDDE6\uD83C\uDDFA", Collections.singletonList(":flag_au:"), Collections.singletonList(":flag-au:"), Collections.singletonList(":australia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Australia", d00, q10);
        w.h7 = new f("\uD83C\uDDE6\uD83C\uDDFC", "\uD83C\uDDE6\uD83C\uDDFC", Collections.singletonList(":flag_aw:"), Collections.singletonList(":flag-aw:"), Collections.singletonList(":aruba:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Aruba", d00, q10);
        w.i7 = new f("\uD83C\uDDE6\uD83C\uDDFD", "\uD83C\uDDE6\uD83C\uDDFD", Collections.singletonList(":flag_ax:"), Collections.singletonList(":flag-ax:"), Collections.singletonList(":aland_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Åland Islands", d00, q10);
        w.j7 = new f("\uD83C\uDDE6\uD83C\uDDFF", "\uD83C\uDDE6\uD83C\uDDFF", Collections.singletonList(":flag_az:"), Collections.singletonList(":flag-az:"), Collections.singletonList(":azerbaijan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Azerbaijan", d00, q10);
        w.k7 = new f("\uD83C\uDDE7\uD83C\uDDE6", "\uD83C\uDDE7\uD83C\uDDE6", Collections.singletonList(":flag_ba:"), Collections.singletonList(":flag-ba:"), Collections.singletonList(":bosnia_herzegovina:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bosnia & Herzegovina", d00, q10);
        w.l7 = new f("\uD83C\uDDE7\uD83C\uDDE7", "\uD83C\uDDE7\uD83C\uDDE7", Collections.singletonList(":flag_bb:"), Collections.singletonList(":flag-bb:"), Collections.singletonList(":barbados:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Barbados", d00, q10);
        w.m7 = new f("\uD83C\uDDE7\uD83C\uDDE9", "\uD83C\uDDE7\uD83C\uDDE9", Collections.singletonList(":flag_bd:"), Collections.singletonList(":flag-bd:"), Collections.singletonList(":bangladesh:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bangladesh", d00, q10);
        w.n7 = new f("\uD83C\uDDE7\uD83C\uDDEA", "\uD83C\uDDE7\uD83C\uDDEA", Collections.singletonList(":flag_be:"), Collections.singletonList(":flag-be:"), Collections.singletonList(":belgium:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Belgium", d00, q10);
        w.o7 = new f("\uD83C\uDDE7\uD83C\uDDEB", "\uD83C\uDDE7\uD83C\uDDEB", Collections.singletonList(":flag_bf:"), Collections.singletonList(":flag-bf:"), Collections.singletonList(":burkina_faso:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Burkina Faso", d00, q10);
        w.p7 = new f("\uD83C\uDDE7\uD83C\uDDEC", "\uD83C\uDDE7\uD83C\uDDEC", Collections.singletonList(":flag_bg:"), Collections.singletonList(":flag-bg:"), Collections.singletonList(":bulgaria:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bulgaria", d00, q10);
        w.q7 = new f("\uD83C\uDDE7\uD83C\uDDED", "\uD83C\uDDE7\uD83C\uDDED", Collections.singletonList(":flag_bh:"), Collections.singletonList(":flag-bh:"), Collections.singletonList(":bahrain:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bahrain", d00, q10);
        w.r7 = new f("\uD83C\uDDE7\uD83C\uDDEE", "\uD83C\uDDE7\uD83C\uDDEE", Collections.singletonList(":flag_bi:"), Collections.singletonList(":flag-bi:"), Collections.singletonList(":burundi:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Burundi", d00, q10);
        w.s7 = new f("\uD83C\uDDE7\uD83C\uDDEF", "\uD83C\uDDE7\uD83C\uDDEF", Collections.singletonList(":flag_bj:"), Collections.singletonList(":flag-bj:"), Collections.singletonList(":benin:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Benin", d00, q10);
        w.t7 = new f("\uD83C\uDDE7\uD83C\uDDF1", "\uD83C\uDDE7\uD83C\uDDF1", Collections.singletonList(":flag_bl:"), Collections.singletonList(":flag-bl:"), Collections.singletonList(":st_barthelemy:"), false, false, 2.0, M1.a("fully-qualified"), "flag: St. Barthélemy", d00, q10);
        w.u7 = new f("\uD83C\uDDE7\uD83C\uDDF2", "\uD83C\uDDE7\uD83C\uDDF2", Collections.singletonList(":flag_bm:"), Collections.singletonList(":flag-bm:"), Collections.singletonList(":bermuda:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bermuda", d00, q10);
        w.v7 = new f("\uD83C\uDDE7\uD83C\uDDF3", "\uD83C\uDDE7\uD83C\uDDF3", Collections.singletonList(":flag_bn:"), Collections.singletonList(":flag-bn:"), Collections.singletonList(":brunei:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Brunei", d00, q10);
        w.w7 = new f("\uD83C\uDDE7\uD83C\uDDF4", "\uD83C\uDDE7\uD83C\uDDF4", Collections.singletonList(":flag_bo:"), Collections.singletonList(":flag-bo:"), Collections.singletonList(":bolivia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bolivia", d00, q10);
        w.x7 = new f("\uD83C\uDDE7\uD83C\uDDF6", "\uD83C\uDDE7\uD83C\uDDF6", Collections.singletonList(":flag_bq:"), Collections.singletonList(":flag-bq:"), Collections.singletonList(":caribbean_netherlands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Caribbean Netherlands", d00, q10);
        w.y7 = new f("\uD83C\uDDE7\uD83C\uDDF7", "\uD83C\uDDE7\uD83C\uDDF7", Collections.singletonList(":flag_br:"), Collections.singletonList(":flag-br:"), Collections.singletonList(":brazil:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Brazil", d00, q10);
        w.z7 = new f("\uD83C\uDDE7\uD83C\uDDF8", "\uD83C\uDDE7\uD83C\uDDF8", Collections.singletonList(":flag_bs:"), Collections.singletonList(":flag-bs:"), Collections.singletonList(":bahamas:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bahamas", d00, q10);
        w.A7 = new f("\uD83C\uDDE7\uD83C\uDDF9", "\uD83C\uDDE7\uD83C\uDDF9", Collections.singletonList(":flag_bt:"), Collections.singletonList(":flag-bt:"), Collections.singletonList(":bhutan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bhutan", d00, q10);
        w.B7 = new f("\uD83C\uDDE7\uD83C\uDDFB", "\uD83C\uDDE7\uD83C\uDDFB", Collections.singletonList(":flag_bv:"), Collections.singletonList(":flag-bv:"), Collections.singletonList(":bouvet_island:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Bouvet Island", d00, q10);
        w.C7 = new f("\uD83C\uDDE7\uD83C\uDDFC", "\uD83C\uDDE7\uD83C\uDDFC", Collections.singletonList(":flag_bw:"), Collections.singletonList(":flag-bw:"), Collections.singletonList(":botswana:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Botswana", d00, q10);
        w.D7 = new f("\uD83C\uDDE7\uD83C\uDDFE", "\uD83C\uDDE7\uD83C\uDDFE", Collections.singletonList(":flag_by:"), Collections.singletonList(":flag-by:"), Collections.singletonList(":belarus:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Belarus", d00, q10);
        w.E7 = new f("\uD83C\uDDE7\uD83C\uDDFF", "\uD83C\uDDE7\uD83C\uDDFF", Collections.singletonList(":flag_bz:"), Collections.singletonList(":flag-bz:"), Collections.singletonList(":belize:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Belize", d00, q10);
        w.F7 = new f("\uD83C\uDDE8\uD83C\uDDE6", "\uD83C\uDDE8\uD83C\uDDE6", Collections.singletonList(":flag_ca:"), Collections.singletonList(":flag-ca:"), Collections.singletonList(":canada:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Canada", d00, q10);
        w.G7 = new f("\uD83C\uDDE8\uD83C\uDDE8", "\uD83C\uDDE8\uD83C\uDDE8", Collections.singletonList(":flag_cc:"), Collections.singletonList(":flag-cc:"), Collections.singletonList(":cocos_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cocos (Keeling) Islands", d00, q10);
        w.H7 = new f("\uD83C\uDDE8\uD83C\uDDE9", "\uD83C\uDDE8\uD83C\uDDE9", Collections.singletonList(":flag_cd:"), Collections.singletonList(":flag-cd:"), Collections.singletonList(":congo_kinshasa:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Congo - Kinshasa", d00, q10);
        w.I7 = new f("\uD83C\uDDE8\uD83C\uDDEB", "\uD83C\uDDE8\uD83C\uDDEB", Collections.singletonList(":flag_cf:"), Collections.singletonList(":flag-cf:"), Collections.singletonList(":central_african_republic:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Central African Republic", d00, q10);
        w.J7 = new f("\uD83C\uDDE8\uD83C\uDDEC", "\uD83C\uDDE8\uD83C\uDDEC", Collections.singletonList(":flag_cg:"), Collections.singletonList(":flag-cg:"), Collections.singletonList(":congo_brazzaville:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Congo - Brazzaville", d00, q10);
        w.K7 = new f("\uD83C\uDDE8\uD83C\uDDED", "\uD83C\uDDE8\uD83C\uDDED", Collections.singletonList(":flag_ch:"), Collections.singletonList(":flag-ch:"), Collections.singletonList(":switzerland:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Switzerland", d00, q10);
        w.L7 = new f("\uD83C\uDDE8\uD83C\uDDEE", "\uD83C\uDDE8\uD83C\uDDEE", Collections.singletonList(":flag_ci:"), Collections.singletonList(":flag-ci:"), Collections.singletonList(":cote_divoire:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Côte d’Ivoire", d00, q10);
        w.M7 = new f("\uD83C\uDDE8\uD83C\uDDF0", "\uD83C\uDDE8\uD83C\uDDF0", Collections.singletonList(":flag_ck:"), Collections.singletonList(":flag-ck:"), Collections.singletonList(":cook_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cook Islands", d00, q10);
        w.N7 = new f("\uD83C\uDDE8\uD83C\uDDF1", "\uD83C\uDDE8\uD83C\uDDF1", Collections.singletonList(":flag_cl:"), Collections.singletonList(":flag-cl:"), Collections.singletonList(":chile:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Chile", d00, q10);
        w.O7 = new f("\uD83C\uDDE8\uD83C\uDDF2", "\uD83C\uDDE8\uD83C\uDDF2", Collections.singletonList(":flag_cm:"), Collections.singletonList(":flag-cm:"), Collections.singletonList(":cameroon:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cameroon", d00, q10);
        w.P7 = new f("\uD83C\uDDE8\uD83C\uDDF3", "\uD83C\uDDE8\uD83C\uDDF3", Collections.singletonList(":flag_cn:"), Collections.singletonList(":cn:"), Collections.singletonList(":cn:"), false, false, 0.6, M1.a("fully-qualified"), "flag: China", d00, q10);
        w.Q7 = new f("\uD83C\uDDE8\uD83C\uDDF4", "\uD83C\uDDE8\uD83C\uDDF4", Collections.singletonList(":flag_co:"), Collections.singletonList(":flag-co:"), Collections.singletonList(":colombia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Colombia", d00, q10);
        w.R7 = new f("\uD83C\uDDE8\uD83C\uDDF5", "\uD83C\uDDE8\uD83C\uDDF5", Collections.singletonList(":flag_cp:"), Collections.singletonList(":flag-cp:"), Collections.singletonList(":clipperton_island:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Clipperton Island", d00, q10);
        w.S7 = new f("\uD83C\uDDE8\uD83C\uDDF7", "\uD83C\uDDE8\uD83C\uDDF7", Collections.singletonList(":flag_cr:"), Collections.singletonList(":flag-cr:"), Collections.singletonList(":costa_rica:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Costa Rica", d00, q10);
        w.T7 = new f("\uD83C\uDDE8\uD83C\uDDFA", "\uD83C\uDDE8\uD83C\uDDFA", Collections.singletonList(":flag_cu:"), Collections.singletonList(":flag-cu:"), Collections.singletonList(":cuba:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cuba", d00, q10);
        w.U7 = new f("\uD83C\uDDE8\uD83C\uDDFB", "\uD83C\uDDE8\uD83C\uDDFB", Collections.singletonList(":flag_cv:"), Collections.singletonList(":flag-cv:"), Collections.singletonList(":cape_verde:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cape Verde", d00, q10);
        w.V7 = new f("\uD83C\uDDE8\uD83C\uDDFC", "\uD83C\uDDE8\uD83C\uDDFC", Collections.singletonList(":flag_cw:"), Collections.singletonList(":flag-cw:"), Collections.singletonList(":curacao:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Curaçao", d00, q10);
        w.W7 = new f("\uD83C\uDDE8\uD83C\uDDFD", "\uD83C\uDDE8\uD83C\uDDFD", Collections.singletonList(":flag_cx:"), Collections.singletonList(":flag-cx:"), Collections.singletonList(":christmas_island:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Christmas Island", d00, q10);
        w.X7 = new f("\uD83C\uDDE8\uD83C\uDDFE", "\uD83C\uDDE8\uD83C\uDDFE", Collections.singletonList(":flag_cy:"), Collections.singletonList(":flag-cy:"), Collections.singletonList(":cyprus:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cyprus", d00, q10);
        w.Y7 = new f("\uD83C\uDDE8\uD83C\uDDFF", "\uD83C\uDDE8\uD83C\uDDFF", Collections.singletonList(":flag_cz:"), Collections.singletonList(":flag-cz:"), Collections.singletonList(":czech_republic:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Czechia", d00, q10);
        w.Z7 = new f("\uD83C\uDDE9\uD83C\uDDEA", "\uD83C\uDDE9\uD83C\uDDEA", Collections.singletonList(":flag_de:"), Collections.singletonList(":de:"), Collections.singletonList(":de:"), false, false, 0.6, M1.a("fully-qualified"), "flag: Germany", d00, q10);
        w.a8 = new f("\uD83C\uDDE9\uD83C\uDDEC", "\uD83C\uDDE9\uD83C\uDDEC", Collections.singletonList(":flag_dg:"), Collections.singletonList(":flag-dg:"), Collections.singletonList(":diego_garcia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Diego Garcia", d00, q10);
        w.b8 = new f("\uD83C\uDDE9\uD83C\uDDEF", "\uD83C\uDDE9\uD83C\uDDEF", Collections.singletonList(":flag_dj:"), Collections.singletonList(":flag-dj:"), Collections.singletonList(":djibouti:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Djibouti", d00, q10);
        w.c8 = new f("\uD83C\uDDE9\uD83C\uDDF0", "\uD83C\uDDE9\uD83C\uDDF0", Collections.singletonList(":flag_dk:"), Collections.singletonList(":flag-dk:"), Collections.singletonList(":denmark:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Denmark", d00, q10);
        w.d8 = new f("\uD83C\uDDE9\uD83C\uDDF2", "\uD83C\uDDE9\uD83C\uDDF2", Collections.singletonList(":flag_dm:"), Collections.singletonList(":flag-dm:"), Collections.singletonList(":dominica:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Dominica", d00, q10);
        w.e8 = new f("\uD83C\uDDE9\uD83C\uDDF4", "\uD83C\uDDE9\uD83C\uDDF4", Collections.singletonList(":flag_do:"), Collections.singletonList(":flag-do:"), Collections.singletonList(":dominican_republic:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Dominican Republic", d00, q10);
        w.f8 = new f("\uD83C\uDDE9\uD83C\uDDFF", "\uD83C\uDDE9\uD83C\uDDFF", Collections.singletonList(":flag_dz:"), Collections.singletonList(":flag-dz:"), Collections.singletonList(":algeria:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Algeria", d00, q10);
        w.g8 = new f("\uD83C\uDDEA\uD83C\uDDE6", "\uD83C\uDDEA\uD83C\uDDE6", Collections.singletonList(":flag_ea:"), Collections.singletonList(":flag-ea:"), Collections.singletonList(":ceuta_melilla:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Ceuta & Melilla", d00, q10);
        w.h8 = new f("\uD83C\uDDEA\uD83C\uDDE8", "\uD83C\uDDEA\uD83C\uDDE8", Collections.singletonList(":flag_ec:"), Collections.singletonList(":flag-ec:"), Collections.singletonList(":ecuador:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Ecuador", d00, q10);
        w.i8 = new f("\uD83C\uDDEA\uD83C\uDDEA", "\uD83C\uDDEA\uD83C\uDDEA", Collections.singletonList(":flag_ee:"), Collections.singletonList(":flag-ee:"), Collections.singletonList(":estonia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Estonia", d00, q10);
        w.j8 = new f("\uD83C\uDDEA\uD83C\uDDEC", "\uD83C\uDDEA\uD83C\uDDEC", Collections.singletonList(":flag_eg:"), Collections.singletonList(":flag-eg:"), Collections.singletonList(":egypt:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Egypt", d00, q10);
        w.k8 = new f("\uD83C\uDDEA\uD83C\uDDED", "\uD83C\uDDEA\uD83C\uDDED", Collections.singletonList(":flag_eh:"), Collections.singletonList(":flag-eh:"), Collections.singletonList(":western_sahara:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Western Sahara", d00, q10);
        w.l8 = new f("\uD83C\uDDEA\uD83C\uDDF7", "\uD83C\uDDEA\uD83C\uDDF7", Collections.singletonList(":flag_er:"), Collections.singletonList(":flag-er:"), Collections.singletonList(":eritrea:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Eritrea", d00, q10);
        w.m8 = new f("\uD83C\uDDEA\uD83C\uDDF8", "\uD83C\uDDEA\uD83C\uDDF8", Collections.singletonList(":flag_es:"), Collections.singletonList(":es:"), Collections.singletonList(":es:"), false, false, 0.6, M1.a("fully-qualified"), "flag: Spain", d00, q10);
        w.n8 = new f("\uD83C\uDDEA\uD83C\uDDF9", "\uD83C\uDDEA\uD83C\uDDF9", Collections.singletonList(":flag_et:"), Collections.singletonList(":flag-et:"), Collections.singletonList(":ethiopia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Ethiopia", d00, q10);
        w.o8 = new f("\uD83C\uDDEA\uD83C\uDDFA", "\uD83C\uDDEA\uD83C\uDDFA", Collections.singletonList(":flag_eu:"), Collections.singletonList(":flag-eu:"), DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":eu:", ":european_union:"})), false, false, 2.0, M1.a("fully-qualified"), "flag: European Union", d00, q10);
        w.p8 = new f("\uD83C\uDDEB\uD83C\uDDEE", "\uD83C\uDDEB\uD83C\uDDEE", Collections.singletonList(":flag_fi:"), Collections.singletonList(":flag-fi:"), Collections.singletonList(":finland:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Finland", d00, q10);
        w.q8 = new f("\uD83C\uDDEB\uD83C\uDDEF", "\uD83C\uDDEB\uD83C\uDDEF", Collections.singletonList(":flag_fj:"), Collections.singletonList(":flag-fj:"), Collections.singletonList(":fiji:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Fiji", d00, q10);
        w.r8 = new f("\uD83C\uDDEB\uD83C\uDDF0", "\uD83C\uDDEB\uD83C\uDDF0", Collections.singletonList(":flag_fk:"), Collections.singletonList(":flag-fk:"), Collections.singletonList(":falkland_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Falkland Islands", d00, q10);
        w.s8 = new f("\uD83C\uDDEB\uD83C\uDDF2", "\uD83C\uDDEB\uD83C\uDDF2", Collections.singletonList(":flag_fm:"), Collections.singletonList(":flag-fm:"), Collections.singletonList(":micronesia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Micronesia", d00, q10);
        w.t8 = new f("\uD83C\uDDEB\uD83C\uDDF4", "\uD83C\uDDEB\uD83C\uDDF4", Collections.singletonList(":flag_fo:"), Collections.singletonList(":flag-fo:"), Collections.singletonList(":faroe_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Faroe Islands", d00, q10);
        w.u8 = new f("\uD83C\uDDEB\uD83C\uDDF7", "\uD83C\uDDEB\uD83C\uDDF7", Collections.singletonList(":flag_fr:"), Collections.singletonList(":fr:"), Collections.singletonList(":fr:"), false, false, 0.6, M1.a("fully-qualified"), "flag: France", d00, q10);
        w.v8 = new f("\uD83C\uDDEC\uD83C\uDDE6", "\uD83C\uDDEC\uD83C\uDDE6", Collections.singletonList(":flag_ga:"), Collections.singletonList(":flag-ga:"), Collections.singletonList(":gabon:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Gabon", d00, q10);
        w.w8 = new f("\uD83C\uDDEC\uD83C\uDDE7", "\uD83C\uDDEC\uD83C\uDDE7", Collections.singletonList(":flag_gb:"), Collections.singletonList(":gb:"), DesugarCollections.unmodifiableList(Arrays.asList(new String[]{":gb:", ":uk:"})), false, false, 0.6, M1.a("fully-qualified"), "flag: United Kingdom", d00, q10);
        w.x8 = new f("\uD83C\uDDEC\uD83C\uDDE9", "\uD83C\uDDEC\uD83C\uDDE9", Collections.singletonList(":flag_gd:"), Collections.singletonList(":flag-gd:"), Collections.singletonList(":grenada:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Grenada", d00, q10);
        w.y8 = new f("\uD83C\uDDEC\uD83C\uDDEA", "\uD83C\uDDEC\uD83C\uDDEA", Collections.singletonList(":flag_ge:"), Collections.singletonList(":flag-ge:"), Collections.singletonList(":georgia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Georgia", d00, q10);
        w.z8 = new f("\uD83C\uDDEC\uD83C\uDDEB", "\uD83C\uDDEC\uD83C\uDDEB", Collections.singletonList(":flag_gf:"), Collections.singletonList(":flag-gf:"), Collections.singletonList(":french_guiana:"), false, false, 2.0, M1.a("fully-qualified"), "flag: French Guiana", d00, q10);
        w.A8 = new f("\uD83C\uDDEC\uD83C\uDDEC", "\uD83C\uDDEC\uD83C\uDDEC", Collections.singletonList(":flag_gg:"), Collections.singletonList(":flag-gg:"), Collections.singletonList(":guernsey:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Guernsey", d00, q10);
        w.B8 = new f("\uD83C\uDDEC\uD83C\uDDED", "\uD83C\uDDEC\uD83C\uDDED", Collections.singletonList(":flag_gh:"), Collections.singletonList(":flag-gh:"), Collections.singletonList(":ghana:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Ghana", d00, q10);
        w.C8 = new f("\uD83C\uDDEC\uD83C\uDDEE", "\uD83C\uDDEC\uD83C\uDDEE", Collections.singletonList(":flag_gi:"), Collections.singletonList(":flag-gi:"), Collections.singletonList(":gibraltar:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Gibraltar", d00, q10);
        w.D8 = new f("\uD83C\uDDEC\uD83C\uDDF1", "\uD83C\uDDEC\uD83C\uDDF1", Collections.singletonList(":flag_gl:"), Collections.singletonList(":flag-gl:"), Collections.singletonList(":greenland:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Greenland", d00, q10);
        w.E8 = new f("\uD83C\uDDEC\uD83C\uDDF2", "\uD83C\uDDEC\uD83C\uDDF2", Collections.singletonList(":flag_gm:"), Collections.singletonList(":flag-gm:"), Collections.singletonList(":gambia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Gambia", d00, q10);
        w.F8 = new f("\uD83C\uDDEC\uD83C\uDDF3", "\uD83C\uDDEC\uD83C\uDDF3", Collections.singletonList(":flag_gn:"), Collections.singletonList(":flag-gn:"), Collections.singletonList(":guinea:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Guinea", d00, q10);
        w.G8 = new f("\uD83C\uDDEC\uD83C\uDDF5", "\uD83C\uDDEC\uD83C\uDDF5", Collections.singletonList(":flag_gp:"), Collections.singletonList(":flag-gp:"), Collections.singletonList(":guadeloupe:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Guadeloupe", d00, q10);
        w.H8 = new f("\uD83C\uDDEC\uD83C\uDDF6", "\uD83C\uDDEC\uD83C\uDDF6", Collections.singletonList(":flag_gq:"), Collections.singletonList(":flag-gq:"), Collections.singletonList(":equatorial_guinea:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Equatorial Guinea", d00, q10);
        w.I8 = new f("\uD83C\uDDEC\uD83C\uDDF7", "\uD83C\uDDEC\uD83C\uDDF7", Collections.singletonList(":flag_gr:"), Collections.singletonList(":flag-gr:"), Collections.singletonList(":greece:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Greece", d00, q10);
        w.J8 = new f("\uD83C\uDDEC\uD83C\uDDF8", "\uD83C\uDDEC\uD83C\uDDF8", Collections.singletonList(":flag_gs:"), Collections.singletonList(":flag-gs:"), Collections.singletonList(":south_georgia_south_sandwich_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: South Georgia & South Sandwich Islands", d00, q10);
        w.K8 = new f("\uD83C\uDDEC\uD83C\uDDF9", "\uD83C\uDDEC\uD83C\uDDF9", Collections.singletonList(":flag_gt:"), Collections.singletonList(":flag-gt:"), Collections.singletonList(":guatemala:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Guatemala", d00, q10);
        w.L8 = new f("\uD83C\uDDEC\uD83C\uDDFA", "\uD83C\uDDEC\uD83C\uDDFA", Collections.singletonList(":flag_gu:"), Collections.singletonList(":flag-gu:"), Collections.singletonList(":guam:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Guam", d00, q10);
        w.M8 = new f("\uD83C\uDDEC\uD83C\uDDFC", "\uD83C\uDDEC\uD83C\uDDFC", Collections.singletonList(":flag_gw:"), Collections.singletonList(":flag-gw:"), Collections.singletonList(":guinea_bissau:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Guinea-Bissau", d00, q10);
        w.N8 = new f("\uD83C\uDDEC\uD83C\uDDFE", "\uD83C\uDDEC\uD83C\uDDFE", Collections.singletonList(":flag_gy:"), Collections.singletonList(":flag-gy:"), Collections.singletonList(":guyana:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Guyana", d00, q10);
        w.O8 = new f("\uD83C\uDDED\uD83C\uDDF0", "\uD83C\uDDED\uD83C\uDDF0", Collections.singletonList(":flag_hk:"), Collections.singletonList(":flag-hk:"), Collections.singletonList(":hong_kong:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Hong Kong SAR China", d00, q10);
        w.P8 = new f("\uD83C\uDDED\uD83C\uDDF2", "\uD83C\uDDED\uD83C\uDDF2", Collections.singletonList(":flag_hm:"), Collections.singletonList(":flag-hm:"), Collections.singletonList(":heard_mcdonald_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Heard & McDonald Islands", d00, q10);
        w.Q8 = new f("\uD83C\uDDED\uD83C\uDDF3", "\uD83C\uDDED\uD83C\uDDF3", Collections.singletonList(":flag_hn:"), Collections.singletonList(":flag-hn:"), Collections.singletonList(":honduras:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Honduras", d00, q10);
        w.R8 = new f("\uD83C\uDDED\uD83C\uDDF7", "\uD83C\uDDED\uD83C\uDDF7", Collections.singletonList(":flag_hr:"), Collections.singletonList(":flag-hr:"), Collections.singletonList(":croatia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Croatia", d00, q10);
        w.S8 = new f("\uD83C\uDDED\uD83C\uDDF9", "\uD83C\uDDED\uD83C\uDDF9", Collections.singletonList(":flag_ht:"), Collections.singletonList(":flag-ht:"), Collections.singletonList(":haiti:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Haiti", d00, q10);
        w.T8 = new f("\uD83C\uDDED\uD83C\uDDFA", "\uD83C\uDDED\uD83C\uDDFA", Collections.singletonList(":flag_hu:"), Collections.singletonList(":flag-hu:"), Collections.singletonList(":hungary:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Hungary", d00, q10);
        w.U8 = new f("\uD83C\uDDEE\uD83C\uDDE8", "\uD83C\uDDEE\uD83C\uDDE8", Collections.singletonList(":flag_ic:"), Collections.singletonList(":flag-ic:"), Collections.singletonList(":canary_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Canary Islands", d00, q10);
        w.V8 = new f("\uD83C\uDDEE\uD83C\uDDE9", "\uD83C\uDDEE\uD83C\uDDE9", Collections.singletonList(":flag_id:"), Collections.singletonList(":flag-id:"), Collections.singletonList(":indonesia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Indonesia", d00, q10);
        w.W8 = new f("\uD83C\uDDEE\uD83C\uDDEA", "\uD83C\uDDEE\uD83C\uDDEA", Collections.singletonList(":flag_ie:"), Collections.singletonList(":flag-ie:"), Collections.singletonList(":ireland:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Ireland", d00, q10);
        w.X8 = new f("\uD83C\uDDEE\uD83C\uDDF1", "\uD83C\uDDEE\uD83C\uDDF1", Collections.singletonList(":flag_il:"), Collections.singletonList(":flag-il:"), Collections.singletonList(":israel:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Israel", d00, q10);
        w.Y8 = new f("\uD83C\uDDEE\uD83C\uDDF2", "\uD83C\uDDEE\uD83C\uDDF2", Collections.singletonList(":flag_im:"), Collections.singletonList(":flag-im:"), Collections.singletonList(":isle_of_man:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Isle of Man", d00, q10);
        w.Z8 = new f("\uD83C\uDDEE\uD83C\uDDF3", "\uD83C\uDDEE\uD83C\uDDF3", Collections.singletonList(":flag_in:"), Collections.singletonList(":flag-in:"), Collections.singletonList(":india:"), false, false, 2.0, M1.a("fully-qualified"), "flag: India", d00, q10);
        w.a9 = new f("\uD83C\uDDEE\uD83C\uDDF4", "\uD83C\uDDEE\uD83C\uDDF4", Collections.singletonList(":flag_io:"), Collections.singletonList(":flag-io:"), Collections.singletonList(":british_indian_ocean_territory:"), false, false, 2.0, M1.a("fully-qualified"), "flag: British Indian Ocean Territory", d00, q10);
        w.b9 = new f("\uD83C\uDDEE\uD83C\uDDF6", "\uD83C\uDDEE\uD83C\uDDF6", Collections.singletonList(":flag_iq:"), Collections.singletonList(":flag-iq:"), Collections.singletonList(":iraq:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Iraq", d00, q10);
        w.c9 = new f("\uD83C\uDDEE\uD83C\uDDF7", "\uD83C\uDDEE\uD83C\uDDF7", Collections.singletonList(":flag_ir:"), Collections.singletonList(":flag-ir:"), Collections.singletonList(":iran:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Iran", d00, q10);
        w.d9 = new f("\uD83C\uDDEE\uD83C\uDDF8", "\uD83C\uDDEE\uD83C\uDDF8", Collections.singletonList(":flag_is:"), Collections.singletonList(":flag-is:"), Collections.singletonList(":iceland:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Iceland", d00, q10);
        w.e9 = new f("\uD83C\uDDEE\uD83C\uDDF9", "\uD83C\uDDEE\uD83C\uDDF9", Collections.singletonList(":flag_it:"), Collections.singletonList(":it:"), Collections.singletonList(":it:"), false, false, 0.6, M1.a("fully-qualified"), "flag: Italy", d00, q10);
        w.f9 = new f("\uD83C\uDDEF\uD83C\uDDEA", "\uD83C\uDDEF\uD83C\uDDEA", Collections.singletonList(":flag_je:"), Collections.singletonList(":flag-je:"), Collections.singletonList(":jersey:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Jersey", d00, q10);
        w.g9 = new f("\uD83C\uDDEF\uD83C\uDDF2", "\uD83C\uDDEF\uD83C\uDDF2", Collections.singletonList(":flag_jm:"), Collections.singletonList(":flag-jm:"), Collections.singletonList(":jamaica:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Jamaica", d00, q10);
        w.h9 = new f("\uD83C\uDDEF\uD83C\uDDF4", "\uD83C\uDDEF\uD83C\uDDF4", Collections.singletonList(":flag_jo:"), Collections.singletonList(":flag-jo:"), Collections.singletonList(":jordan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Jordan", d00, q10);
        w.i9 = new f("\uD83C\uDDEF\uD83C\uDDF5", "\uD83C\uDDEF\uD83C\uDDF5", Collections.singletonList(":flag_jp:"), Collections.singletonList(":jp:"), Collections.singletonList(":jp:"), false, false, 0.6, M1.a("fully-qualified"), "flag: Japan", d00, q10);
        w.j9 = new f("\uD83C\uDDF0\uD83C\uDDEA", "\uD83C\uDDF0\uD83C\uDDEA", Collections.singletonList(":flag_ke:"), Collections.singletonList(":flag-ke:"), Collections.singletonList(":kenya:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Kenya", d00, q10);
        w.k9 = new f("\uD83C\uDDF0\uD83C\uDDEC", "\uD83C\uDDF0\uD83C\uDDEC", Collections.singletonList(":flag_kg:"), Collections.singletonList(":flag-kg:"), Collections.singletonList(":kyrgyzstan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Kyrgyzstan", d00, q10);
        w.l9 = new f("\uD83C\uDDF0\uD83C\uDDED", "\uD83C\uDDF0\uD83C\uDDED", Collections.singletonList(":flag_kh:"), Collections.singletonList(":flag-kh:"), Collections.singletonList(":cambodia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cambodia", d00, q10);
        w.m9 = new f("\uD83C\uDDF0\uD83C\uDDEE", "\uD83C\uDDF0\uD83C\uDDEE", Collections.singletonList(":flag_ki:"), Collections.singletonList(":flag-ki:"), Collections.singletonList(":kiribati:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Kiribati", d00, q10);
        w.n9 = new f("\uD83C\uDDF0\uD83C\uDDF2", "\uD83C\uDDF0\uD83C\uDDF2", Collections.singletonList(":flag_km:"), Collections.singletonList(":flag-km:"), Collections.singletonList(":comoros:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Comoros", d00, q10);
        w.o9 = new f("\uD83C\uDDF0\uD83C\uDDF3", "\uD83C\uDDF0\uD83C\uDDF3", Collections.singletonList(":flag_kn:"), Collections.singletonList(":flag-kn:"), Collections.singletonList(":st_kitts_nevis:"), false, false, 2.0, M1.a("fully-qualified"), "flag: St. Kitts & Nevis", d00, q10);
        w.p9 = new f("\uD83C\uDDF0\uD83C\uDDF5", "\uD83C\uDDF0\uD83C\uDDF5", Collections.singletonList(":flag_kp:"), Collections.singletonList(":flag-kp:"), Collections.singletonList(":north_korea:"), false, false, 2.0, M1.a("fully-qualified"), "flag: North Korea", d00, q10);
        w.q9 = new f("\uD83C\uDDF0\uD83C\uDDF7", "\uD83C\uDDF0\uD83C\uDDF7", Collections.singletonList(":flag_kr:"), Collections.singletonList(":kr:"), Collections.singletonList(":kr:"), false, false, 0.6, M1.a("fully-qualified"), "flag: South Korea", d00, q10);
        w.r9 = new f("\uD83C\uDDF0\uD83C\uDDFC", "\uD83C\uDDF0\uD83C\uDDFC", Collections.singletonList(":flag_kw:"), Collections.singletonList(":flag-kw:"), Collections.singletonList(":kuwait:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Kuwait", d00, q10);
        w.s9 = new f("\uD83C\uDDF0\uD83C\uDDFE", "\uD83C\uDDF0\uD83C\uDDFE", Collections.singletonList(":flag_ky:"), Collections.singletonList(":flag-ky:"), Collections.singletonList(":cayman_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Cayman Islands", d00, q10);
        w.t9 = new f("\uD83C\uDDF0\uD83C\uDDFF", "\uD83C\uDDF0\uD83C\uDDFF", Collections.singletonList(":flag_kz:"), Collections.singletonList(":flag-kz:"), Collections.singletonList(":kazakhstan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Kazakhstan", d00, q10);
        w.u9 = new f("\uD83C\uDDF1\uD83C\uDDE6", "\uD83C\uDDF1\uD83C\uDDE6", Collections.singletonList(":flag_la:"), Collections.singletonList(":flag-la:"), Collections.singletonList(":laos:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Laos", d00, q10);
        w.v9 = new f("\uD83C\uDDF1\uD83C\uDDE7", "\uD83C\uDDF1\uD83C\uDDE7", Collections.singletonList(":flag_lb:"), Collections.singletonList(":flag-lb:"), Collections.singletonList(":lebanon:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Lebanon", d00, q10);
        w.w9 = new f("\uD83C\uDDF1\uD83C\uDDE8", "\uD83C\uDDF1\uD83C\uDDE8", Collections.singletonList(":flag_lc:"), Collections.singletonList(":flag-lc:"), Collections.singletonList(":st_lucia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: St. Lucia", d00, q10);
        w.x9 = new f("\uD83C\uDDF1\uD83C\uDDEE", "\uD83C\uDDF1\uD83C\uDDEE", Collections.singletonList(":flag_li:"), Collections.singletonList(":flag-li:"), Collections.singletonList(":liechtenstein:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Liechtenstein", d00, q10);
        w.y9 = new f("\uD83C\uDDF1\uD83C\uDDF0", "\uD83C\uDDF1\uD83C\uDDF0", Collections.singletonList(":flag_lk:"), Collections.singletonList(":flag-lk:"), Collections.singletonList(":sri_lanka:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Sri Lanka", d00, q10);
        w.z9 = new f("\uD83C\uDDF1\uD83C\uDDF7", "\uD83C\uDDF1\uD83C\uDDF7", Collections.singletonList(":flag_lr:"), Collections.singletonList(":flag-lr:"), Collections.singletonList(":liberia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Liberia", d00, q10);
        w.A9 = new f("\uD83C\uDDF1\uD83C\uDDF8", "\uD83C\uDDF1\uD83C\uDDF8", Collections.singletonList(":flag_ls:"), Collections.singletonList(":flag-ls:"), Collections.singletonList(":lesotho:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Lesotho", d00, q10);
        w.B9 = new f("\uD83C\uDDF1\uD83C\uDDF9", "\uD83C\uDDF1\uD83C\uDDF9", Collections.singletonList(":flag_lt:"), Collections.singletonList(":flag-lt:"), Collections.singletonList(":lithuania:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Lithuania", d00, q10);
        w.C9 = new f("\uD83C\uDDF1\uD83C\uDDFA", "\uD83C\uDDF1\uD83C\uDDFA", Collections.singletonList(":flag_lu:"), Collections.singletonList(":flag-lu:"), Collections.singletonList(":luxembourg:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Luxembourg", d00, q10);
        w.D9 = new f("\uD83C\uDDF1\uD83C\uDDFB", "\uD83C\uDDF1\uD83C\uDDFB", Collections.singletonList(":flag_lv:"), Collections.singletonList(":flag-lv:"), Collections.singletonList(":latvia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Latvia", d00, q10);
        w.E9 = new f("\uD83C\uDDF1\uD83C\uDDFE", "\uD83C\uDDF1\uD83C\uDDFE", Collections.singletonList(":flag_ly:"), Collections.singletonList(":flag-ly:"), Collections.singletonList(":libya:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Libya", d00, q10);
        w.F9 = new f("\uD83C\uDDF2\uD83C\uDDE6", "\uD83C\uDDF2\uD83C\uDDE6", Collections.singletonList(":flag_ma:"), Collections.singletonList(":flag-ma:"), Collections.singletonList(":morocco:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Morocco", d00, q10);
        w.G9 = new f("\uD83C\uDDF2\uD83C\uDDE8", "\uD83C\uDDF2\uD83C\uDDE8", Collections.singletonList(":flag_mc:"), Collections.singletonList(":flag-mc:"), Collections.singletonList(":monaco:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Monaco", d00, q10);
        w.H9 = new f("\uD83C\uDDF2\uD83C\uDDE9", "\uD83C\uDDF2\uD83C\uDDE9", Collections.singletonList(":flag_md:"), Collections.singletonList(":flag-md:"), Collections.singletonList(":moldova:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Moldova", d00, q10);
        w.I9 = new f("\uD83C\uDDF2\uD83C\uDDEA", "\uD83C\uDDF2\uD83C\uDDEA", Collections.singletonList(":flag_me:"), Collections.singletonList(":flag-me:"), Collections.singletonList(":montenegro:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Montenegro", d00, q10);
        w.J9 = new f("\uD83C\uDDF2\uD83C\uDDEB", "\uD83C\uDDF2\uD83C\uDDEB", Collections.singletonList(":flag_mf:"), Collections.singletonList(":flag-mf:"), Collections.singletonList(":st_martin:"), false, false, 2.0, M1.a("fully-qualified"), "flag: St. Martin", d00, q10);
        w.K9 = new f("\uD83C\uDDF2\uD83C\uDDEC", "\uD83C\uDDF2\uD83C\uDDEC", Collections.singletonList(":flag_mg:"), Collections.singletonList(":flag-mg:"), Collections.singletonList(":madagascar:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Madagascar", d00, q10);
        w.L9 = new f("\uD83C\uDDF2\uD83C\uDDED", "\uD83C\uDDF2\uD83C\uDDED", Collections.singletonList(":flag_mh:"), Collections.singletonList(":flag-mh:"), Collections.singletonList(":marshall_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Marshall Islands", d00, q10);
        w.M9 = new f("\uD83C\uDDF2\uD83C\uDDF0", "\uD83C\uDDF2\uD83C\uDDF0", Collections.singletonList(":flag_mk:"), Collections.singletonList(":flag-mk:"), Collections.singletonList(":macedonia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: North Macedonia", d00, q10);
        w.N9 = new f("\uD83C\uDDF2\uD83C\uDDF1", "\uD83C\uDDF2\uD83C\uDDF1", Collections.singletonList(":flag_ml:"), Collections.singletonList(":flag-ml:"), Collections.singletonList(":mali:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Mali", d00, q10);
        w.O9 = new f("\uD83C\uDDF2\uD83C\uDDF2", "\uD83C\uDDF2\uD83C\uDDF2", Collections.singletonList(":flag_mm:"), Collections.singletonList(":flag-mm:"), Collections.singletonList(":myanmar:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Myanmar (Burma)", d00, q10);
        w.P9 = new f("\uD83C\uDDF2\uD83C\uDDF3", "\uD83C\uDDF2\uD83C\uDDF3", Collections.singletonList(":flag_mn:"), Collections.singletonList(":flag-mn:"), Collections.singletonList(":mongolia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Mongolia", d00, q10);
        w.Q9 = new f("\uD83C\uDDF2\uD83C\uDDF4", "\uD83C\uDDF2\uD83C\uDDF4", Collections.singletonList(":flag_mo:"), Collections.singletonList(":flag-mo:"), Collections.singletonList(":macau:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Macao SAR China", d00, q10);
        w.R9 = new f("\uD83C\uDDF2\uD83C\uDDF5", "\uD83C\uDDF2\uD83C\uDDF5", Collections.singletonList(":flag_mp:"), Collections.singletonList(":flag-mp:"), Collections.singletonList(":northern_mariana_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Northern Mariana Islands", d00, q10);
        w.S9 = new f("\uD83C\uDDF2\uD83C\uDDF6", "\uD83C\uDDF2\uD83C\uDDF6", Collections.singletonList(":flag_mq:"), Collections.singletonList(":flag-mq:"), Collections.singletonList(":martinique:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Martinique", d00, q10);
        w.T9 = new f("\uD83C\uDDF2\uD83C\uDDF7", "\uD83C\uDDF2\uD83C\uDDF7", Collections.singletonList(":flag_mr:"), Collections.singletonList(":flag-mr:"), Collections.singletonList(":mauritania:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Mauritania", d00, q10);
        w.U9 = new f("\uD83C\uDDF2\uD83C\uDDF8", "\uD83C\uDDF2\uD83C\uDDF8", Collections.singletonList(":flag_ms:"), Collections.singletonList(":flag-ms:"), Collections.singletonList(":montserrat:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Montserrat", d00, q10);
        w.V9 = new f("\uD83C\uDDF2\uD83C\uDDF9", "\uD83C\uDDF2\uD83C\uDDF9", Collections.singletonList(":flag_mt:"), Collections.singletonList(":flag-mt:"), Collections.singletonList(":malta:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Malta", d00, q10);
        w.W9 = new f("\uD83C\uDDF2\uD83C\uDDFA", "\uD83C\uDDF2\uD83C\uDDFA", Collections.singletonList(":flag_mu:"), Collections.singletonList(":flag-mu:"), Collections.singletonList(":mauritius:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Mauritius", d00, q10);
        w.X9 = new f("\uD83C\uDDF2\uD83C\uDDFB", "\uD83C\uDDF2\uD83C\uDDFB", Collections.singletonList(":flag_mv:"), Collections.singletonList(":flag-mv:"), Collections.singletonList(":maldives:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Maldives", d00, q10);
        w.Y9 = new f("\uD83C\uDDF2\uD83C\uDDFC", "\uD83C\uDDF2\uD83C\uDDFC", Collections.singletonList(":flag_mw:"), Collections.singletonList(":flag-mw:"), Collections.singletonList(":malawi:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Malawi", d00, q10);
        w.Z9 = new f("\uD83C\uDDF2\uD83C\uDDFD", "\uD83C\uDDF2\uD83C\uDDFD", Collections.singletonList(":flag_mx:"), Collections.singletonList(":flag-mx:"), Collections.singletonList(":mexico:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Mexico", d00, q10);
        w.aa = new f("\uD83C\uDDF2\uD83C\uDDFE", "\uD83C\uDDF2\uD83C\uDDFE", Collections.singletonList(":flag_my:"), Collections.singletonList(":flag-my:"), Collections.singletonList(":malaysia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Malaysia", d00, q10);
        w.ba = new f("\uD83C\uDDF2\uD83C\uDDFF", "\uD83C\uDDF2\uD83C\uDDFF", Collections.singletonList(":flag_mz:"), Collections.singletonList(":flag-mz:"), Collections.singletonList(":mozambique:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Mozambique", d00, q10);
        w.ca = new f("\uD83C\uDDF3\uD83C\uDDE6", "\uD83C\uDDF3\uD83C\uDDE6", Collections.singletonList(":flag_na:"), Collections.singletonList(":flag-na:"), Collections.singletonList(":namibia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Namibia", d00, q10);
        w.da = new f("\uD83C\uDDF3\uD83C\uDDE8", "\uD83C\uDDF3\uD83C\uDDE8", Collections.singletonList(":flag_nc:"), Collections.singletonList(":flag-nc:"), Collections.singletonList(":new_caledonia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: New Caledonia", d00, q10);
        w.ea = new f("\uD83C\uDDF3\uD83C\uDDEA", "\uD83C\uDDF3\uD83C\uDDEA", Collections.singletonList(":flag_ne:"), Collections.singletonList(":flag-ne:"), Collections.singletonList(":niger:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Niger", d00, q10);
        w.fa = new f("\uD83C\uDDF3\uD83C\uDDEB", "\uD83C\uDDF3\uD83C\uDDEB", Collections.singletonList(":flag_nf:"), Collections.singletonList(":flag-nf:"), Collections.singletonList(":norfolk_island:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Norfolk Island", d00, q10);
        w.ga = new f("\uD83C\uDDF3\uD83C\uDDEC", "\uD83C\uDDF3\uD83C\uDDEC", Collections.singletonList(":flag_ng:"), Collections.singletonList(":flag-ng:"), Collections.singletonList(":nigeria:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Nigeria", d00, q10);
        w.ha = new f("\uD83C\uDDF3\uD83C\uDDEE", "\uD83C\uDDF3\uD83C\uDDEE", Collections.singletonList(":flag_ni:"), Collections.singletonList(":flag-ni:"), Collections.singletonList(":nicaragua:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Nicaragua", d00, q10);
        w.ia = new f("\uD83C\uDDF3\uD83C\uDDF1", "\uD83C\uDDF3\uD83C\uDDF1", Collections.singletonList(":flag_nl:"), Collections.singletonList(":flag-nl:"), Collections.singletonList(":netherlands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Netherlands", d00, q10);
        w.ja = new f("\uD83C\uDDF3\uD83C\uDDF4", "\uD83C\uDDF3\uD83C\uDDF4", Collections.singletonList(":flag_no:"), Collections.singletonList(":flag-no:"), Collections.singletonList(":norway:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Norway", d00, q10);
        w.ka = new f("\uD83C\uDDF3\uD83C\uDDF5", "\uD83C\uDDF3\uD83C\uDDF5", Collections.singletonList(":flag_np:"), Collections.singletonList(":flag-np:"), Collections.singletonList(":nepal:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Nepal", d00, q10);
        w.la = new f("\uD83C\uDDF3\uD83C\uDDF7", "\uD83C\uDDF3\uD83C\uDDF7", Collections.singletonList(":flag_nr:"), Collections.singletonList(":flag-nr:"), Collections.singletonList(":nauru:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Nauru", d00, q10);
        w.ma = new f("\uD83C\uDDF3\uD83C\uDDFA", "\uD83C\uDDF3\uD83C\uDDFA", Collections.singletonList(":flag_nu:"), Collections.singletonList(":flag-nu:"), Collections.singletonList(":niue:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Niue", d00, q10);
        w.na = new f("\uD83C\uDDF3\uD83C\uDDFF", "\uD83C\uDDF3\uD83C\uDDFF", Collections.singletonList(":flag_nz:"), Collections.singletonList(":flag-nz:"), Collections.singletonList(":new_zealand:"), false, false, 2.0, M1.a("fully-qualified"), "flag: New Zealand", d00, q10);
        w.oa = new f("\uD83C\uDDF4\uD83C\uDDF2", "\uD83C\uDDF4\uD83C\uDDF2", Collections.singletonList(":flag_om:"), Collections.singletonList(":flag-om:"), Collections.singletonList(":oman:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Oman", d00, q10);
        w.pa = new f("\uD83C\uDDF5\uD83C\uDDE6", "\uD83C\uDDF5\uD83C\uDDE6", Collections.singletonList(":flag_pa:"), Collections.singletonList(":flag-pa:"), Collections.singletonList(":panama:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Panama", d00, q10);
        w.qa = new f("\uD83C\uDDF5\uD83C\uDDEA", "\uD83C\uDDF5\uD83C\uDDEA", Collections.singletonList(":flag_pe:"), Collections.singletonList(":flag-pe:"), Collections.singletonList(":peru:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Peru", d00, q10);
        w.ra = new f("\uD83C\uDDF5\uD83C\uDDEB", "\uD83C\uDDF5\uD83C\uDDEB", Collections.singletonList(":flag_pf:"), Collections.singletonList(":flag-pf:"), Collections.singletonList(":french_polynesia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: French Polynesia", d00, q10);
        w.sa = new f("\uD83C\uDDF5\uD83C\uDDEC", "\uD83C\uDDF5\uD83C\uDDEC", Collections.singletonList(":flag_pg:"), Collections.singletonList(":flag-pg:"), Collections.singletonList(":papua_new_guinea:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Papua New Guinea", d00, q10);
        w.ta = new f("\uD83C\uDDF5\uD83C\uDDED", "\uD83C\uDDF5\uD83C\uDDED", Collections.singletonList(":flag_ph:"), Collections.singletonList(":flag-ph:"), Collections.singletonList(":philippines:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Philippines", d00, q10);
        w.ua = new f("\uD83C\uDDF5\uD83C\uDDF0", "\uD83C\uDDF5\uD83C\uDDF0", Collections.singletonList(":flag_pk:"), Collections.singletonList(":flag-pk:"), Collections.singletonList(":pakistan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Pakistan", d00, q10);
        w.va = new f("\uD83C\uDDF5\uD83C\uDDF1", "\uD83C\uDDF5\uD83C\uDDF1", Collections.singletonList(":flag_pl:"), Collections.singletonList(":flag-pl:"), Collections.singletonList(":poland:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Poland", d00, q10);
        w.wa = new f("\uD83C\uDDF5\uD83C\uDDF2", "\uD83C\uDDF5\uD83C\uDDF2", Collections.singletonList(":flag_pm:"), Collections.singletonList(":flag-pm:"), Collections.singletonList(":st_pierre_miquelon:"), false, false, 2.0, M1.a("fully-qualified"), "flag: St. Pierre & Miquelon", d00, q10);
        w.xa = new f("\uD83C\uDDF5\uD83C\uDDF3", "\uD83C\uDDF5\uD83C\uDDF3", Collections.singletonList(":flag_pn:"), Collections.singletonList(":flag-pn:"), Collections.singletonList(":pitcairn_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Pitcairn Islands", d00, q10);
        w.ya = new f("\uD83C\uDDF5\uD83C\uDDF7", "\uD83C\uDDF5\uD83C\uDDF7", Collections.singletonList(":flag_pr:"), Collections.singletonList(":flag-pr:"), Collections.singletonList(":puerto_rico:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Puerto Rico", d00, q10);
        w.za = new f("\uD83C\uDDF5\uD83C\uDDF8", "\uD83C\uDDF5\uD83C\uDDF8", Collections.singletonList(":flag_ps:"), Collections.singletonList(":flag-ps:"), Collections.singletonList(":palestinian_territories:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Palestinian Territories", d00, q10);
        w.Aa = new f("\uD83C\uDDF5\uD83C\uDDF9", "\uD83C\uDDF5\uD83C\uDDF9", Collections.singletonList(":flag_pt:"), Collections.singletonList(":flag-pt:"), Collections.singletonList(":portugal:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Portugal", d00, q10);
        w.Ba = new f("\uD83C\uDDF5\uD83C\uDDFC", "\uD83C\uDDF5\uD83C\uDDFC", Collections.singletonList(":flag_pw:"), Collections.singletonList(":flag-pw:"), Collections.singletonList(":palau:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Palau", d00, q10);
        w.Ca = new f("\uD83C\uDDF5\uD83C\uDDFE", "\uD83C\uDDF5\uD83C\uDDFE", Collections.singletonList(":flag_py:"), Collections.singletonList(":flag-py:"), Collections.singletonList(":paraguay:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Paraguay", d00, q10);
        w.Da = new f("\uD83C\uDDF6\uD83C\uDDE6", "\uD83C\uDDF6\uD83C\uDDE6", Collections.singletonList(":flag_qa:"), Collections.singletonList(":flag-qa:"), Collections.singletonList(":qatar:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Qatar", d00, q10);
        w.Ea = new f("\uD83C\uDDF7\uD83C\uDDEA", "\uD83C\uDDF7\uD83C\uDDEA", Collections.singletonList(":flag_re:"), Collections.singletonList(":flag-re:"), Collections.singletonList(":reunion:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Réunion", d00, q10);
        w.Fa = new f("\uD83C\uDDF7\uD83C\uDDF4", "\uD83C\uDDF7\uD83C\uDDF4", Collections.singletonList(":flag_ro:"), Collections.singletonList(":flag-ro:"), Collections.singletonList(":romania:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Romania", d00, q10);
        w.Ga = new f("\uD83C\uDDF7\uD83C\uDDF8", "\uD83C\uDDF7\uD83C\uDDF8", Collections.singletonList(":flag_rs:"), Collections.singletonList(":flag-rs:"), Collections.singletonList(":serbia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Serbia", d00, q10);
        w.Ha = new f("\uD83C\uDDF7\uD83C\uDDFA", "\uD83C\uDDF7\uD83C\uDDFA", Collections.singletonList(":flag_ru:"), Collections.singletonList(":ru:"), Collections.singletonList(":ru:"), false, false, 0.6, M1.a("fully-qualified"), "flag: Russia", d00, q10);
        w.Ia = new f("\uD83C\uDDF7\uD83C\uDDFC", "\uD83C\uDDF7\uD83C\uDDFC", Collections.singletonList(":flag_rw:"), Collections.singletonList(":flag-rw:"), Collections.singletonList(":rwanda:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Rwanda", d00, q10);
        w.Ja = new f("\uD83C\uDDF8\uD83C\uDDE6", "\uD83C\uDDF8\uD83C\uDDE6", Collections.singletonList(":flag_sa:"), Collections.singletonList(":flag-sa:"), Collections.singletonList(":saudi_arabia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Saudi Arabia", d00, q10);
        w.Ka = new f("\uD83C\uDDF8\uD83C\uDDE7", "\uD83C\uDDF8\uD83C\uDDE7", Collections.singletonList(":flag_sb:"), Collections.singletonList(":flag-sb:"), Collections.singletonList(":solomon_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Solomon Islands", d00, q10);
        w.La = new f("\uD83C\uDDF8\uD83C\uDDE8", "\uD83C\uDDF8\uD83C\uDDE8", Collections.singletonList(":flag_sc:"), Collections.singletonList(":flag-sc:"), Collections.singletonList(":seychelles:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Seychelles", d00, q10);
        w.Ma = new f("\uD83C\uDDF8\uD83C\uDDE9", "\uD83C\uDDF8\uD83C\uDDE9", Collections.singletonList(":flag_sd:"), Collections.singletonList(":flag-sd:"), Collections.singletonList(":sudan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Sudan", d00, q10);
        w.Na = new f("\uD83C\uDDF8\uD83C\uDDEA", "\uD83C\uDDF8\uD83C\uDDEA", Collections.singletonList(":flag_se:"), Collections.singletonList(":flag-se:"), Collections.singletonList(":sweden:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Sweden", d00, q10);
        w.Oa = new f("\uD83C\uDDF8\uD83C\uDDEC", "\uD83C\uDDF8\uD83C\uDDEC", Collections.singletonList(":flag_sg:"), Collections.singletonList(":flag-sg:"), Collections.singletonList(":singapore:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Singapore", d00, q10);
        w.Pa = new f("\uD83C\uDDF8\uD83C\uDDED", "\uD83C\uDDF8\uD83C\uDDED", Collections.singletonList(":flag_sh:"), Collections.singletonList(":flag-sh:"), Collections.singletonList(":st_helena:"), false, false, 2.0, M1.a("fully-qualified"), "flag: St. Helena", d00, q10);
        w.Qa = new f("\uD83C\uDDF8\uD83C\uDDEE", "\uD83C\uDDF8\uD83C\uDDEE", Collections.singletonList(":flag_si:"), Collections.singletonList(":flag-si:"), Collections.singletonList(":slovenia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Slovenia", d00, q10);
        w.Ra = new f("\uD83C\uDDF8\uD83C\uDDEF", "\uD83C\uDDF8\uD83C\uDDEF", Collections.singletonList(":flag_sj:"), Collections.singletonList(":flag-sj:"), Collections.singletonList(":svalbard_jan_mayen:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Svalbard & Jan Mayen", d00, q10);
        w.Sa = new f("\uD83C\uDDF8\uD83C\uDDF0", "\uD83C\uDDF8\uD83C\uDDF0", Collections.singletonList(":flag_sk:"), Collections.singletonList(":flag-sk:"), Collections.singletonList(":slovakia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Slovakia", d00, q10);
        w.Ta = new f("\uD83C\uDDF8\uD83C\uDDF1", "\uD83C\uDDF8\uD83C\uDDF1", Collections.singletonList(":flag_sl:"), Collections.singletonList(":flag-sl:"), Collections.singletonList(":sierra_leone:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Sierra Leone", d00, q10);
        w.Ua = new f("\uD83C\uDDF8\uD83C\uDDF2", "\uD83C\uDDF8\uD83C\uDDF2", Collections.singletonList(":flag_sm:"), Collections.singletonList(":flag-sm:"), Collections.singletonList(":san_marino:"), false, false, 2.0, M1.a("fully-qualified"), "flag: San Marino", d00, q10);
        w.Va = new f("\uD83C\uDDF8\uD83C\uDDF3", "\uD83C\uDDF8\uD83C\uDDF3", Collections.singletonList(":flag_sn:"), Collections.singletonList(":flag-sn:"), Collections.singletonList(":senegal:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Senegal", d00, q10);
        w.Wa = new f("\uD83C\uDDF8\uD83C\uDDF4", "\uD83C\uDDF8\uD83C\uDDF4", Collections.singletonList(":flag_so:"), Collections.singletonList(":flag-so:"), Collections.singletonList(":somalia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Somalia", d00, q10);
        w.Xa = new f("\uD83C\uDDF8\uD83C\uDDF7", "\uD83C\uDDF8\uD83C\uDDF7", Collections.singletonList(":flag_sr:"), Collections.singletonList(":flag-sr:"), Collections.singletonList(":suriname:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Suriname", d00, q10);
        w.Ya = new f("\uD83C\uDDF8\uD83C\uDDF8", "\uD83C\uDDF8\uD83C\uDDF8", Collections.singletonList(":flag_ss:"), Collections.singletonList(":flag-ss:"), Collections.singletonList(":south_sudan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: South Sudan", d00, q10);
        w.Za = new f("\uD83C\uDDF8\uD83C\uDDF9", "\uD83C\uDDF8\uD83C\uDDF9", Collections.singletonList(":flag_st:"), Collections.singletonList(":flag-st:"), Collections.singletonList(":sao_tome_principe:"), false, false, 2.0, M1.a("fully-qualified"), "flag: São Tomé & Príncipe", d00, q10);
        w.ab = new f("\uD83C\uDDF8\uD83C\uDDFB", "\uD83C\uDDF8\uD83C\uDDFB", Collections.singletonList(":flag_sv:"), Collections.singletonList(":flag-sv:"), Collections.singletonList(":el_salvador:"), false, false, 2.0, M1.a("fully-qualified"), "flag: El Salvador", d00, q10);
        w.bb = new f("\uD83C\uDDF8\uD83C\uDDFD", "\uD83C\uDDF8\uD83C\uDDFD", Collections.singletonList(":flag_sx:"), Collections.singletonList(":flag-sx:"), Collections.singletonList(":sint_maarten:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Sint Maarten", d00, q10);
        w.cb = new f("\uD83C\uDDF8\uD83C\uDDFE", "\uD83C\uDDF8\uD83C\uDDFE", Collections.singletonList(":flag_sy:"), Collections.singletonList(":flag-sy:"), Collections.singletonList(":syria:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Syria", d00, q10);
        w.db = new f("\uD83C\uDDF8\uD83C\uDDFF", "\uD83C\uDDF8\uD83C\uDDFF", Collections.singletonList(":flag_sz:"), Collections.singletonList(":flag-sz:"), Collections.singletonList(":swaziland:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Eswatini", d00, q10);
        w.eb = new f("\uD83C\uDDF9\uD83C\uDDE6", "\uD83C\uDDF9\uD83C\uDDE6", Collections.singletonList(":flag_ta:"), Collections.singletonList(":flag-ta:"), Collections.singletonList(":tristan_da_cunha:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Tristan da Cunha", d00, q10);
        w.fb = new f("\uD83C\uDDF9\uD83C\uDDE8", "\uD83C\uDDF9\uD83C\uDDE8", Collections.singletonList(":flag_tc:"), Collections.singletonList(":flag-tc:"), Collections.singletonList(":turks_caicos_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Turks & Caicos Islands", d00, q10);
        w.gb = new f("\uD83C\uDDF9\uD83C\uDDE9", "\uD83C\uDDF9\uD83C\uDDE9", Collections.singletonList(":flag_td:"), Collections.singletonList(":flag-td:"), Collections.singletonList(":chad:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Chad", d00, q10);
        w.hb = new f("\uD83C\uDDF9\uD83C\uDDEB", "\uD83C\uDDF9\uD83C\uDDEB", Collections.singletonList(":flag_tf:"), Collections.singletonList(":flag-tf:"), Collections.singletonList(":french_southern_territories:"), false, false, 2.0, M1.a("fully-qualified"), "flag: French Southern Territories", d00, q10);
        w.ib = new f("\uD83C\uDDF9\uD83C\uDDEC", "\uD83C\uDDF9\uD83C\uDDEC", Collections.singletonList(":flag_tg:"), Collections.singletonList(":flag-tg:"), Collections.singletonList(":togo:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Togo", d00, q10);
        w.jb = new f("\uD83C\uDDF9\uD83C\uDDED", "\uD83C\uDDF9\uD83C\uDDED", Collections.singletonList(":flag_th:"), Collections.singletonList(":flag-th:"), Collections.singletonList(":thailand:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Thailand", d00, q10);
        w.kb = new f("\uD83C\uDDF9\uD83C\uDDEF", "\uD83C\uDDF9\uD83C\uDDEF", Collections.singletonList(":flag_tj:"), Collections.singletonList(":flag-tj:"), Collections.singletonList(":tajikistan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Tajikistan", d00, q10);
        w.lb = new f("\uD83C\uDDF9\uD83C\uDDF0", "\uD83C\uDDF9\uD83C\uDDF0", Collections.singletonList(":flag_tk:"), Collections.singletonList(":flag-tk:"), Collections.singletonList(":tokelau:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Tokelau", d00, q10);
        w.mb = new f("\uD83C\uDDF9\uD83C\uDDF1", "\uD83C\uDDF9\uD83C\uDDF1", Collections.singletonList(":flag_tl:"), Collections.singletonList(":flag-tl:"), Collections.singletonList(":timor_leste:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Timor-Leste", d00, q10);
        w.nb = new f("\uD83C\uDDF9\uD83C\uDDF2", "\uD83C\uDDF9\uD83C\uDDF2", Collections.singletonList(":flag_tm:"), Collections.singletonList(":flag-tm:"), Collections.singletonList(":turkmenistan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Turkmenistan", d00, q10);
        w.ob = new f("\uD83C\uDDF9\uD83C\uDDF3", "\uD83C\uDDF9\uD83C\uDDF3", Collections.singletonList(":flag_tn:"), Collections.singletonList(":flag-tn:"), Collections.singletonList(":tunisia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Tunisia", d00, q10);
        w.pb = new f("\uD83C\uDDF9\uD83C\uDDF4", "\uD83C\uDDF9\uD83C\uDDF4", Collections.singletonList(":flag_to:"), Collections.singletonList(":flag-to:"), Collections.singletonList(":tonga:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Tonga", d00, q10);
        w.qb = new f("\uD83C\uDDF9\uD83C\uDDF7", "\uD83C\uDDF9\uD83C\uDDF7", Collections.singletonList(":flag_tr:"), Collections.singletonList(":flag-tr:"), Collections.singletonList(":tr:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Türkiye", d00, q10);
        w.rb = new f("\uD83C\uDDF9\uD83C\uDDF9", "\uD83C\uDDF9\uD83C\uDDF9", Collections.singletonList(":flag_tt:"), Collections.singletonList(":flag-tt:"), Collections.singletonList(":trinidad_tobago:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Trinidad & Tobago", d00, q10);
        w.sb = new f("\uD83C\uDDF9\uD83C\uDDFB", "\uD83C\uDDF9\uD83C\uDDFB", Collections.singletonList(":flag_tv:"), Collections.singletonList(":flag-tv:"), Collections.singletonList(":tuvalu:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Tuvalu", d00, q10);
        w.tb = new f("\uD83C\uDDF9\uD83C\uDDFC", "\uD83C\uDDF9\uD83C\uDDFC", Collections.singletonList(":flag_tw:"), Collections.singletonList(":flag-tw:"), Collections.singletonList(":taiwan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Taiwan", d00, q10);
        w.ub = new f("\uD83C\uDDF9\uD83C\uDDFF", "\uD83C\uDDF9\uD83C\uDDFF", Collections.singletonList(":flag_tz:"), Collections.singletonList(":flag-tz:"), Collections.singletonList(":tanzania:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Tanzania", d00, q10);
        w.vb = new f("\uD83C\uDDFA\uD83C\uDDE6", "\uD83C\uDDFA\uD83C\uDDE6", Collections.singletonList(":flag_ua:"), Collections.singletonList(":flag-ua:"), Collections.singletonList(":ukraine:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Ukraine", d00, q10);
        w.wb = new f("\uD83C\uDDFA\uD83C\uDDEC", "\uD83C\uDDFA\uD83C\uDDEC", Collections.singletonList(":flag_ug:"), Collections.singletonList(":flag-ug:"), Collections.singletonList(":uganda:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Uganda", d00, q10);
        w.xb = new f("\uD83C\uDDFA\uD83C\uDDF2", "\uD83C\uDDFA\uD83C\uDDF2", Collections.singletonList(":flag_um:"), Collections.singletonList(":flag-um:"), Collections.singletonList(":us_outlying_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: U.S. Outlying Islands", d00, q10);
        w.yb = new f("\uD83C\uDDFA\uD83C\uDDF3", "\uD83C\uDDFA\uD83C\uDDF3", Collections.singletonList(":united_nations:"), Collections.singletonList(":flag-un:"), Collections.singletonList(":united_nations:"), false, false, 4.0, M1.a("fully-qualified"), "flag: United Nations", d00, q10);
        w.zb = new f("\uD83C\uDDFA\uD83C\uDDF8", "\uD83C\uDDFA\uD83C\uDDF8", Collections.singletonList(":flag_us:"), Collections.singletonList(":us:"), Collections.singletonList(":us:"), false, false, 0.6, M1.a("fully-qualified"), "flag: United States", d00, q10);
        w.Ab = new f("\uD83C\uDDFA\uD83C\uDDFE", "\uD83C\uDDFA\uD83C\uDDFE", Collections.singletonList(":flag_uy:"), Collections.singletonList(":flag-uy:"), Collections.singletonList(":uruguay:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Uruguay", d00, q10);
        w.Bb = new f("\uD83C\uDDFA\uD83C\uDDFF", "\uD83C\uDDFA\uD83C\uDDFF", Collections.singletonList(":flag_uz:"), Collections.singletonList(":flag-uz:"), Collections.singletonList(":uzbekistan:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Uzbekistan", d00, q10);
        w.Cb = new f("\uD83C\uDDFB\uD83C\uDDE6", "\uD83C\uDDFB\uD83C\uDDE6", Collections.singletonList(":flag_va:"), Collections.singletonList(":flag-va:"), Collections.singletonList(":vatican_city:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Vatican City", d00, q10);
        w.Db = new f("\uD83C\uDDFB\uD83C\uDDE8", "\uD83C\uDDFB\uD83C\uDDE8", Collections.singletonList(":flag_vc:"), Collections.singletonList(":flag-vc:"), Collections.singletonList(":st_vincent_grenadines:"), false, false, 2.0, M1.a("fully-qualified"), "flag: St. Vincent & Grenadines", d00, q10);
        w.Eb = new f("\uD83C\uDDFB\uD83C\uDDEA", "\uD83C\uDDFB\uD83C\uDDEA", Collections.singletonList(":flag_ve:"), Collections.singletonList(":flag-ve:"), Collections.singletonList(":venezuela:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Venezuela", d00, q10);
        w.Fb = new f("\uD83C\uDDFB\uD83C\uDDEC", "\uD83C\uDDFB\uD83C\uDDEC", Collections.singletonList(":flag_vg:"), Collections.singletonList(":flag-vg:"), Collections.singletonList(":british_virgin_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: British Virgin Islands", d00, q10);
        w.Gb = new f("\uD83C\uDDFB\uD83C\uDDEE", "\uD83C\uDDFB\uD83C\uDDEE", Collections.singletonList(":flag_vi:"), Collections.singletonList(":flag-vi:"), Collections.singletonList(":us_virgin_islands:"), false, false, 2.0, M1.a("fully-qualified"), "flag: U.S. Virgin Islands", d00, q10);
        w.Hb = new f("\uD83C\uDDFB\uD83C\uDDF3", "\uD83C\uDDFB\uD83C\uDDF3", Collections.singletonList(":flag_vn:"), Collections.singletonList(":flag-vn:"), Collections.singletonList(":vietnam:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Vietnam", d00, q10);
        w.Ib = new f("\uD83C\uDDFB\uD83C\uDDFA", "\uD83C\uDDFB\uD83C\uDDFA", Collections.singletonList(":flag_vu:"), Collections.singletonList(":flag-vu:"), Collections.singletonList(":vanuatu:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Vanuatu", d00, q10);
        w.Jb = new f("\uD83C\uDDFC\uD83C\uDDEB", "\uD83C\uDDFC\uD83C\uDDEB", Collections.singletonList(":flag_wf:"), Collections.singletonList(":flag-wf:"), Collections.singletonList(":wallis_futuna:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Wallis & Futuna", d00, q10);
        w.Kb = new f("\uD83C\uDDFC\uD83C\uDDF8", "\uD83C\uDDFC\uD83C\uDDF8", Collections.singletonList(":flag_ws:"), Collections.singletonList(":flag-ws:"), Collections.singletonList(":samoa:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Samoa", d00, q10);
        w.Lb = new f("\uD83C\uDDFD\uD83C\uDDF0", "\uD83C\uDDFD\uD83C\uDDF0", Collections.singletonList(":flag_xk:"), Collections.singletonList(":flag-xk:"), Collections.singletonList(":kosovo:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Kosovo", d00, q10);
        w.Mb = new f("\uD83C\uDDFE\uD83C\uDDEA", "\uD83C\uDDFE\uD83C\uDDEA", Collections.singletonList(":flag_ye:"), Collections.singletonList(":flag-ye:"), Collections.singletonList(":yemen:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Yemen", d00, q10);
        w.Nb = new f("\uD83C\uDDFE\uD83C\uDDF9", "\uD83C\uDDFE\uD83C\uDDF9", Collections.singletonList(":flag_yt:"), Collections.singletonList(":flag-yt:"), Collections.singletonList(":mayotte:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Mayotte", d00, q10);
        w.Ob = new f("\uD83C\uDDFF\uD83C\uDDE6", "\uD83C\uDDFF\uD83C\uDDE6", Collections.singletonList(":flag_za:"), Collections.singletonList(":flag-za:"), Collections.singletonList(":south_africa:"), false, false, 2.0, M1.a("fully-qualified"), "flag: South Africa", d00, q10);
        w.Pb = new f("\uD83C\uDDFF\uD83C\uDDF2", "\uD83C\uDDFF\uD83C\uDDF2", Collections.singletonList(":flag_zm:"), Collections.singletonList(":flag-zm:"), Collections.singletonList(":zambia:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Zambia", d00, q10);
        w.Qb = new f("\uD83C\uDDFF\uD83C\uDDFC", "\uD83C\uDDFF\uD83C\uDDFC", Collections.singletonList(":flag_zw:"), Collections.singletonList(":flag-zw:"), Collections.singletonList(":zimbabwe:"), false, false, 2.0, M1.a("fully-qualified"), "flag: Zimbabwe", d00, q10);
    }
}

