package com.bytedance.sdk.openadsdk.fDm;

import android.content.Context;
import android.graphics.Color;
import android.text.TextUtils.TruncateAt;
import android.util.AttributeSet;
import android.widget.ImageView.ScaleType;
import android.widget.LinearLayout.LayoutParams;
import android.widget.RelativeLayout.LayoutParams;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.Lrd;
import com.bytedance.sdk.openadsdk.core.JQp.Au;
import com.bytedance.sdk.openadsdk.core.JQp.JQp;
import com.bytedance.sdk.openadsdk.core.JQp.XX;
import com.bytedance.sdk.openadsdk.core.JQp.cr;
import com.bytedance.sdk.openadsdk.core.JQp.cz;
import com.bytedance.sdk.openadsdk.utils.DWo;
import com.bytedance.sdk.openadsdk.utils.qZS;
import com.bytedance.sdk.openadsdk.utils.qla;

public class xs extends XX {
    public xs(Context context0) {
        this(context0, null);
    }

    public xs(Context context0, AttributeSet attributeSet0) {
        this(context0, attributeSet0, 0);
    }

    public xs(Context context0, AttributeSet attributeSet0, int v) {
        super(context0, attributeSet0, v);
        this.PjT(context0);
    }

    private void PjT(Context context0) {
        this.setId(0x1F00001E);
        this.setBackgroundColor(-1);
        XX xX0 = new XX(context0);
        xX0.setId(qla.QB);
        xX0.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        xX0.setBackgroundColor(0);
        xX0.setGravity(17);
        this.addView(xX0);
        cr cr0 = new cr(context0);
        cr0.setId(qla.pBJ);
        cr0.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        xX0.addView(cr0);
        cz cz0 = new cz(context0);
        cz0.setId(qla.sjb);
        int v = qZS.Zh(context0, 60.0f);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams0 = new RelativeLayout.LayoutParams(v, v);
        relativeLayout$LayoutParams0.addRule(13);
        cz0.setLayoutParams(relativeLayout$LayoutParams0);
        cz0.setIndeterminateDrawable(DWo.PjT(context0, "tt_video_loading_progress_bar"));
        xX0.addView(cz0);
        JQp jQp0 = new JQp(context0);
        jQp0.setId(qla.vSp);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams1 = new RelativeLayout.LayoutParams(-2, -2);
        relativeLayout$LayoutParams1.addRule(13);
        jQp0.setLayoutParams(relativeLayout$LayoutParams1);
        jQp0.setGravity(1);
        jQp0.setOrientation(1);
        jQp0.setVisibility(8);
        xX0.addView(jQp0);
        cr cr1 = new cr(context0);
        cr1.setId(qla.hLk);
        cr1.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        cr1.setImageDrawable(DWo.PjT(context0, "tt_refreshing_video_textpage"));
        ImageView.ScaleType imageView$ScaleType0 = ImageView.ScaleType.CENTER;
        cr1.setScaleType(imageView$ScaleType0);
        jQp0.addView(cr1);
        Au au0 = new Au(context0);
        au0.setId(qla.VZ);
        au0.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        au0.setText(Lrd.PjT(context0, "tt_video_retry_des_txt"));
        au0.setTextColor(Color.parseColor("#999999"));
        jQp0.addView(au0);
        cr cr2 = new cr(context0);
        cr2.setId(qla.dG);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        relativeLayout$LayoutParams2.addRule(13);
        cr2.setLayoutParams(relativeLayout$LayoutParams2);
        cr2.setScaleType(imageView$ScaleType0);
        cr2.setImageDrawable(DWo.PjT(context0, "tt_play_movebar_textpage"));
        cr2.setVisibility(8);
        this.addView(cr2);
        cr cr3 = new cr(context0);
        cr3.setId(qla.NR);
        int v1 = qZS.Zh(context0, 30.0f);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams3 = new RelativeLayout.LayoutParams(v1, v1);
        relativeLayout$LayoutParams3.addRule(21);
        relativeLayout$LayoutParams3.addRule(11);
        int v2 = qZS.Zh(context0, 7.0f);
        relativeLayout$LayoutParams3.setMarginEnd(v2);
        relativeLayout$LayoutParams3.rightMargin = v2;
        relativeLayout$LayoutParams3.topMargin = v2;
        cr3.setLayoutParams(relativeLayout$LayoutParams3);
        cr3.setBackground(DWo.PjT(context0, "tt_detail_video_btn_bg"));
        cr3.setScaleType(imageView$ScaleType0);
        cr3.setImageDrawable(DWo.PjT(context0, "tt_close_move_detail"));
        this.addView(cr3);
        Au au1 = new Au(context0);
        au1.setId(qla.KP);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams4 = new RelativeLayout.LayoutParams(-1, -2);
        relativeLayout$LayoutParams4.addRule(9);
        relativeLayout$LayoutParams4.addRule(20);
        relativeLayout$LayoutParams4.addRule(10);
        au1.setLayoutParams(relativeLayout$LayoutParams4);
        au1.setBackground(DWo.PjT(context0, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt textUtils$TruncateAt0 = TextUtils.TruncateAt.END;
        au1.setEllipsize(textUtils$TruncateAt0);
        au1.setMaxLines(2);
        int v3 = qZS.Zh(context0, 15.0f);
        au1.setPadding(v3, qZS.Zh(context0, 14.0f), v3, 0);
        au1.setSingleLine(false);
        au1.setTextColor(-1);
        au1.setTextSize(2, 17.0f);
        au1.setVisibility(8);
        this.addView(au1);
        XX xX1 = new XX(context0);
        xX1.setId(qla.Lmo);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        relativeLayout$LayoutParams5.addRule(10);
        xX1.setLayoutParams(relativeLayout$LayoutParams5);
        xX1.setBackground(DWo.PjT(context0, "tt_video_black_desc_gradient"));
        xX1.setGravity(16);
        xX1.setVisibility(8);
        this.addView(xX1);
        cr cr4 = new cr(context0);
        cr4.setId(qla.xi);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams6 = new RelativeLayout.LayoutParams(-2, -1);
        relativeLayout$LayoutParams6.addRule(15);
        int v4 = qZS.Zh(context0, 12.0f);
        relativeLayout$LayoutParams6.leftMargin = v4;
        relativeLayout$LayoutParams6.setMarginStart(v4);
        cr4.setLayoutParams(relativeLayout$LayoutParams6);
        cr4.setScaleType(imageView$ScaleType0);
        cr4.setImageDrawable(DWo.PjT(context0, "tt_leftbackbutton_titlebar_photo_preview"));
        xX1.addView(cr4);
        Au au2 = new Au(context0);
        au2.setId(qla.WHM);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        relativeLayout$LayoutParams7.addRule(15);
        int v5 = qZS.Zh(context0, 16.0f);
        relativeLayout$LayoutParams7.leftMargin = v5;
        relativeLayout$LayoutParams7.rightMargin = v;
        relativeLayout$LayoutParams7.setMarginStart(v5);
        relativeLayout$LayoutParams7.setMarginEnd(v);
        relativeLayout$LayoutParams7.addRule(17, qla.xi);
        relativeLayout$LayoutParams7.addRule(0, qla.KLT);
        relativeLayout$LayoutParams7.addRule(1, qla.xi);
        relativeLayout$LayoutParams7.addRule(16, qla.KLT);
        au2.setLayoutParams(relativeLayout$LayoutParams7);
        au2.setEllipsize(textUtils$TruncateAt0);
        au2.setGravity(16);
        au2.setMaxLines(1);
        au2.setSingleLine(true);
        au2.setTextColor(-1);
        au2.setTextSize(2, 17.0f);
        xX1.addView(au2);
        JQp jQp1 = new JQp(context0);
        jQp1.setId(qla.KLT);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams8 = new RelativeLayout.LayoutParams(-2, -2);
        relativeLayout$LayoutParams8.addRule(21);
        relativeLayout$LayoutParams8.addRule(11);
        int v6 = qZS.Zh(context0, 14.0f);
        relativeLayout$LayoutParams8.rightMargin = v6;
        relativeLayout$LayoutParams8.setMarginEnd(v6);
        jQp1.setLayoutParams(relativeLayout$LayoutParams8);
        jQp1.setGravity(16);
        jQp1.setOrientation(1);
        xX1.addView(jQp1);
        Au au3 = new Au(context0);
        au3.setId(qla.RXa);
        LinearLayout.LayoutParams linearLayout$LayoutParams0 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams0.gravity = 1;
        au3.setLayoutParams(linearLayout$LayoutParams0);
        au3.setGravity(16);
        au3.setMaxLines(1);
        au3.setSingleLine(true);
        au3.setTextColor(-1);
        au3.setTextSize(2, 12.0f);
        jQp1.addView(au3);
        JQp jQp2 = new JQp(context0);
        jQp2.setId(qla.hx);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams9 = new RelativeLayout.LayoutParams(-2, qZS.Zh(context0, 40.0f));
        relativeLayout$LayoutParams9.addRule(12);
        relativeLayout$LayoutParams9.addRule(21);
        relativeLayout$LayoutParams9.addRule(11);
        jQp2.setLayoutParams(relativeLayout$LayoutParams9);
        jQp2.setGravity(16);
        jQp2.setOrientation(0);
        jQp2.setVisibility(8);
        this.addView(jQp2);
        Au au4 = new Au(context0);
        au4.setId(qla.gH);
        LinearLayout.LayoutParams linearLayout$LayoutParams1 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams1.leftMargin = v5;
        linearLayout$LayoutParams1.rightMargin = v4;
        linearLayout$LayoutParams1.setMarginEnd(v4);
        linearLayout$LayoutParams1.setMarginStart(v5);
        au4.setLayoutParams(linearLayout$LayoutParams1);
        au4.setText(Lrd.PjT(context0, "tt_00_00"));
        au4.setTextColor(-1);
        au4.setTextSize(2, 10.0f);
        jQp2.addView(au4);
        SeekBar seekBar0 = new SeekBar(context0);
        seekBar0.setId(qla.It);
        LinearLayout.LayoutParams linearLayout$LayoutParams2 = new LinearLayout.LayoutParams(0, qZS.Zh(context0, 5.0f));
        linearLayout$LayoutParams2.gravity = 16;
        seekBar0.setLayoutParams(linearLayout$LayoutParams2);
        seekBar0.setMax(100);
        seekBar0.setPadding(0, 0, 0, 0);
        seekBar0.setProgressDrawable(DWo.PjT(context0, "tt_seek_progress"));
        seekBar0.setThumb(DWo.PjT(context0, "tt_seek_thumb"));
        seekBar0.setThumbOffset(0);
        jQp2.addView(seekBar0);
        Au au5 = new Au(context0);
        au5.setId(qla.JU);
        LinearLayout.LayoutParams linearLayout$LayoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        linearLayout$LayoutParams3.leftMargin = v4;
        linearLayout$LayoutParams3.rightMargin = v5;
        linearLayout$LayoutParams3.setMarginEnd(v5);
        linearLayout$LayoutParams3.setMarginStart(v4);
        au5.setLayoutParams(linearLayout$LayoutParams3);
        au5.setText(Lrd.PjT(context0, "tt_00_00"));
        au5.setTextColor(-1);
        au5.setTextSize(2, 10.0f);
        jQp2.addView(au5);
        cr cr5 = new cr(context0);
        cr5.setId(qla.GP);
        cr5.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        cr5.setPadding(v5, 0, v5, 0);
        cr5.setScaleType(imageView$ScaleType0);
        cr5.setVisibility(8);
        cr5.setImageDrawable(Lrd.ReZ(context0, "tt_enlarge_video"));
        jQp2.addView(cr5);
        xf xf0 = new xf(context0);
        xf0.setId(qla.fU);
        xf0.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        this.addView(xf0);
        Au au6 = new Au(context0);
        au6.setId(qla.OnL);
        RelativeLayout.LayoutParams relativeLayout$LayoutParams10 = new RelativeLayout.LayoutParams(-2, -2);
        relativeLayout$LayoutParams10.leftMargin = v4;
        relativeLayout$LayoutParams10.addRule(9);
        relativeLayout$LayoutParams10.addRule(20);
        au6.setLayoutParams(relativeLayout$LayoutParams10);
        au6.setBackgroundColor(Color.parseColor("#00000000"));
        au6.setText("close");
        au6.setMinHeight(qZS.Zh(context0, 44.0f));
        au6.setCompoundDrawablesWithIntrinsicBounds(DWo.PjT(context0, "tt_shadow_btn_back"), null, null, null);
        this.addView(au6);
    }
}

